// THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT BY HAND!
#include "torch_api_for_generated.hpp"

value atg_dot(value self, value tensor) {
  CAMLparam2(self, tensor);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::dot(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(tensor))));
  )
}

value atg_dot_out(value out, value self, value tensor) {
  CAMLparam3(out, self, tensor);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::dot_out(out_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(tensor))));
  )
}

value atg_dropout(value input, double p, int train) {
  CAMLparam1(input);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::dropout(rc_tensor_from_ocaml(input), p, train != 0)));
  )
}

value atg_dropout_(value self, double p, int train) {
  CAMLparam1(self);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::dropout_(self_local, p, train != 0)));
  )
}

value atg_dsplit(value self, int64_t sections) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(to_ocaml_tensor_list(torch::dsplit(rc_tensor_from_ocaml(self), sections)));
  )
}

value atg_dsplit_array(value self, value indices) {
  CAMLparam2(self, indices);
  PROTECT(
    CAMLreturn(to_ocaml_tensor_list(torch::dsplit(rc_tensor_from_ocaml(self), vec_of_ocaml_int_list(indices))));
  )
}

value atg_dstack(value tensors) {
  CAMLparam1(tensors);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::dstack(of_ocaml_tensor_list(tensors))));
  )
}

value atg_dstack_out(value out, value tensors) {
  CAMLparam2(out, tensors);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::dstack_out(out_local, of_ocaml_tensor_list(tensors))));
  )
}

value atg_einsum(const char * equation, value tensors, value path) {
  CAMLparam2(tensors, path);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::einsum(std::string(equation), of_ocaml_tensor_list(tensors), Is_some(path) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(path))) : c10::OptionalArrayRef<int64_t>(std::nullopt))));
  )
}

value atg_elu(value self, value alpha, value scale, value input_scale) {
  CAMLparam4(self, alpha, scale, input_scale);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::elu(rc_tensor_from_ocaml(self), scalar_option_from_ocaml(alpha).value_or(1) , scalar_option_from_ocaml(scale).value_or(1) , scalar_option_from_ocaml(input_scale).value_or(1) )));
  )
}

value atg_elu_(value self, value alpha, value scale, value input_scale) {
  CAMLparam4(self, alpha, scale, input_scale);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::elu_(self_local, scalar_option_from_ocaml(alpha).value_or(1) , scalar_option_from_ocaml(scale).value_or(1) , scalar_option_from_ocaml(input_scale).value_or(1) )));
  )
}

value atg_elu_backward(value grad_output, value alpha, value scale, value input_scale, int is_result, value self_or_result) {
  CAMLparam5(grad_output, alpha, scale, input_scale, self_or_result);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::elu_backward(rc_tensor_from_ocaml(grad_output), *scalar_from_ocaml_noalloc(alpha), *scalar_from_ocaml_noalloc(scale), *scalar_from_ocaml_noalloc(input_scale), is_result != 0, rc_tensor_from_ocaml(self_or_result))));
  )
}

value atg_elu_backward_grad_input(value grad_input, value grad_output, value alpha, value scale, value input_scale, int is_result, value self_or_result) {
  CAMLparam5(grad_input, grad_output, alpha, scale, input_scale);
  CAMLxparam1(self_or_result);
  PROTECT(
    torch::Tensor grad_input_local = rc_tensor_from_ocaml(grad_input);
    CAMLreturn(rc_tensor_to_ocaml(torch::elu_backward_out(grad_input_local, rc_tensor_from_ocaml(grad_output), *scalar_from_ocaml_noalloc(alpha), *scalar_from_ocaml_noalloc(scale), *scalar_from_ocaml_noalloc(input_scale), is_result != 0, rc_tensor_from_ocaml(self_or_result))));
  )
}

value atg_elu_out(value out, value self, value alpha, value scale, value input_scale) {
  CAMLparam5(out, self, alpha, scale, input_scale);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::elu_out(out_local, rc_tensor_from_ocaml(self), scalar_option_from_ocaml(alpha).value_or(1) , scalar_option_from_ocaml(scale).value_or(1) , scalar_option_from_ocaml(input_scale).value_or(1) )));
  )
}

value atg_embedding(value weight, value indices, int64_t padding_idx, int scale_grad_by_freq, int sparse) {
  CAMLparam2(weight, indices);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::embedding(rc_tensor_from_ocaml(weight), rc_tensor_from_ocaml(indices), padding_idx, scale_grad_by_freq != 0, sparse != 0)));
  )
}

value atg_embedding_backward(value grad, value indices, int64_t num_weights, int64_t padding_idx, int scale_grad_by_freq, int sparse) {
  CAMLparam2(grad, indices);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::embedding_backward(rc_tensor_from_ocaml(grad), rc_tensor_from_ocaml(indices), num_weights, padding_idx, scale_grad_by_freq != 0, sparse != 0)));
  )
}

value atg_embedding_bag(value weight, value indices, value offsets, int scale_grad_by_freq, int64_t mode, int sparse, value per_sample_weights, int include_last_offset) {
  CAMLparam4(weight, indices, offsets, per_sample_weights);
  PROTECT(
    CAMLreturn(rc_tensors_to_ocaml_tuple(torch::embedding_bag(rc_tensor_from_ocaml(weight), rc_tensor_from_ocaml(indices), rc_tensor_from_ocaml(offsets), scale_grad_by_freq != 0, mode, sparse != 0, tensor_option_from_ocaml(per_sample_weights), include_last_offset != 0)));
  )
}

value atg_embedding_bag_padding_idx(value weight, value indices, value offsets, int scale_grad_by_freq, int64_t mode, int sparse, value per_sample_weights, int include_last_offset, value padding_idx) {
  CAMLparam5(weight, indices, offsets, per_sample_weights, padding_idx);
  PROTECT(
    CAMLreturn(rc_tensors_to_ocaml_tuple(torch::embedding_bag(rc_tensor_from_ocaml(weight), rc_tensor_from_ocaml(indices), rc_tensor_from_ocaml(offsets), scale_grad_by_freq != 0, mode, sparse != 0, tensor_option_from_ocaml(per_sample_weights), include_last_offset != 0, optional_int_from_ocaml(padding_idx))));
  )
}

value atg_embedding_dense_backward(value grad_output, value indices, int64_t num_weights, int64_t padding_idx, int scale_grad_by_freq) {
  CAMLparam2(grad_output, indices);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::embedding_dense_backward(rc_tensor_from_ocaml(grad_output), rc_tensor_from_ocaml(indices), num_weights, padding_idx, scale_grad_by_freq != 0)));
  )
}

value atg_embedding_dense_backward_out(value out, value grad_output, value indices, int64_t num_weights, int64_t padding_idx, int scale_grad_by_freq) {
  CAMLparam3(out, grad_output, indices);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::embedding_dense_backward_out(out_local, rc_tensor_from_ocaml(grad_output), rc_tensor_from_ocaml(indices), num_weights, padding_idx, scale_grad_by_freq != 0)));
  )
}

value atg_embedding_out(value out, value weight, value indices, int64_t padding_idx, int scale_grad_by_freq, int sparse) {
  CAMLparam3(out, weight, indices);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::embedding_out(out_local, rc_tensor_from_ocaml(weight), rc_tensor_from_ocaml(indices), padding_idx, scale_grad_by_freq != 0, sparse != 0)));
  )
}

value atg_embedding_renorm(value self, value indices, double max_norm, double norm_type) {
  CAMLparam2(self, indices);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::embedding_renorm(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(indices), max_norm, norm_type)));
  )
}

value atg_embedding_renorm_(value self, value indices, double max_norm, double norm_type) {
  CAMLparam2(self, indices);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::embedding_renorm_(self_local, rc_tensor_from_ocaml(indices), max_norm, norm_type)));
  )
}

value atg_embedding_renorm_out(value out, value self, value indices, double max_norm, double norm_type) {
  CAMLparam3(out, self, indices);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::embedding_renorm_out(out_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(indices), max_norm, norm_type)));
  )
}

value atg_embedding_sparse_backward(value grad, value indices, int64_t num_weights, int64_t padding_idx, int scale_grad_by_freq) {
  CAMLparam2(grad, indices);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::embedding_sparse_backward(rc_tensor_from_ocaml(grad), rc_tensor_from_ocaml(indices), num_weights, padding_idx, scale_grad_by_freq != 0)));
  )
}

value atg_empty(value size, int options_kind, int options_device) {
  CAMLparam1(size);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::empty(vec_of_ocaml_int_list(size), at::device(device_of_int(options_device)).dtype(at::ScalarType(options_kind)))));
  )
}

value atg_empty_like(value self) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::empty_like(rc_tensor_from_ocaml(self))));
  )
}

value atg_empty_like_out(value out, value self) {
  CAMLparam2(out, self);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::empty_like_out(out_local, rc_tensor_from_ocaml(self))));
  )
}

value atg_empty_out(value out, value size) {
  CAMLparam2(out, size);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::empty_out(out_local, vec_of_ocaml_int_list(size))));
  )
}

value atg_empty_permuted(value size, value physical_layout, int options_kind, int options_device) {
  CAMLparam2(size, physical_layout);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::empty_permuted(vec_of_ocaml_int_list(size), vec_of_ocaml_int_list(physical_layout), at::device(device_of_int(options_device)).dtype(at::ScalarType(options_kind)))));
  )
}

value atg_empty_permuted_out(value out, value size, value physical_layout) {
  CAMLparam3(out, size, physical_layout);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::empty_permuted_out(out_local, vec_of_ocaml_int_list(size), vec_of_ocaml_int_list(physical_layout))));
  )
}

value atg_empty_quantized(value size, value qtensor, int options_kind, int options_device) {
  CAMLparam2(size, qtensor);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::empty_quantized(vec_of_ocaml_int_list(size), rc_tensor_from_ocaml(qtensor), at::device(device_of_int(options_device)).dtype(at::ScalarType(options_kind)))));
  )
}

value atg_empty_quantized_out(value out, value size, value qtensor) {
  CAMLparam3(out, size, qtensor);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::empty_quantized_out(out_local, vec_of_ocaml_int_list(size), rc_tensor_from_ocaml(qtensor))));
  )
}

value atg_empty_strided(value size, value stride, int options_kind, int options_device) {
  CAMLparam2(size, stride);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::empty_strided(vec_of_ocaml_int_list(size), vec_of_ocaml_int_list(stride), at::device(device_of_int(options_device)).dtype(at::ScalarType(options_kind)))));
  )
}

value atg_empty_strided_out(value out, value size, value stride) {
  CAMLparam3(out, size, stride);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::empty_strided_out(out_local, vec_of_ocaml_int_list(size), vec_of_ocaml_int_list(stride))));
  )
}

value atg_eq(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::eq(rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(other))));
  )
}

value atg_eq_(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.eq_(*scalar_from_ocaml_noalloc(other))));
  )
}

value atg_eq_scalar_out(value out, value self, value other) {
  CAMLparam3(out, self, other);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::eq_out(out_local, rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(other))));
  )
}

value atg_eq_tensor(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::eq(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_eq_tensor_(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.eq_(rc_tensor_from_ocaml(other))));
  )
}

value atg_eq_tensor_out(value out, value self, value other) {
  CAMLparam3(out, self, other);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::eq_out(out_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_equal(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(Val_bool(torch::equal(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_erf(value self) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::erf(rc_tensor_from_ocaml(self))));
  )
}

value atg_erf_(value self) {
  CAMLparam1(self);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::erf_(self_local)));
  )
}

value atg_erf_out(value out, value self) {
  CAMLparam2(out, self);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::erf_out(out_local, rc_tensor_from_ocaml(self))));
  )
}

value atg_erfc(value self) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::erfc(rc_tensor_from_ocaml(self))));
  )
}

value atg_erfc_(value self) {
  CAMLparam1(self);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::erfc_(self_local)));
  )
}

value atg_erfc_out(value out, value self) {
  CAMLparam2(out, self);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::erfc_out(out_local, rc_tensor_from_ocaml(self))));
  )
}

value atg_erfinv(value self) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::erfinv(rc_tensor_from_ocaml(self))));
  )
}

value atg_erfinv_(value self) {
  CAMLparam1(self);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.erfinv_()));
  )
}

value atg_erfinv_out(value out, value self) {
  CAMLparam2(out, self);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::erfinv_out(out_local, rc_tensor_from_ocaml(self))));
  )
}

value atg_exp(value self) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::exp(rc_tensor_from_ocaml(self))));
  )
}

value atg_exp2(value self) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::exp2(rc_tensor_from_ocaml(self))));
  )
}

value atg_exp2_(value self) {
  CAMLparam1(self);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::exp2_(self_local)));
  )
}

value atg_exp2_out(value out, value self) {
  CAMLparam2(out, self);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::exp2_out(out_local, rc_tensor_from_ocaml(self))));
  )
}

value atg_exp_(value self) {
  CAMLparam1(self);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::exp_(self_local)));
  )
}

value atg_exp_out(value out, value self) {
  CAMLparam2(out, self);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::exp_out(out_local, rc_tensor_from_ocaml(self))));
  )
}

value atg_expand(value self, value size, int implicit) {
  CAMLparam2(self, size);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(rc_tensor_from_ocaml(self).expand(vec_of_ocaml_int_list(size), implicit != 0)));
  )
}

value atg_expand_as(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(rc_tensor_from_ocaml(self).expand_as(rc_tensor_from_ocaml(other))));
  )
}

value atg_expand_copy(value self, value size, int implicit) {
  CAMLparam2(self, size);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::expand_copy(rc_tensor_from_ocaml(self), vec_of_ocaml_int_list(size), implicit != 0)));
  )
}

value atg_expand_copy_out(value out, value self, value size, int implicit) {
  CAMLparam3(out, self, size);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::expand_copy_out(out_local, rc_tensor_from_ocaml(self), vec_of_ocaml_int_list(size), implicit != 0)));
  )
}

value atg_expm1(value self) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::expm1(rc_tensor_from_ocaml(self))));
  )
}

value atg_expm1_(value self) {
  CAMLparam1(self);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::expm1_(self_local)));
  )
}

value atg_expm1_out(value out, value self) {
  CAMLparam2(out, self);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::expm1_out(out_local, rc_tensor_from_ocaml(self))));
  )
}

value atg_exponential(value self, double lambd) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::exponential(rc_tensor_from_ocaml(self), lambd)));
  )
}

value atg_exponential_(value self, double lambd) {
  CAMLparam1(self);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.exponential_(lambd)));
  )
}

value atg_exponential_out(value out, value self, double lambd) {
  CAMLparam2(out, self);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::exponential_out(out_local, rc_tensor_from_ocaml(self), lambd)));
  )
}

value atg_eye(int64_t n, int options_kind, int options_device) {
  CAMLparam0();
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::eye(n, at::device(device_of_int(options_device)).dtype(at::ScalarType(options_kind)))));
  )
}

value atg_eye_m(int64_t n, int64_t m, int options_kind, int options_device) {
  CAMLparam0();
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::eye(n, m, at::device(device_of_int(options_device)).dtype(at::ScalarType(options_kind)))));
  )
}

value atg_eye_m_out(value out, int64_t n, int64_t m) {
  CAMLparam1(out);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::eye_out(out_local, n, m)));
  )
}

value atg_eye_out(value out, int64_t n) {
  CAMLparam1(out);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::eye_out(out_local, n)));
  )
}

value atg_fake_quantize_per_channel_affine(value self, value scale, value zero_point, int64_t axis, int64_t quant_min, int64_t quant_max) {
  CAMLparam3(self, scale, zero_point);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fake_quantize_per_channel_affine(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(scale), rc_tensor_from_ocaml(zero_point), axis, quant_min, quant_max)));
  )
}

value atg_fake_quantize_per_channel_affine_cachemask(value self, value scale, value zero_point, int64_t axis, int64_t quant_min, int64_t quant_max) {
  CAMLparam3(self, scale, zero_point);
  PROTECT(
    CAMLreturn(rc_tensors_to_ocaml_tuple(torch::fake_quantize_per_channel_affine_cachemask(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(scale), rc_tensor_from_ocaml(zero_point), axis, quant_min, quant_max)));
  )
}

value atg_fake_quantize_per_channel_affine_cachemask_backward(value grad, value mask) {
  CAMLparam2(grad, mask);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fake_quantize_per_channel_affine_cachemask_backward(rc_tensor_from_ocaml(grad), rc_tensor_from_ocaml(mask))));
  )
}

value atg_fake_quantize_per_channel_affine_cachemask_out(value out0, value out1, value self, value scale, value zero_point, int64_t axis, int64_t quant_min, int64_t quant_max) {
  CAMLparam5(out0, out1, self, scale, zero_point);
  PROTECT(
    torch::Tensor out0_local = rc_tensor_from_ocaml(out0);
    torch::Tensor out1_local = rc_tensor_from_ocaml(out1);
    CAMLreturn(rc_tensors_to_ocaml_tuple(torch::fake_quantize_per_channel_affine_cachemask_out(out0_local, out1_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(scale), rc_tensor_from_ocaml(zero_point), axis, quant_min, quant_max)));
  )
}

value atg_fake_quantize_per_tensor_affine(value self, double scale, int64_t zero_point, int64_t quant_min, int64_t quant_max) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fake_quantize_per_tensor_affine(rc_tensor_from_ocaml(self), scale, zero_point, quant_min, quant_max)));
  )
}

value atg_fake_quantize_per_tensor_affine_cachemask(value self, double scale, int64_t zero_point, int64_t quant_min, int64_t quant_max) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensors_to_ocaml_tuple(torch::fake_quantize_per_tensor_affine_cachemask(rc_tensor_from_ocaml(self), scale, zero_point, quant_min, quant_max)));
  )
}

value atg_fake_quantize_per_tensor_affine_cachemask_backward(value grad, value mask) {
  CAMLparam2(grad, mask);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fake_quantize_per_tensor_affine_cachemask_backward(rc_tensor_from_ocaml(grad), rc_tensor_from_ocaml(mask))));
  )
}

value atg_fake_quantize_per_tensor_affine_cachemask_out(value out0, value out1, value self, double scale, int64_t zero_point, int64_t quant_min, int64_t quant_max) {
  CAMLparam3(out0, out1, self);
  PROTECT(
    torch::Tensor out0_local = rc_tensor_from_ocaml(out0);
    torch::Tensor out1_local = rc_tensor_from_ocaml(out1);
    CAMLreturn(rc_tensors_to_ocaml_tuple(torch::fake_quantize_per_tensor_affine_cachemask_out(out0_local, out1_local, rc_tensor_from_ocaml(self), scale, zero_point, quant_min, quant_max)));
  )
}

value atg_fake_quantize_per_tensor_affine_tensor_qparams(value self, value scale, value zero_point, int64_t quant_min, int64_t quant_max) {
  CAMLparam3(self, scale, zero_point);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fake_quantize_per_tensor_affine(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(scale), rc_tensor_from_ocaml(zero_point), quant_min, quant_max)));
  )
}

value atg_fbgemm_linear_fp16_weight(value input, value packed_weight, value bias) {
  CAMLparam3(input, packed_weight, bias);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fbgemm_linear_fp16_weight(rc_tensor_from_ocaml(input), rc_tensor_from_ocaml(packed_weight), rc_tensor_from_ocaml(bias))));
  )
}

value atg_fbgemm_linear_fp16_weight_fp32_activation(value input, value packed_weight, value bias) {
  CAMLparam3(input, packed_weight, bias);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fbgemm_linear_fp16_weight_fp32_activation(rc_tensor_from_ocaml(input), rc_tensor_from_ocaml(packed_weight), rc_tensor_from_ocaml(bias))));
  )
}

value atg_fbgemm_linear_int8_weight(value input, value weight, value packed, value col_offsets, value weight_scale, value weight_zero_point, value bias) {
  CAMLparam5(input, weight, packed, col_offsets, weight_scale);
  CAMLxparam2(weight_zero_point, bias);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fbgemm_linear_int8_weight(rc_tensor_from_ocaml(input), rc_tensor_from_ocaml(weight), rc_tensor_from_ocaml(packed), rc_tensor_from_ocaml(col_offsets), *scalar_from_ocaml_noalloc(weight_scale), *scalar_from_ocaml_noalloc(weight_zero_point), rc_tensor_from_ocaml(bias))));
  )
}

value atg_fbgemm_linear_int8_weight_fp32_activation(value input, value weight, value packed, value col_offsets, value weight_scale, value weight_zero_point, value bias) {
  CAMLparam5(input, weight, packed, col_offsets, weight_scale);
  CAMLxparam2(weight_zero_point, bias);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fbgemm_linear_int8_weight_fp32_activation(rc_tensor_from_ocaml(input), rc_tensor_from_ocaml(weight), rc_tensor_from_ocaml(packed), rc_tensor_from_ocaml(col_offsets), *scalar_from_ocaml_noalloc(weight_scale), *scalar_from_ocaml_noalloc(weight_zero_point), rc_tensor_from_ocaml(bias))));
  )
}

value atg_fbgemm_pack_gemm_matrix_fp16(value input) {
  CAMLparam1(input);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fbgemm_pack_gemm_matrix_fp16(rc_tensor_from_ocaml(input))));
  )
}

value atg_fbgemm_pack_quantized_matrix(value input) {
  CAMLparam1(input);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fbgemm_pack_quantized_matrix(rc_tensor_from_ocaml(input))));
  )
}

value atg_fbgemm_pack_quantized_matrix_kn(value input, int64_t K, int64_t n) {
  CAMLparam1(input);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fbgemm_pack_quantized_matrix(rc_tensor_from_ocaml(input), K, n)));
  )
}

value atg_feature_alpha_dropout(value input, double p, int train) {
  CAMLparam1(input);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::feature_alpha_dropout(rc_tensor_from_ocaml(input), p, train != 0)));
  )
}

value atg_feature_alpha_dropout_(value self, double p, int train) {
  CAMLparam1(self);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::feature_alpha_dropout_(self_local, p, train != 0)));
  )
}

value atg_feature_dropout(value input, double p, int train) {
  CAMLparam1(input);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::feature_dropout(rc_tensor_from_ocaml(input), p, train != 0)));
  )
}

value atg_feature_dropout_(value self, double p, int train) {
  CAMLparam1(self);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::feature_dropout_(self_local, p, train != 0)));
  )
}

value atg_fft_fft(value self, value n, int64_t dim, value norm) {
  CAMLparam3(self, n, norm);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_fft(rc_tensor_from_ocaml(self), optional_int_from_ocaml(n), dim, optional_string_from_ocaml(norm))));
  )
}

value atg_fft_fft2(value self, value s, value dim, value norm) {
  CAMLparam4(self, s, dim, norm);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_fft2(rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), vec_of_ocaml_int_list(dim), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_fft2_out(value out, value self, value s, value dim, value norm) {
  CAMLparam5(out, self, s, dim, norm);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_fft2_out(out_local, rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), vec_of_ocaml_int_list(dim), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_fft_out(value out, value self, value n, int64_t dim, value norm) {
  CAMLparam4(out, self, n, norm);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_fft_out(out_local, rc_tensor_from_ocaml(self), optional_int_from_ocaml(n), dim, optional_string_from_ocaml(norm))));
  )
}

value atg_fft_fftfreq(int64_t n, double d, int options_kind, int options_device) {
  CAMLparam0();
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_fftfreq(n, d, at::device(device_of_int(options_device)).dtype(at::ScalarType(options_kind)))));
  )
}

value atg_fft_fftfreq_out(value out, int64_t n, double d) {
  CAMLparam1(out);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_fftfreq_out(out_local, n, d)));
  )
}

value atg_fft_fftn(value self, value s, value dim, value norm) {
  CAMLparam4(self, s, dim, norm);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_fftn(rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), Is_some(dim) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(dim))) : c10::OptionalArrayRef<int64_t>(std::nullopt), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_fftn_out(value out, value self, value s, value dim, value norm) {
  CAMLparam5(out, self, s, dim, norm);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_fftn_out(out_local, rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), Is_some(dim) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(dim))) : c10::OptionalArrayRef<int64_t>(std::nullopt), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_fftshift(value self, value dim) {
  CAMLparam2(self, dim);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_fftshift(rc_tensor_from_ocaml(self), Is_some(dim) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(dim))) : c10::OptionalArrayRef<int64_t>(std::nullopt))));
  )
}

value atg_fft_hfft(value self, value n, int64_t dim, value norm) {
  CAMLparam3(self, n, norm);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_hfft(rc_tensor_from_ocaml(self), optional_int_from_ocaml(n), dim, optional_string_from_ocaml(norm))));
  )
}

value atg_fft_hfft2(value self, value s, value dim, value norm) {
  CAMLparam4(self, s, dim, norm);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_hfft2(rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), vec_of_ocaml_int_list(dim), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_hfft2_out(value out, value self, value s, value dim, value norm) {
  CAMLparam5(out, self, s, dim, norm);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_hfft2_out(out_local, rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), vec_of_ocaml_int_list(dim), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_hfft_out(value out, value self, value n, int64_t dim, value norm) {
  CAMLparam4(out, self, n, norm);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_hfft_out(out_local, rc_tensor_from_ocaml(self), optional_int_from_ocaml(n), dim, optional_string_from_ocaml(norm))));
  )
}

value atg_fft_hfftn(value self, value s, value dim, value norm) {
  CAMLparam4(self, s, dim, norm);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_hfftn(rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), Is_some(dim) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(dim))) : c10::OptionalArrayRef<int64_t>(std::nullopt), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_hfftn_out(value out, value self, value s, value dim, value norm) {
  CAMLparam5(out, self, s, dim, norm);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_hfftn_out(out_local, rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), Is_some(dim) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(dim))) : c10::OptionalArrayRef<int64_t>(std::nullopt), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_ifft(value self, value n, int64_t dim, value norm) {
  CAMLparam3(self, n, norm);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_ifft(rc_tensor_from_ocaml(self), optional_int_from_ocaml(n), dim, optional_string_from_ocaml(norm))));
  )
}

value atg_fft_ifft2(value self, value s, value dim, value norm) {
  CAMLparam4(self, s, dim, norm);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_ifft2(rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), vec_of_ocaml_int_list(dim), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_ifft2_out(value out, value self, value s, value dim, value norm) {
  CAMLparam5(out, self, s, dim, norm);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_ifft2_out(out_local, rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), vec_of_ocaml_int_list(dim), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_ifft_out(value out, value self, value n, int64_t dim, value norm) {
  CAMLparam4(out, self, n, norm);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_ifft_out(out_local, rc_tensor_from_ocaml(self), optional_int_from_ocaml(n), dim, optional_string_from_ocaml(norm))));
  )
}

value atg_fft_ifftn(value self, value s, value dim, value norm) {
  CAMLparam4(self, s, dim, norm);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_ifftn(rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), Is_some(dim) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(dim))) : c10::OptionalArrayRef<int64_t>(std::nullopt), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_ifftn_out(value out, value self, value s, value dim, value norm) {
  CAMLparam5(out, self, s, dim, norm);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_ifftn_out(out_local, rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), Is_some(dim) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(dim))) : c10::OptionalArrayRef<int64_t>(std::nullopt), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_ifftshift(value self, value dim) {
  CAMLparam2(self, dim);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_ifftshift(rc_tensor_from_ocaml(self), Is_some(dim) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(dim))) : c10::OptionalArrayRef<int64_t>(std::nullopt))));
  )
}

value atg_fft_ihfft(value self, value n, int64_t dim, value norm) {
  CAMLparam3(self, n, norm);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_ihfft(rc_tensor_from_ocaml(self), optional_int_from_ocaml(n), dim, optional_string_from_ocaml(norm))));
  )
}

value atg_fft_ihfft2(value self, value s, value dim, value norm) {
  CAMLparam4(self, s, dim, norm);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_ihfft2(rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), vec_of_ocaml_int_list(dim), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_ihfft2_out(value out, value self, value s, value dim, value norm) {
  CAMLparam5(out, self, s, dim, norm);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_ihfft2_out(out_local, rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), vec_of_ocaml_int_list(dim), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_ihfft_out(value out, value self, value n, int64_t dim, value norm) {
  CAMLparam4(out, self, n, norm);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_ihfft_out(out_local, rc_tensor_from_ocaml(self), optional_int_from_ocaml(n), dim, optional_string_from_ocaml(norm))));
  )
}

value atg_fft_ihfftn(value self, value s, value dim, value norm) {
  CAMLparam4(self, s, dim, norm);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_ihfftn(rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), Is_some(dim) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(dim))) : c10::OptionalArrayRef<int64_t>(std::nullopt), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_ihfftn_out(value out, value self, value s, value dim, value norm) {
  CAMLparam5(out, self, s, dim, norm);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_ihfftn_out(out_local, rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), Is_some(dim) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(dim))) : c10::OptionalArrayRef<int64_t>(std::nullopt), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_irfft(value self, value n, int64_t dim, value norm) {
  CAMLparam3(self, n, norm);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_irfft(rc_tensor_from_ocaml(self), optional_int_from_ocaml(n), dim, optional_string_from_ocaml(norm))));
  )
}

value atg_fft_irfft2(value self, value s, value dim, value norm) {
  CAMLparam4(self, s, dim, norm);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_irfft2(rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), vec_of_ocaml_int_list(dim), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_irfft2_out(value out, value self, value s, value dim, value norm) {
  CAMLparam5(out, self, s, dim, norm);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_irfft2_out(out_local, rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), vec_of_ocaml_int_list(dim), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_irfft_out(value out, value self, value n, int64_t dim, value norm) {
  CAMLparam4(out, self, n, norm);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_irfft_out(out_local, rc_tensor_from_ocaml(self), optional_int_from_ocaml(n), dim, optional_string_from_ocaml(norm))));
  )
}

value atg_fft_irfftn(value self, value s, value dim, value norm) {
  CAMLparam4(self, s, dim, norm);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_irfftn(rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), Is_some(dim) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(dim))) : c10::OptionalArrayRef<int64_t>(std::nullopt), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_irfftn_out(value out, value self, value s, value dim, value norm) {
  CAMLparam5(out, self, s, dim, norm);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_irfftn_out(out_local, rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), Is_some(dim) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(dim))) : c10::OptionalArrayRef<int64_t>(std::nullopt), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_rfft(value self, value n, int64_t dim, value norm) {
  CAMLparam3(self, n, norm);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_rfft(rc_tensor_from_ocaml(self), optional_int_from_ocaml(n), dim, optional_string_from_ocaml(norm))));
  )
}

value atg_fft_rfft2(value self, value s, value dim, value norm) {
  CAMLparam4(self, s, dim, norm);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_rfft2(rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), vec_of_ocaml_int_list(dim), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_rfft2_out(value out, value self, value s, value dim, value norm) {
  CAMLparam5(out, self, s, dim, norm);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_rfft2_out(out_local, rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), vec_of_ocaml_int_list(dim), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_rfft_out(value out, value self, value n, int64_t dim, value norm) {
  CAMLparam4(out, self, n, norm);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_rfft_out(out_local, rc_tensor_from_ocaml(self), optional_int_from_ocaml(n), dim, optional_string_from_ocaml(norm))));
  )
}

value atg_fft_rfftfreq(int64_t n, double d, int options_kind, int options_device) {
  CAMLparam0();
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_rfftfreq(n, d, at::device(device_of_int(options_device)).dtype(at::ScalarType(options_kind)))));
  )
}

value atg_fft_rfftfreq_out(value out, int64_t n, double d) {
  CAMLparam1(out);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_rfftfreq_out(out_local, n, d)));
  )
}

value atg_fft_rfftn(value self, value s, value dim, value norm) {
  CAMLparam4(self, s, dim, norm);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_rfftn(rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), Is_some(dim) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(dim))) : c10::OptionalArrayRef<int64_t>(std::nullopt), optional_string_from_ocaml(norm))));
  )
}

value atg_fft_rfftn_out(value out, value self, value s, value dim, value norm) {
  CAMLparam5(out, self, s, dim, norm);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fft_rfftn_out(out_local, rc_tensor_from_ocaml(self), Is_some(s) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(s))) : c10::OptionalArrayRef<int64_t>(std::nullopt), Is_some(dim) ? c10::OptionalArrayRef<int64_t>(vec_of_ocaml_int_list(Some_val(dim))) : c10::OptionalArrayRef<int64_t>(std::nullopt), optional_string_from_ocaml(norm))));
  )
}

value atg_fill(value self, value value_) {
  CAMLparam2(self, value_);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fill(rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(value_))));
  )
}

value atg_fill_(value self, value value_) {
  CAMLparam2(self, value_);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::fill_(self_local, *scalar_from_ocaml_noalloc(value_))));
  )
}

value atg_fill_diagonal_(value self, value fill_value, int wrap) {
  CAMLparam2(self, fill_value);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.fill_diagonal_(*scalar_from_ocaml_noalloc(fill_value), wrap != 0)));
  )
}

value atg_fill_scalar_out(value out, value self, value value_) {
  CAMLparam3(out, self, value_);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fill_out(out_local, rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(value_))));
  )
}

value atg_fill_tensor(value self, value value_) {
  CAMLparam2(self, value_);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fill(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(value_))));
  )
}

value atg_fill_tensor_(value self, value value_) {
  CAMLparam2(self, value_);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::fill_(self_local, rc_tensor_from_ocaml(value_))));
  )
}

value atg_fill_tensor_out(value out, value self, value value_) {
  CAMLparam3(out, self, value_);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fill_out(out_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(value_))));
  )
}

value atg_fix(value self) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fix(rc_tensor_from_ocaml(self))));
  )
}

value atg_fix_(value self) {
  CAMLparam1(self);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::fix_(self_local)));
  )
}

value atg_fix_out(value out, value self) {
  CAMLparam2(out, self);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fix_out(out_local, rc_tensor_from_ocaml(self))));
  )
}

value atg_flatten(value self, int64_t start_dim, int64_t end_dim) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::flatten(rc_tensor_from_ocaml(self), start_dim, end_dim)));
  )
}

value atg_flatten_dense_tensors(value tensors) {
  CAMLparam1(tensors);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::flatten_dense_tensors(of_ocaml_tensor_list(tensors))));
  )
}

value atg_flip(value self, value dims) {
  CAMLparam2(self, dims);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::flip(rc_tensor_from_ocaml(self), vec_of_ocaml_int_list(dims))));
  )
}

value atg_flip_out(value out, value self, value dims) {
  CAMLparam3(out, self, dims);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::flip_out(out_local, rc_tensor_from_ocaml(self), vec_of_ocaml_int_list(dims))));
  )
}

value atg_fliplr(value self) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fliplr(rc_tensor_from_ocaml(self))));
  )
}

value atg_flipud(value self) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::flipud(rc_tensor_from_ocaml(self))));
  )
}

value atg_float_power(value self, value exponent) {
  CAMLparam2(self, exponent);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::float_power(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(exponent))));
  )
}

value atg_float_power_(value self, value exponent) {
  CAMLparam2(self, exponent);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.float_power_(*scalar_from_ocaml_noalloc(exponent))));
  )
}

value atg_float_power_scalar(value self, value exponent) {
  CAMLparam2(self, exponent);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::float_power(*scalar_from_ocaml_noalloc(self), rc_tensor_from_ocaml(exponent))));
  )
}

value atg_float_power_scalar_out(value out, value self, value exponent) {
  CAMLparam3(out, self, exponent);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::float_power_out(out_local, *scalar_from_ocaml_noalloc(self), rc_tensor_from_ocaml(exponent))));
  )
}

value atg_float_power_tensor_(value self, value exponent) {
  CAMLparam2(self, exponent);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.float_power_(rc_tensor_from_ocaml(exponent))));
  )
}

value atg_float_power_tensor_scalar(value self, value exponent) {
  CAMLparam2(self, exponent);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::float_power(rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(exponent))));
  )
}

value atg_float_power_tensor_scalar_out(value out, value self, value exponent) {
  CAMLparam3(out, self, exponent);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::float_power_out(out_local, rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(exponent))));
  )
}

value atg_float_power_tensor_tensor_out(value out, value self, value exponent) {
  CAMLparam3(out, self, exponent);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::float_power_out(out_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(exponent))));
  )
}

value atg_floor(value self) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::floor(rc_tensor_from_ocaml(self))));
  )
}

value atg_floor_(value self) {
  CAMLparam1(self);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::floor_(self_local)));
  )
}

value atg_floor_divide(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::floor_divide(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_floor_divide_(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.floor_divide_(rc_tensor_from_ocaml(other))));
  )
}

value atg_floor_divide_out(value out, value self, value other) {
  CAMLparam3(out, self, other);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::floor_divide_out(out_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_floor_divide_scalar(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::floor_divide(rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(other))));
  )
}

value atg_floor_divide_scalar_(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.floor_divide_(*scalar_from_ocaml_noalloc(other))));
  )
}

value atg_floor_divide_scalar_out(value out, value self, value other) {
  CAMLparam3(out, self, other);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::floor_divide_out(out_local, rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(other))));
  )
}

value atg_floor_out(value out, value self) {
  CAMLparam2(out, self);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::floor_out(out_local, rc_tensor_from_ocaml(self))));
  )
}

value atg_fmax(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fmax(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_fmax_out(value out, value self, value other) {
  CAMLparam3(out, self, other);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fmax_out(out_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_fmin(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fmin(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_fmin_out(value out, value self, value other) {
  CAMLparam3(out, self, other);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fmin_out(out_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_fmod(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fmod(rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(other))));
  )
}

value atg_fmod_(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.fmod_(*scalar_from_ocaml_noalloc(other))));
  )
}

value atg_fmod_scalar_out(value out, value self, value other) {
  CAMLparam3(out, self, other);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fmod_out(out_local, rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(other))));
  )
}

value atg_fmod_tensor(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fmod(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_fmod_tensor_(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.fmod_(rc_tensor_from_ocaml(other))));
  )
}

value atg_fmod_tensor_out(value out, value self, value other) {
  CAMLparam3(out, self, other);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::fmod_out(out_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_frac(value self) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::frac(rc_tensor_from_ocaml(self))));
  )
}

value atg_frac_(value self) {
  CAMLparam1(self);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::frac_(self_local)));
  )
}

value atg_frac_out(value out, value self) {
  CAMLparam2(out, self);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::frac_out(out_local, rc_tensor_from_ocaml(self))));
  )
}

value atg_fractional_max_pool2d(value self, value kernel_size, value output_size, value random_samples) {
  CAMLparam4(self, kernel_size, output_size, random_samples);
  PROTECT(
    CAMLreturn(rc_tensors_to_ocaml_tuple(torch::fractional_max_pool2d(rc_tensor_from_ocaml(self), vec_of_ocaml_int_list(kernel_size), vec_of_ocaml_int_list(output_size), rc_tensor_from_ocaml(random_samples))));
  )
}

value atg_fractional_max_pool2d_backward(value grad_output, value self, value kernel_size, value output_size, value indices) {
  CAMLparam5(grad_output, self, kernel_size, output_size, indices);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fractional_max_pool2d_backward(rc_tensor_from_ocaml(grad_output), rc_tensor_from_ocaml(self), vec_of_ocaml_int_list(kernel_size), vec_of_ocaml_int_list(output_size), rc_tensor_from_ocaml(indices))));
  )
}

value atg_fractional_max_pool2d_backward_grad_input(value grad_input, value grad_output, value self, value kernel_size, value output_size, value indices) {
  CAMLparam5(grad_input, grad_output, self, kernel_size, output_size);
  CAMLxparam1(indices);
  PROTECT(
    torch::Tensor grad_input_local = rc_tensor_from_ocaml(grad_input);
    CAMLreturn(rc_tensor_to_ocaml(torch::fractional_max_pool2d_backward_out(grad_input_local, rc_tensor_from_ocaml(grad_output), rc_tensor_from_ocaml(self), vec_of_ocaml_int_list(kernel_size), vec_of_ocaml_int_list(output_size), rc_tensor_from_ocaml(indices))));
  )
}

value atg_fractional_max_pool2d_output(value output, value indices, value self, value kernel_size, value output_size, value random_samples) {
  CAMLparam5(output, indices, self, kernel_size, output_size);
  CAMLxparam1(random_samples);
  PROTECT(
    torch::Tensor output_local = rc_tensor_from_ocaml(output);
    torch::Tensor indices_local = rc_tensor_from_ocaml(indices);
    CAMLreturn(rc_tensors_to_ocaml_tuple(torch::fractional_max_pool2d_out(output_local, indices_local, rc_tensor_from_ocaml(self), vec_of_ocaml_int_list(kernel_size), vec_of_ocaml_int_list(output_size), rc_tensor_from_ocaml(random_samples))));
  )
}

value atg_fractional_max_pool3d(value self, value kernel_size, value output_size, value random_samples) {
  CAMLparam4(self, kernel_size, output_size, random_samples);
  PROTECT(
    CAMLreturn(rc_tensors_to_ocaml_tuple(torch::fractional_max_pool3d(rc_tensor_from_ocaml(self), vec_of_ocaml_int_list(kernel_size), vec_of_ocaml_int_list(output_size), rc_tensor_from_ocaml(random_samples))));
  )
}

value atg_fractional_max_pool3d_backward(value grad_output, value self, value kernel_size, value output_size, value indices) {
  CAMLparam5(grad_output, self, kernel_size, output_size, indices);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::fractional_max_pool3d_backward(rc_tensor_from_ocaml(grad_output), rc_tensor_from_ocaml(self), vec_of_ocaml_int_list(kernel_size), vec_of_ocaml_int_list(output_size), rc_tensor_from_ocaml(indices))));
  )
}

value atg_fractional_max_pool3d_backward_grad_input(value grad_input, value grad_output, value self, value kernel_size, value output_size, value indices) {
  CAMLparam5(grad_input, grad_output, self, kernel_size, output_size);
  CAMLxparam1(indices);
  PROTECT(
    torch::Tensor grad_input_local = rc_tensor_from_ocaml(grad_input);
    CAMLreturn(rc_tensor_to_ocaml(torch::fractional_max_pool3d_backward_out(grad_input_local, rc_tensor_from_ocaml(grad_output), rc_tensor_from_ocaml(self), vec_of_ocaml_int_list(kernel_size), vec_of_ocaml_int_list(output_size), rc_tensor_from_ocaml(indices))));
  )
}

value atg_fractional_max_pool3d_output(value output, value indices, value self, value kernel_size, value output_size, value random_samples) {
  CAMLparam5(output, indices, self, kernel_size, output_size);
  CAMLxparam1(random_samples);
  PROTECT(
    torch::Tensor output_local = rc_tensor_from_ocaml(output);
    torch::Tensor indices_local = rc_tensor_from_ocaml(indices);
    CAMLreturn(rc_tensors_to_ocaml_tuple(torch::fractional_max_pool3d_out(output_local, indices_local, rc_tensor_from_ocaml(self), vec_of_ocaml_int_list(kernel_size), vec_of_ocaml_int_list(output_size), rc_tensor_from_ocaml(random_samples))));
  )
}

value atg_frexp(value self) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensors_to_ocaml_tuple(torch::frexp(rc_tensor_from_ocaml(self))));
  )
}

value atg_frexp_tensor_out(value mantissa, value exponent, value self) {
  CAMLparam3(mantissa, exponent, self);
  PROTECT(
    torch::Tensor mantissa_local = rc_tensor_from_ocaml(mantissa);
    torch::Tensor exponent_local = rc_tensor_from_ocaml(exponent);
    CAMLreturn(rc_tensors_to_ocaml_tuple(torch::frexp_out(mantissa_local, exponent_local, rc_tensor_from_ocaml(self))));
  )
}

value atg_frobenius_norm(value self, value dim, int keepdim) {
  CAMLparam2(self, dim);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::frobenius_norm(rc_tensor_from_ocaml(self), vec_of_ocaml_int_list(dim), keepdim != 0)));
  )
}

value atg_frobenius_norm_out(value out, value self, value dim, int keepdim) {
  CAMLparam3(out, self, dim);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::frobenius_norm_out(out_local, rc_tensor_from_ocaml(self), vec_of_ocaml_int_list(dim), keepdim != 0)));
  )
}

value atg_from_file(const char * filename, int shared, value size, int options_kind, int options_device) {
  CAMLparam1(size);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::from_file(std::string(filename), shared != 0, optional_int_from_ocaml(size), at::device(device_of_int(options_device)).dtype(at::ScalarType(options_kind)))));
  )
}

value atg_from_file_out(value out, const char * filename, int shared, value size) {
  CAMLparam2(out, size);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::from_file_out(out_local, std::string(filename), shared != 0, optional_int_from_ocaml(size))));
  )
}

value atg_full(value size, value fill_value, int options_kind, int options_device) {
  CAMLparam2(size, fill_value);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::full(vec_of_ocaml_int_list(size), *scalar_from_ocaml_noalloc(fill_value), at::device(device_of_int(options_device)).dtype(at::ScalarType(options_kind)))));
  )
}

value atg_full_like(value self, value fill_value) {
  CAMLparam2(self, fill_value);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::full_like(rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(fill_value))));
  )
}

value atg_full_like_out(value out, value self, value fill_value) {
  CAMLparam3(out, self, fill_value);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::full_like_out(out_local, rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(fill_value))));
  )
}

value atg_full_out(value out, value size, value fill_value) {
  CAMLparam3(out, size, fill_value);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::full_out(out_local, vec_of_ocaml_int_list(size), *scalar_from_ocaml_noalloc(fill_value))));
  )
}

value atg_fused_moving_avg_obs_fake_quant(value self, value observer_on, value fake_quant_on, value running_min, value running_max, value scale, value zero_point, double averaging_const, int64_t quant_min, int64_t quant_max, int64_t ch_axis, int per_row_fake_quant, int symmetric_quant) {
  CAMLparam5(self, observer_on, fake_quant_on, running_min, running_max);
  CAMLxparam2(scale, zero_point);
  PROTECT(
    torch::Tensor running_min_local = rc_tensor_from_ocaml(running_min);
    torch::Tensor running_max_local = rc_tensor_from_ocaml(running_max);
    torch::Tensor scale_local = rc_tensor_from_ocaml(scale);
    torch::Tensor zero_point_local = rc_tensor_from_ocaml(zero_point);
    CAMLreturn(rc_tensor_to_ocaml(torch::fused_moving_avg_obs_fake_quant(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(observer_on), rc_tensor_from_ocaml(fake_quant_on), running_min_local, running_max_local, scale_local, zero_point_local, averaging_const, quant_min, quant_max, ch_axis, per_row_fake_quant != 0, symmetric_quant != 0)));
  )
}

value atg_gather(value self, int64_t dim, value index, int sparse_grad) {
  CAMLparam2(self, index);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::gather(rc_tensor_from_ocaml(self), dim, rc_tensor_from_ocaml(index), sparse_grad != 0)));
  )
}

value atg_gather_backward(value grad, value self, int64_t dim, value index, int sparse_grad) {
  CAMLparam3(grad, self, index);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::gather_backward(rc_tensor_from_ocaml(grad), rc_tensor_from_ocaml(self), dim, rc_tensor_from_ocaml(index), sparse_grad != 0)));
  )
}

value atg_gather_out(value out, value self, int64_t dim, value index, int sparse_grad) {
  CAMLparam3(out, self, index);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::gather_out(out_local, rc_tensor_from_ocaml(self), dim, rc_tensor_from_ocaml(index), sparse_grad != 0)));
  )
}

value atg_gcd(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::gcd(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_gcd_(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::gcd_(self_local, rc_tensor_from_ocaml(other))));
  )
}

value atg_gcd_out(value out, value self, value other) {
  CAMLparam3(out, self, other);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::gcd_out(out_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_ge(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::ge(rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(other))));
  )
}

value atg_ge_(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.ge_(*scalar_from_ocaml_noalloc(other))));
  )
}

value atg_ge_scalar_out(value out, value self, value other) {
  CAMLparam3(out, self, other);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::ge_out(out_local, rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(other))));
  )
}

value atg_ge_tensor(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::ge(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_ge_tensor_(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.ge_(rc_tensor_from_ocaml(other))));
  )
}

value atg_ge_tensor_out(value out, value self, value other) {
  CAMLparam3(out, self, other);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::ge_out(out_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_gelu(value self, const char * approximate) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::gelu(rc_tensor_from_ocaml(self), std::string(approximate))));
  )
}

value atg_gelu_(value self, const char * approximate) {
  CAMLparam1(self);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::gelu_(self_local, std::string(approximate))));
  )
}

value atg_gelu_backward(value grad_output, value self, const char * approximate) {
  CAMLparam2(grad_output, self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::gelu_backward(rc_tensor_from_ocaml(grad_output), rc_tensor_from_ocaml(self), std::string(approximate))));
  )
}

value atg_gelu_backward_grad_input(value grad_input, value grad_output, value self, const char * approximate) {
  CAMLparam3(grad_input, grad_output, self);
  PROTECT(
    torch::Tensor grad_input_local = rc_tensor_from_ocaml(grad_input);
    CAMLreturn(rc_tensor_to_ocaml(torch::gelu_backward_out(grad_input_local, rc_tensor_from_ocaml(grad_output), rc_tensor_from_ocaml(self), std::string(approximate))));
  )
}

value atg_gelu_out(value out, value self, const char * approximate) {
  CAMLparam2(out, self);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::gelu_out(out_local, rc_tensor_from_ocaml(self), std::string(approximate))));
  )
}

value atg_geometric(value self, double p) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::geometric(rc_tensor_from_ocaml(self), p)));
  )
}

value atg_geometric_(value self, double p) {
  CAMLparam1(self);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.geometric_(p)));
  )
}

value atg_geometric_out(value out, value self, double p) {
  CAMLparam2(out, self);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::geometric_out(out_local, rc_tensor_from_ocaml(self), p)));
  )
}

value atg_geqrf(value self) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensors_to_ocaml_tuple(torch::geqrf(rc_tensor_from_ocaml(self))));
  )
}

value atg_geqrf_a(value a, value tau, value self) {
  CAMLparam3(a, tau, self);
  PROTECT(
    torch::Tensor a_local = rc_tensor_from_ocaml(a);
    torch::Tensor tau_local = rc_tensor_from_ocaml(tau);
    CAMLreturn(rc_tensors_to_ocaml_tuple(torch::geqrf_out(a_local, tau_local, rc_tensor_from_ocaml(self))));
  )
}

value atg_ger(value self, value vec2) {
  CAMLparam2(self, vec2);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::ger(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(vec2))));
  )
}

value atg_ger_out(value out, value self, value vec2) {
  CAMLparam3(out, self, vec2);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::ger_out(out_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(vec2))));
  )
}

value atg_glu(value self, int64_t dim) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::glu(rc_tensor_from_ocaml(self), dim)));
  )
}

value atg_glu_backward(value grad_output, value self, int64_t dim) {
  CAMLparam2(grad_output, self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::glu_backward(rc_tensor_from_ocaml(grad_output), rc_tensor_from_ocaml(self), dim)));
  )
}

value atg_glu_backward_grad_input(value grad_input, value grad_output, value self, int64_t dim) {
  CAMLparam3(grad_input, grad_output, self);
  PROTECT(
    torch::Tensor grad_input_local = rc_tensor_from_ocaml(grad_input);
    CAMLreturn(rc_tensor_to_ocaml(torch::glu_backward_out(grad_input_local, rc_tensor_from_ocaml(grad_output), rc_tensor_from_ocaml(self), dim)));
  )
}

value atg_glu_backward_jvp(value grad_x, value grad_glu, value x, value dgrad_glu, value dx, int64_t dim) {
  CAMLparam5(grad_x, grad_glu, x, dgrad_glu, dx);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::glu_backward_jvp(rc_tensor_from_ocaml(grad_x), rc_tensor_from_ocaml(grad_glu), rc_tensor_from_ocaml(x), rc_tensor_from_ocaml(dgrad_glu), rc_tensor_from_ocaml(dx), dim)));
  )
}

value atg_glu_backward_jvp_out(value out, value grad_x, value grad_glu, value x, value dgrad_glu, value dx, int64_t dim) {
  CAMLparam5(out, grad_x, grad_glu, x, dgrad_glu);
  CAMLxparam1(dx);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::glu_backward_jvp_out(out_local, rc_tensor_from_ocaml(grad_x), rc_tensor_from_ocaml(grad_glu), rc_tensor_from_ocaml(x), rc_tensor_from_ocaml(dgrad_glu), rc_tensor_from_ocaml(dx), dim)));
  )
}

value atg_glu_jvp(value glu, value x, value dx, int64_t dim) {
  CAMLparam3(glu, x, dx);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::glu_jvp(rc_tensor_from_ocaml(glu), rc_tensor_from_ocaml(x), rc_tensor_from_ocaml(dx), dim)));
  )
}

value atg_glu_jvp_out(value out, value glu, value x, value dx, int64_t dim) {
  CAMLparam4(out, glu, x, dx);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::glu_jvp_out(out_local, rc_tensor_from_ocaml(glu), rc_tensor_from_ocaml(x), rc_tensor_from_ocaml(dx), dim)));
  )
}

value atg_glu_out(value out, value self, int64_t dim) {
  CAMLparam2(out, self);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::glu_out(out_local, rc_tensor_from_ocaml(self), dim)));
  )
}

value atg_grad(value self) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(rc_tensor_from_ocaml(self).grad()));
  )
}

value atg_greater(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::greater(rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(other))));
  )
}

value atg_greater_(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.greater_(*scalar_from_ocaml_noalloc(other))));
  )
}

value atg_greater_equal(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::greater_equal(rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(other))));
  )
}

value atg_greater_equal_(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.greater_equal_(*scalar_from_ocaml_noalloc(other))));
  )
}

value atg_greater_equal_scalar_out(value out, value self, value other) {
  CAMLparam3(out, self, other);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::greater_equal_out(out_local, rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(other))));
  )
}

value atg_greater_equal_tensor(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::greater_equal(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_greater_equal_tensor_(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.greater_equal_(rc_tensor_from_ocaml(other))));
  )
}

value atg_greater_equal_tensor_out(value out, value self, value other) {
  CAMLparam3(out, self, other);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::greater_equal_out(out_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_greater_scalar_out(value out, value self, value other) {
  CAMLparam3(out, self, other);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::greater_out(out_local, rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(other))));
  )
}

value atg_greater_tensor(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::greater(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_greater_tensor_(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.greater_(rc_tensor_from_ocaml(other))));
  )
}

value atg_greater_tensor_out(value out, value self, value other) {
  CAMLparam3(out, self, other);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::greater_out(out_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_grid_sampler(value input, value grid, int64_t interpolation_mode, int64_t padding_mode, int align_corners) {
  CAMLparam2(input, grid);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::grid_sampler(rc_tensor_from_ocaml(input), rc_tensor_from_ocaml(grid), interpolation_mode, padding_mode, align_corners != 0)));
  )
}

value atg_grid_sampler_2d(value input, value grid, int64_t interpolation_mode, int64_t padding_mode, int align_corners) {
  CAMLparam2(input, grid);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::grid_sampler_2d(rc_tensor_from_ocaml(input), rc_tensor_from_ocaml(grid), interpolation_mode, padding_mode, align_corners != 0)));
  )
}

value atg_grid_sampler_2d_out(value out, value input, value grid, int64_t interpolation_mode, int64_t padding_mode, int align_corners) {
  CAMLparam3(out, input, grid);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::grid_sampler_2d_out(out_local, rc_tensor_from_ocaml(input), rc_tensor_from_ocaml(grid), interpolation_mode, padding_mode, align_corners != 0)));
  )
}

value atg_grid_sampler_3d(value input, value grid, int64_t interpolation_mode, int64_t padding_mode, int align_corners) {
  CAMLparam2(input, grid);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::grid_sampler_3d(rc_tensor_from_ocaml(input), rc_tensor_from_ocaml(grid), interpolation_mode, padding_mode, align_corners != 0)));
  )
}

value atg_grid_sampler_3d_out(value out, value input, value grid, int64_t interpolation_mode, int64_t padding_mode, int align_corners) {
  CAMLparam3(out, input, grid);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::grid_sampler_3d_out(out_local, rc_tensor_from_ocaml(input), rc_tensor_from_ocaml(grid), interpolation_mode, padding_mode, align_corners != 0)));
  )
}

value atg_group_norm(value input, int64_t num_groups, value weight, value bias, double eps, int cudnn_enabled) {
  CAMLparam3(input, weight, bias);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::group_norm(rc_tensor_from_ocaml(input), num_groups, tensor_option_from_ocaml(weight), tensor_option_from_ocaml(bias), eps, cudnn_enabled != 0)));
  )
}

value atg_gru(value input, value hx, value params, int has_biases, int64_t num_layers, double dropout, int train, int bidirectional, int batch_first) {
  CAMLparam3(input, hx, params);
  PROTECT(
    CAMLreturn(rc_tensors_to_ocaml_tuple(torch::gru(rc_tensor_from_ocaml(input), rc_tensor_from_ocaml(hx), of_ocaml_tensor_list(params), has_biases != 0, num_layers, dropout, train != 0, bidirectional != 0, batch_first != 0)));
  )
}

value atg_gru_cell(value input, value hx, value w_ih, value w_hh, value b_ih, value b_hh) {
  CAMLparam5(input, hx, w_ih, w_hh, b_ih);
  CAMLxparam1(b_hh);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::gru_cell(rc_tensor_from_ocaml(input), rc_tensor_from_ocaml(hx), rc_tensor_from_ocaml(w_ih), rc_tensor_from_ocaml(w_hh), tensor_option_from_ocaml(b_ih), tensor_option_from_ocaml(b_hh))));
  )
}

value atg_gru_data(value data, value batch_sizes, value hx, value params, int has_biases, int64_t num_layers, double dropout, int train, int bidirectional) {
  CAMLparam4(data, batch_sizes, hx, params);
  PROTECT(
    CAMLreturn(rc_tensors_to_ocaml_tuple(torch::gru(rc_tensor_from_ocaml(data), rc_tensor_from_ocaml(batch_sizes), rc_tensor_from_ocaml(hx), of_ocaml_tensor_list(params), has_biases != 0, num_layers, dropout, train != 0, bidirectional != 0)));
  )
}

value atg_gt(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::gt(rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(other))));
  )
}

value atg_gt_(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.gt_(*scalar_from_ocaml_noalloc(other))));
  )
}

value atg_gt_scalar_out(value out, value self, value other) {
  CAMLparam3(out, self, other);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::gt_out(out_local, rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(other))));
  )
}

value atg_gt_tensor(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::gt(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_gt_tensor_(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.gt_(rc_tensor_from_ocaml(other))));
  )
}

value atg_gt_tensor_out(value out, value self, value other) {
  CAMLparam3(out, self, other);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::gt_out(out_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_hamming_window(int64_t window_length, int options_kind, int options_device) {
  CAMLparam0();
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::hamming_window(window_length, at::device(device_of_int(options_device)).dtype(at::ScalarType(options_kind)))));
  )
}

value atg_hamming_window_out(value out, int64_t window_length) {
  CAMLparam1(out);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::hamming_window_out(out_local, window_length)));
  )
}

value atg_hamming_window_periodic(int64_t window_length, int periodic, int options_kind, int options_device) {
  CAMLparam0();
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::hamming_window(window_length, periodic != 0, at::device(device_of_int(options_device)).dtype(at::ScalarType(options_kind)))));
  )
}

value atg_hamming_window_periodic_alpha(int64_t window_length, int periodic, double alpha, int options_kind, int options_device) {
  CAMLparam0();
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::hamming_window(window_length, periodic != 0, alpha, at::device(device_of_int(options_device)).dtype(at::ScalarType(options_kind)))));
  )
}

value atg_hamming_window_periodic_alpha_beta(int64_t window_length, int periodic, double alpha, double beta, int options_kind, int options_device) {
  CAMLparam0();
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::hamming_window(window_length, periodic != 0, alpha, beta, at::device(device_of_int(options_device)).dtype(at::ScalarType(options_kind)))));
  )
}

value atg_hamming_window_periodic_alpha_beta_out(value out, int64_t window_length, int periodic, double alpha, double beta) {
  CAMLparam1(out);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::hamming_window_out(out_local, window_length, periodic != 0, alpha, beta)));
  )
}

value atg_hamming_window_periodic_alpha_out(value out, int64_t window_length, int periodic, double alpha) {
  CAMLparam1(out);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::hamming_window_out(out_local, window_length, periodic != 0, alpha)));
  )
}

value atg_hamming_window_periodic_out(value out, int64_t window_length, int periodic) {
  CAMLparam1(out);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::hamming_window_out(out_local, window_length, periodic != 0)));
  )
}

value atg_hann_window(int64_t window_length, int options_kind, int options_device) {
  CAMLparam0();
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::hann_window(window_length, at::device(device_of_int(options_device)).dtype(at::ScalarType(options_kind)))));
  )
}

value atg_hann_window_out(value out, int64_t window_length) {
  CAMLparam1(out);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::hann_window_out(out_local, window_length)));
  )
}

value atg_hann_window_periodic(int64_t window_length, int periodic, int options_kind, int options_device) {
  CAMLparam0();
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::hann_window(window_length, periodic != 0, at::device(device_of_int(options_device)).dtype(at::ScalarType(options_kind)))));
  )
}

value atg_hann_window_periodic_out(value out, int64_t window_length, int periodic) {
  CAMLparam1(out);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::hann_window_out(out_local, window_length, periodic != 0)));
  )
}

value atg_hardshrink(value self, value lambd) {
  CAMLparam2(self, lambd);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::hardshrink(rc_tensor_from_ocaml(self), scalar_option_from_ocaml(lambd).value_or(0.5) )));
  )
}

value atg_hardshrink_backward(value grad_out, value self, value lambd) {
  CAMLparam3(grad_out, self, lambd);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::hardshrink_backward(rc_tensor_from_ocaml(grad_out), rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(lambd))));
  )
}

value atg_hardshrink_backward_grad_input(value grad_input, value grad_out, value self, value lambd) {
  CAMLparam4(grad_input, grad_out, self, lambd);
  PROTECT(
    torch::Tensor grad_input_local = rc_tensor_from_ocaml(grad_input);
    CAMLreturn(rc_tensor_to_ocaml(torch::hardshrink_backward_out(grad_input_local, rc_tensor_from_ocaml(grad_out), rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(lambd))));
  )
}

value atg_hardshrink_out(value out, value self, value lambd) {
  CAMLparam3(out, self, lambd);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::hardshrink_out(out_local, rc_tensor_from_ocaml(self), scalar_option_from_ocaml(lambd).value_or(0.5) )));
  )
}

value atg_hardsigmoid(value self) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::hardsigmoid(rc_tensor_from_ocaml(self))));
  )
}

value atg_hardsigmoid_(value self) {
  CAMLparam1(self);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::hardsigmoid_(self_local)));
  )
}

value atg_hardsigmoid_backward(value grad_output, value self) {
  CAMLparam2(grad_output, self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::hardsigmoid_backward(rc_tensor_from_ocaml(grad_output), rc_tensor_from_ocaml(self))));
  )
}

value atg_hardsigmoid_backward_grad_input(value grad_input, value grad_output, value self) {
  CAMLparam3(grad_input, grad_output, self);
  PROTECT(
    torch::Tensor grad_input_local = rc_tensor_from_ocaml(grad_input);
    CAMLreturn(rc_tensor_to_ocaml(torch::hardsigmoid_backward_out(grad_input_local, rc_tensor_from_ocaml(grad_output), rc_tensor_from_ocaml(self))));
  )
}

value atg_hardsigmoid_out(value out, value self) {
  CAMLparam2(out, self);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::hardsigmoid_out(out_local, rc_tensor_from_ocaml(self))));
  )
}

value atg_hardswish(value self) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::hardswish(rc_tensor_from_ocaml(self))));
  )
}

value atg_hardswish_(value self) {
  CAMLparam1(self);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::hardswish_(self_local)));
  )
}

value atg_hardswish_backward(value grad_output, value self) {
  CAMLparam2(grad_output, self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::hardswish_backward(rc_tensor_from_ocaml(grad_output), rc_tensor_from_ocaml(self))));
  )
}

value atg_hardswish_backward_out(value out, value grad_output, value self) {
  CAMLparam3(out, grad_output, self);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::hardswish_backward_out(out_local, rc_tensor_from_ocaml(grad_output), rc_tensor_from_ocaml(self))));
  )
}

value atg_hardswish_out(value out, value self) {
  CAMLparam2(out, self);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::hardswish_out(out_local, rc_tensor_from_ocaml(self))));
  )
}

value atg_hardtanh(value self, value min_val, value max_val) {
  CAMLparam3(self, min_val, max_val);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::hardtanh(rc_tensor_from_ocaml(self), scalar_option_from_ocaml(min_val).value_or(-1) , scalar_option_from_ocaml(max_val).value_or(1) )));
  )
}

value atg_hardtanh_(value self, value min_val, value max_val) {
  CAMLparam3(self, min_val, max_val);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::hardtanh_(self_local, scalar_option_from_ocaml(min_val).value_or(-1) , scalar_option_from_ocaml(max_val).value_or(1) )));
  )
}

value atg_hardtanh_backward(value grad_output, value self, value min_val, value max_val) {
  CAMLparam4(grad_output, self, min_val, max_val);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::hardtanh_backward(rc_tensor_from_ocaml(grad_output), rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(min_val), *scalar_from_ocaml_noalloc(max_val))));
  )
}

value atg_hardtanh_backward_grad_input(value grad_input, value grad_output, value self, value min_val, value max_val) {
  CAMLparam5(grad_input, grad_output, self, min_val, max_val);
  PROTECT(
    torch::Tensor grad_input_local = rc_tensor_from_ocaml(grad_input);
    CAMLreturn(rc_tensor_to_ocaml(torch::hardtanh_backward_out(grad_input_local, rc_tensor_from_ocaml(grad_output), rc_tensor_from_ocaml(self), *scalar_from_ocaml_noalloc(min_val), *scalar_from_ocaml_noalloc(max_val))));
  )
}

value atg_hardtanh_out(value out, value self, value min_val, value max_val) {
  CAMLparam4(out, self, min_val, max_val);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::hardtanh_out(out_local, rc_tensor_from_ocaml(self), scalar_option_from_ocaml(min_val).value_or(-1) , scalar_option_from_ocaml(max_val).value_or(1) )));
  )
}

value atg_heaviside(value self, value values) {
  CAMLparam2(self, values);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::heaviside(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(values))));
  )
}

value atg_heaviside_(value self, value values) {
  CAMLparam2(self, values);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.heaviside_(rc_tensor_from_ocaml(values))));
  )
}

value atg_heaviside_out(value out, value self, value values) {
  CAMLparam3(out, self, values);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::heaviside_out(out_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(values))));
  )
}

value atg_hinge_embedding_loss(value self, value target, double margin, int64_t reduction) {
  CAMLparam2(self, target);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::hinge_embedding_loss(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(target), margin, reduction)));
  )
}

value atg_histc(value self, int64_t bins, value min, value max) {
  CAMLparam3(self, min, max);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::histc(rc_tensor_from_ocaml(self), bins, scalar_option_from_ocaml(min).value_or(0) , scalar_option_from_ocaml(max).value_or(0) )));
  )
}

value atg_histc_out(value out, value self, int64_t bins, value min, value max) {
  CAMLparam4(out, self, min, max);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::histc_out(out_local, rc_tensor_from_ocaml(self), bins, scalar_option_from_ocaml(min).value_or(0) , scalar_option_from_ocaml(max).value_or(0) )));
  )
}

value atg_hsplit(value self, int64_t sections) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(to_ocaml_tensor_list(torch::hsplit(rc_tensor_from_ocaml(self), sections)));
  )
}

value atg_hsplit_array(value self, value indices) {
  CAMLparam2(self, indices);
  PROTECT(
    CAMLreturn(to_ocaml_tensor_list(torch::hsplit(rc_tensor_from_ocaml(self), vec_of_ocaml_int_list(indices))));
  )
}

value atg_hspmm(value mat1, value mat2) {
  CAMLparam2(mat1, mat2);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::hspmm(rc_tensor_from_ocaml(mat1), rc_tensor_from_ocaml(mat2))));
  )
}

value atg_hspmm_out(value out, value mat1, value mat2) {
  CAMLparam3(out, mat1, mat2);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::hspmm_out(out_local, rc_tensor_from_ocaml(mat1), rc_tensor_from_ocaml(mat2))));
  )
}

value atg_hstack(value tensors) {
  CAMLparam1(tensors);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::hstack(of_ocaml_tensor_list(tensors))));
  )
}

value atg_hstack_out(value out, value tensors) {
  CAMLparam2(out, tensors);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::hstack_out(out_local, of_ocaml_tensor_list(tensors))));
  )
}

value atg_huber_loss(value self, value target, int64_t reduction, double delta) {
  CAMLparam2(self, target);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::huber_loss(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(target), reduction, delta)));
  )
}

value atg_huber_loss_backward(value grad_output, value self, value target, int64_t reduction, double delta) {
  CAMLparam3(grad_output, self, target);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::huber_loss_backward(rc_tensor_from_ocaml(grad_output), rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(target), reduction, delta)));
  )
}

value atg_huber_loss_backward_out(value grad_input, value grad_output, value self, value target, int64_t reduction, double delta) {
  CAMLparam4(grad_input, grad_output, self, target);
  PROTECT(
    torch::Tensor grad_input_local = rc_tensor_from_ocaml(grad_input);
    CAMLreturn(rc_tensor_to_ocaml(torch::huber_loss_backward_out(grad_input_local, rc_tensor_from_ocaml(grad_output), rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(target), reduction, delta)));
  )
}

value atg_huber_loss_out(value out, value self, value target, int64_t reduction, double delta) {
  CAMLparam3(out, self, target);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::huber_loss_out(out_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(target), reduction, delta)));
  )
}

value atg_hypot(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::hypot(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_hypot_(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.hypot_(rc_tensor_from_ocaml(other))));
  )
}

value atg_hypot_out(value out, value self, value other) {
  CAMLparam3(out, self, other);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::hypot_out(out_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_i0(value self) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::i0(rc_tensor_from_ocaml(self))));
  )
}

value atg_i0_(value self) {
  CAMLparam1(self);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(torch::i0_(self_local)));
  )
}

value atg_i0_out(value out, value self) {
  CAMLparam2(out, self);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::i0_out(out_local, rc_tensor_from_ocaml(self))));
  )
}

value atg_igamma(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::igamma(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_igamma_(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.igamma_(rc_tensor_from_ocaml(other))));
  )
}

value atg_igamma_out(value out, value self, value other) {
  CAMLparam3(out, self, other);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::igamma_out(out_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_igammac(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::igammac(rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_igammac_(value self, value other) {
  CAMLparam2(self, other);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.igammac_(rc_tensor_from_ocaml(other))));
  )
}

value atg_igammac_out(value out, value self, value other) {
  CAMLparam3(out, self, other);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::igammac_out(out_local, rc_tensor_from_ocaml(self), rc_tensor_from_ocaml(other))));
  )
}

value atg_im2col(value self, value kernel_size, value dilation, value padding, value stride) {
  CAMLparam5(self, kernel_size, dilation, padding, stride);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::im2col(rc_tensor_from_ocaml(self), vec_of_ocaml_int_list(kernel_size), vec_of_ocaml_int_list(dilation), vec_of_ocaml_int_list(padding), vec_of_ocaml_int_list(stride))));
  )
}

value atg_im2col_out(value out, value self, value kernel_size, value dilation, value padding, value stride) {
  CAMLparam5(out, self, kernel_size, dilation, padding);
  CAMLxparam1(stride);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::im2col_out(out_local, rc_tensor_from_ocaml(self), vec_of_ocaml_int_list(kernel_size), vec_of_ocaml_int_list(dilation), vec_of_ocaml_int_list(padding), vec_of_ocaml_int_list(stride))));
  )
}

value atg_imag(value self) {
  CAMLparam1(self);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::imag(rc_tensor_from_ocaml(self))));
  )
}

value atg_index_add(value self, int64_t dim, value index, value source, value alpha) {
  CAMLparam4(self, index, source, alpha);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::index_add(rc_tensor_from_ocaml(self), dim, rc_tensor_from_ocaml(index), rc_tensor_from_ocaml(source), scalar_option_from_ocaml(alpha).value_or(1) )));
  )
}

value atg_index_add_(value self, int64_t dim, value index, value source, value alpha) {
  CAMLparam4(self, index, source, alpha);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.index_add_(dim, rc_tensor_from_ocaml(index), rc_tensor_from_ocaml(source), scalar_option_from_ocaml(alpha).value_or(1) )));
  )
}

value atg_index_add_out(value out, value self, int64_t dim, value index, value source, value alpha) {
  CAMLparam5(out, self, index, source, alpha);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::index_add_out(out_local, rc_tensor_from_ocaml(self), dim, rc_tensor_from_ocaml(index), rc_tensor_from_ocaml(source), scalar_option_from_ocaml(alpha).value_or(1) )));
  )
}

value atg_index_copy(value self, int64_t dim, value index, value source) {
  CAMLparam3(self, index, source);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::index_copy(rc_tensor_from_ocaml(self), dim, rc_tensor_from_ocaml(index), rc_tensor_from_ocaml(source))));
  )
}

value atg_index_copy_(value self, int64_t dim, value index, value source) {
  CAMLparam3(self, index, source);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.index_copy_(dim, rc_tensor_from_ocaml(index), rc_tensor_from_ocaml(source))));
  )
}

value atg_index_copy_out(value out, value self, int64_t dim, value index, value source) {
  CAMLparam4(out, self, index, source);
  PROTECT(
    torch::Tensor out_local = rc_tensor_from_ocaml(out);
    CAMLreturn(rc_tensor_to_ocaml(torch::index_copy_out(out_local, rc_tensor_from_ocaml(self), dim, rc_tensor_from_ocaml(index), rc_tensor_from_ocaml(source))));
  )
}

value atg_index_fill(value self, int64_t dim, value index, value value_) {
  CAMLparam3(self, index, value_);
  PROTECT(
    CAMLreturn(rc_tensor_to_ocaml(torch::index_fill(rc_tensor_from_ocaml(self), dim, rc_tensor_from_ocaml(index), *scalar_from_ocaml_noalloc(value_))));
  )
}

value atg_index_fill_(value self, int64_t dim, value index, value value_) {
  CAMLparam3(self, index, value_);
  PROTECT(
    torch::Tensor self_local = rc_tensor_from_ocaml(self);
    CAMLreturn(rc_tensor_to_ocaml(self_local.index_fill_(dim, rc_tensor_from_ocaml(index), *scalar_from_ocaml_noalloc(value_))));
  )
}

