(* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT BY HAND! *)

open Ctypes

module C0 (F : Cstubs.FOREIGN) = struct
  open F
  open Type_defs

  let stubs___and__ = foreign "atg___and__" (gc_tensor @-> scalar @-> returning raw_tensor)

  let stubs___and__tensor_ =
    foreign "atg___and__tensor_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs___iand__ =
    foreign "atg___iand__" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs___iand__tensor_ =
    foreign "atg___iand__tensor_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs___ilshift__ =
    foreign "atg___ilshift__" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs___ilshift__tensor_ =
    foreign "atg___ilshift__tensor_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs___ior__ = foreign "atg___ior__" (gc_tensor @-> scalar @-> returning raw_tensor)

  let stubs___ior__tensor_ =
    foreign "atg___ior__tensor_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs___irshift__ =
    foreign "atg___irshift__" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs___irshift__tensor_ =
    foreign "atg___irshift__tensor_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs___ixor__ =
    foreign "atg___ixor__" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs___ixor__tensor_ =
    foreign "atg___ixor__tensor_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs___lshift__ =
    foreign "atg___lshift__" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs___lshift__scalar_out_ =
    foreign
      "atg___lshift__scalar_out_"
      (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs___lshift__tensor_ =
    foreign "atg___lshift__tensor_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs___lshift__tensor_out_ =
    foreign
      "atg___lshift__tensor_out_"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs___or__ = foreign "atg___or__" (gc_tensor @-> scalar @-> returning raw_tensor)

  let stubs___or__tensor_ =
    foreign "atg___or__tensor_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs___rshift__ =
    foreign "atg___rshift__" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs___rshift__scalar_out_ =
    foreign
      "atg___rshift__scalar_out_"
      (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs___rshift__tensor_ =
    foreign "atg___rshift__tensor_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs___rshift__tensor_out_ =
    foreign
      "atg___rshift__tensor_out_"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs___xor__ = foreign "atg___xor__" (gc_tensor @-> scalar @-> returning raw_tensor)

  let stubs___xor__tensor_ =
    foreign "atg___xor__tensor_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__adaptive_avg_pool2d =
    foreign
      "atg__adaptive_avg_pool2d"
      (gc_tensor @-> ptr int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__adaptive_avg_pool2d_backward =
    foreign
      "atg__adaptive_avg_pool2d_backward"
      (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__adaptive_avg_pool2d_backward_out =
    foreign
      "atg__adaptive_avg_pool2d_backward_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__adaptive_avg_pool2d_out =
    foreign
      "atg__adaptive_avg_pool2d_out"
      (gc_tensor @-> gc_tensor @-> ptr int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__adaptive_avg_pool3d =
    foreign
      "atg__adaptive_avg_pool3d"
      (gc_tensor @-> ptr int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__adaptive_avg_pool3d_backward =
    foreign
      "atg__adaptive_avg_pool3d_backward"
      (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__adaptive_avg_pool3d_backward_out =
    foreign
      "atg__adaptive_avg_pool3d_backward_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__adaptive_avg_pool3d_out =
    foreign
      "atg__adaptive_avg_pool3d_out"
      (gc_tensor @-> gc_tensor @-> ptr int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__add_batch_dim =
    foreign
      "atg__add_batch_dim"
      (gc_tensor @-> int64_t @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__add_relu =
    foreign "atg__add_relu" (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs__add_relu_ =
    foreign "atg__add_relu_" (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs__add_relu_out =
    foreign
      "atg__add_relu_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs__add_relu_scalar =
    foreign
      "atg__add_relu_scalar"
      (gc_tensor @-> scalar @-> scalar @-> returning raw_tensor)
  ;;

  let stubs__add_relu_scalar_ =
    foreign
      "atg__add_relu_scalar_"
      (gc_tensor @-> scalar @-> scalar @-> returning raw_tensor)
  ;;

  let stubs__add_relu_scalar_out =
    foreign
      "atg__add_relu_scalar_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> scalar @-> returning raw_tensor)
  ;;

  let stubs__addmm_activation =
    foreign
      "atg__addmm_activation"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> scalar
       @-> scalar
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__addmm_activation_out =
    foreign
      "atg__addmm_activation_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> scalar
       @-> scalar
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__aminmax =
    foreign "atg__aminmax" (ptr raw_tensor @-> gc_tensor @-> returning void)
  ;;

  let stubs__aminmax_dim =
    foreign
      "atg__aminmax_dim"
      (ptr raw_tensor @-> gc_tensor @-> int64_t @-> int @-> returning void)
  ;;

  let stubs__aminmax_dim_out =
    foreign
      "atg__aminmax_dim_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int
       @-> returning void)
  ;;

  let stubs__aminmax_out =
    foreign
      "atg__aminmax_out"
      (ptr raw_tensor @-> gc_tensor @-> gc_tensor @-> gc_tensor @-> returning void)
  ;;

  let stubs__amp_update_scale =
    foreign
      "atg__amp_update_scale"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> double
       @-> int64_t
       @-> returning void)
  ;;

  let stubs__amp_update_scale_ =
    foreign
      "atg__amp_update_scale_"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> double
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs__amp_update_scale_out =
    foreign
      "atg__amp_update_scale_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> double
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs__assert_scalar =
    foreign "atg__assert_scalar" (scalar @-> string @-> returning void)
  ;;

  let stubs__assert_tensor_metadata =
    foreign
      "atg__assert_tensor_metadata"
      (gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs__autocast_to_full_precision =
    foreign
      "atg__autocast_to_full_precision"
      (gc_tensor @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs__autocast_to_reduced_precision =
    foreign
      "atg__autocast_to_reduced_precision"
      (gc_tensor @-> int @-> int @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs__batch_norm_no_update =
    foreign
      "atg__batch_norm_no_update"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> double
       @-> returning void)
  ;;

  let stubs__batch_norm_no_update_out =
    foreign
      "atg__batch_norm_no_update_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> double
       @-> returning void)
  ;;

  let stubs__batch_norm_with_update =
    foreign
      "atg__batch_norm_with_update"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> double
       @-> returning void)
  ;;

  let stubs__batch_norm_with_update_functional =
    foreign
      "atg__batch_norm_with_update_functional"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> double
       @-> returning void)
  ;;

  let stubs__batch_norm_with_update_out =
    foreign
      "atg__batch_norm_with_update_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> double
       @-> returning void)
  ;;

  let stubs__cast_byte =
    foreign "atg__cast_byte" (gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__cast_char =
    foreign "atg__cast_char" (gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__cast_double =
    foreign "atg__cast_double" (gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__cast_float =
    foreign "atg__cast_float" (gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__cast_half =
    foreign "atg__cast_half" (gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__cast_int =
    foreign "atg__cast_int" (gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__cast_long =
    foreign "atg__cast_long" (gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__cast_short =
    foreign "atg__cast_short" (gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__cdist_backward =
    foreign
      "atg__cdist_backward"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> gc_tensor
       @-> returning raw_tensor)
  ;;

  let stubs__cdist_backward_out =
    foreign
      "atg__cdist_backward_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> gc_tensor
       @-> returning raw_tensor)
  ;;

  let stubs__cholesky_solve_helper =
    foreign
      "atg__cholesky_solve_helper"
      (gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__cholesky_solve_helper_out =
    foreign
      "atg__cholesky_solve_helper_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__chunk_cat =
    foreign
      "atg__chunk_cat"
      (ptr gc_tensor @-> int @-> int64_t @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__chunk_cat_out =
    foreign
      "atg__chunk_cat_out"
      (gc_tensor
       @-> ptr gc_tensor
       @-> int
       @-> int64_t
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs__coalesce = foreign "atg__coalesce" (gc_tensor @-> returning raw_tensor)

  let stubs__coalesce_out =
    foreign "atg__coalesce_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__coalesced =
    foreign "atg__coalesced" (gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__coalesced_ =
    foreign "atg__coalesced_" (gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__coalesced_out =
    foreign "atg__coalesced_out" (gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__compute_linear_combination =
    foreign
      "atg__compute_linear_combination"
      (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__compute_linear_combination_out =
    foreign
      "atg__compute_linear_combination_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__conj = foreign "atg__conj" (gc_tensor @-> returning raw_tensor)
  let stubs__conj_copy = foreign "atg__conj_copy" (gc_tensor @-> returning raw_tensor)

  let stubs__conj_copy_out =
    foreign "atg__conj_copy_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__conj_physical =
    foreign "atg__conj_physical" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__conj_physical_out =
    foreign "atg__conj_physical_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__conv_depthwise2d =
    foreign
      "atg__conv_depthwise2d"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__conv_depthwise2d_out =
    foreign
      "atg__conv_depthwise2d_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__convert_indices_from_coo_to_csr =
    foreign
      "atg__convert_indices_from_coo_to_csr"
      (gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__convert_indices_from_coo_to_csr_out =
    foreign
      "atg__convert_indices_from_coo_to_csr_out"
      (gc_tensor @-> gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__convert_indices_from_csr_to_coo =
    foreign
      "atg__convert_indices_from_csr_to_coo"
      (gc_tensor @-> gc_tensor @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs__convert_indices_from_csr_to_coo_out =
    foreign
      "atg__convert_indices_from_csr_to_coo_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs__convert_weight_to_int4pack =
    foreign
      "atg__convert_weight_to_int4pack"
      (gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__convert_weight_to_int4pack_for_cpu =
    foreign
      "atg__convert_weight_to_int4pack_for_cpu"
      (gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__convolution =
    foreign
      "atg__convolution"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> int
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__convolution_deprecated =
    foreign
      "atg__convolution_deprecated"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__convolution_mode =
    foreign
      "atg__convolution_mode"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> string
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs__convolution_out =
    foreign
      "atg__convolution_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> int
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__copy_from =
    foreign "atg__copy_from" (gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__copy_from_and_resize =
    foreign "atg__copy_from_and_resize" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__copy_from_and_resize_out =
    foreign
      "atg__copy_from_and_resize_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__copy_from_out =
    foreign
      "atg__copy_from_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__cslt_compress =
    foreign "atg__cslt_compress" (gc_tensor @-> returning raw_tensor)
  ;;
end

module C1 (F : Cstubs.FOREIGN) = struct
  open F
  open Type_defs

  let stubs__cslt_sparse_mm =
    foreign
      "atg__cslt_sparse_mm"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> int
       @-> int64_t
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__cslt_sparse_mm_search =
    foreign
      "atg__cslt_sparse_mm_search"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> int
       @-> returning int64_t)
  ;;

  let stubs__ctc_loss =
    foreign
      "atg__ctc_loss"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> returning void)
  ;;

  let stubs__ctc_loss_backward =
    foreign
      "atg__ctc_loss_backward"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__ctc_loss_backward_out =
    foreign
      "atg__ctc_loss_backward_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__ctc_loss_backward_tensor =
    foreign
      "atg__ctc_loss_backward_tensor"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__ctc_loss_out =
    foreign
      "atg__ctc_loss_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> returning void)
  ;;

  let stubs__ctc_loss_tensor =
    foreign
      "atg__ctc_loss_tensor"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int
       @-> returning void)
  ;;

  let stubs__ctc_loss_tensor_out =
    foreign
      "atg__ctc_loss_tensor_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int
       @-> returning void)
  ;;

  let stubs__cudnn_ctc_loss =
    foreign
      "atg__cudnn_ctc_loss"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs__cudnn_ctc_loss_out =
    foreign
      "atg__cudnn_ctc_loss_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs__cudnn_ctc_loss_tensor =
    foreign
      "atg__cudnn_ctc_loss_tensor"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs__cudnn_init_dropout_state =
    foreign
      "atg__cudnn_init_dropout_state"
      (double @-> int @-> int64_t @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs__cudnn_init_dropout_state_out =
    foreign
      "atg__cudnn_init_dropout_state_out"
      (gc_tensor @-> double @-> int @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__cudnn_rnn =
    foreign
      "atg__cudnn_rnn"
      (ptr raw_tensor
       @-> gc_tensor
       @-> ptr gc_tensor
       @-> int
       @-> int64_t
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> int
       @-> double
       @-> int
       @-> int
       @-> ptr int64_t
       @-> int
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs__cudnn_rnn_flatten_weight =
    foreign
      "atg__cudnn_rnn_flatten_weight"
      (ptr gc_tensor
       @-> int
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__cudnn_rnn_flatten_weight_out =
    foreign
      "atg__cudnn_rnn_flatten_weight_out"
      (gc_tensor
       @-> ptr gc_tensor
       @-> int
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__cudnn_rnn_out =
    foreign
      "atg__cudnn_rnn_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr gc_tensor
       @-> int
       @-> int64_t
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> int
       @-> double
       @-> int
       @-> int
       @-> ptr int64_t
       @-> int
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs__debug_has_internal_overlap =
    foreign "atg__debug_has_internal_overlap" (gc_tensor @-> returning int64_t)
  ;;

  let stubs__dim_arange =
    foreign "atg__dim_arange" (gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__dimi = foreign "atg__dimi" (gc_tensor @-> returning int64_t)
  let stubs__dimv = foreign "atg__dimv" (gc_tensor @-> returning int64_t)

  let stubs__dirichlet_grad =
    foreign
      "atg__dirichlet_grad"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__dirichlet_grad_out =
    foreign
      "atg__dirichlet_grad_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__dyn_quant_matmul_4bit =
    foreign
      "atg__dyn_quant_matmul_4bit"
      (gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs__dyn_quant_pack_4bit_weight =
    foreign
      "atg__dyn_quant_pack_4bit_weight"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs__efficient_attention_backward =
    foreign
      "atg__efficient_attention_backward"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> gc_tensor
       @-> double
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int
       @-> double
       @-> int
       @-> int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs__efficientzerotensor =
    foreign
      "atg__efficientzerotensor"
      (ptr int64_t @-> int @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs__efficientzerotensor_out =
    foreign
      "atg__efficientzerotensor_out"
      (gc_tensor @-> ptr int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__embedding_bag =
    foreign
      "atg__embedding_bag"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> int64_t
       @-> int
       @-> gc_tensor
       @-> int
       @-> int64_t
       @-> returning void)
  ;;

  let stubs__embedding_bag_backward =
    foreign
      "atg__embedding_bag_backward"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> gc_tensor
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs__embedding_bag_dense_backward =
    foreign
      "atg__embedding_bag_dense_backward"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int
       @-> int64_t
       @-> gc_tensor
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs__embedding_bag_dense_backward_out =
    foreign
      "atg__embedding_bag_dense_backward_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int
       @-> int64_t
       @-> gc_tensor
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs__embedding_bag_forward_only =
    foreign
      "atg__embedding_bag_forward_only"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> int64_t
       @-> int
       @-> gc_tensor
       @-> int
       @-> int64_t
       @-> returning void)
  ;;

  let stubs__embedding_bag_forward_only_out =
    foreign
      "atg__embedding_bag_forward_only_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> int64_t
       @-> int
       @-> gc_tensor
       @-> int
       @-> int64_t
       @-> returning void)
  ;;

  let stubs__embedding_bag_out =
    foreign
      "atg__embedding_bag_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> int64_t
       @-> int
       @-> gc_tensor
       @-> int
       @-> int64_t
       @-> returning void)
  ;;

  let stubs__embedding_bag_per_sample_weights_backward =
    foreign
      "atg__embedding_bag_per_sample_weights_backward"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs__embedding_bag_per_sample_weights_backward_out =
    foreign
      "atg__embedding_bag_per_sample_weights_backward_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs__embedding_bag_sparse_backward =
    foreign
      "atg__embedding_bag_sparse_backward"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int
       @-> int64_t
       @-> gc_tensor
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs__empty_affine_quantized =
    foreign
      "atg__empty_affine_quantized"
      (ptr int64_t @-> int @-> int @-> int @-> double @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__empty_affine_quantized_out =
    foreign
      "atg__empty_affine_quantized_out"
      (gc_tensor @-> ptr int64_t @-> int @-> double @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__empty_per_channel_affine_quantized =
    foreign
      "atg__empty_per_channel_affine_quantized"
      (ptr int64_t
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__empty_per_channel_affine_quantized_out =
    foreign
      "atg__empty_per_channel_affine_quantized_out"
      (gc_tensor
       @-> ptr int64_t
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs__euclidean_dist =
    foreign "atg__euclidean_dist" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__euclidean_dist_out =
    foreign
      "atg__euclidean_dist_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__fake_quantize_learnable_per_channel_affine =
    foreign
      "atg__fake_quantize_learnable_per_channel_affine"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> double
       @-> returning raw_tensor)
  ;;

  let stubs__fake_quantize_learnable_per_channel_affine_backward =
    foreign
      "atg__fake_quantize_learnable_per_channel_affine_backward"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> double
       @-> returning void)
  ;;

  let stubs__fake_quantize_learnable_per_channel_affine_out =
    foreign
      "atg__fake_quantize_learnable_per_channel_affine_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> double
       @-> returning raw_tensor)
  ;;

  let stubs__fake_quantize_learnable_per_tensor_affine =
    foreign
      "atg__fake_quantize_learnable_per_tensor_affine"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> double
       @-> returning raw_tensor)
  ;;

  let stubs__fake_quantize_learnable_per_tensor_affine_backward =
    foreign
      "atg__fake_quantize_learnable_per_tensor_affine_backward"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> double
       @-> returning void)
  ;;

  let stubs__fake_quantize_learnable_per_tensor_affine_out =
    foreign
      "atg__fake_quantize_learnable_per_tensor_affine_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> double
       @-> returning raw_tensor)
  ;;

  let stubs__fake_quantize_per_tensor_affine_cachemask_tensor_qparams =
    foreign
      "atg__fake_quantize_per_tensor_affine_cachemask_tensor_qparams"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> returning void)
  ;;

  let stubs__fake_quantize_per_tensor_affine_cachemask_tensor_qparams_out =
    foreign
      "atg__fake_quantize_per_tensor_affine_cachemask_tensor_qparams_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> returning void)
  ;;

  let stubs__fft_c2c =
    foreign
      "atg__fft_c2c"
      (gc_tensor @-> ptr int64_t @-> int @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__fft_c2c_out =
    foreign
      "atg__fft_c2c_out"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__fft_c2r =
    foreign
      "atg__fft_c2r"
      (gc_tensor @-> ptr int64_t @-> int @-> int64_t @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__fft_c2r_out =
    foreign
      "atg__fft_c2r_out"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs__fft_r2c =
    foreign
      "atg__fft_r2c"
      (gc_tensor @-> ptr int64_t @-> int @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__fft_r2c_out =
    foreign
      "atg__fft_r2c_out"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__fill_mem_eff_dropout_mask_ =
    foreign
      "atg__fill_mem_eff_dropout_mask_"
      (gc_tensor @-> double @-> int64_t @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__flash_attention_backward =
    foreign
      "atg__flash_attention_backward"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> double
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> int
       @-> int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> returning void)
  ;;

  let stubs__foobar =
    foreign "atg__foobar" (gc_tensor @-> int @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs__foobar_out =
    foreign
      "atg__foobar_out"
      (gc_tensor @-> gc_tensor @-> int @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs__functional_assert_async =
    foreign
      "atg__functional_assert_async"
      (gc_tensor @-> string @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__functional_assert_scalar =
    foreign
      "atg__functional_assert_scalar"
      (scalar @-> string @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__functional_sym_constrain_range =
    foreign
      "atg__functional_sym_constrain_range"
      (scalar
       @-> int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> gc_tensor
       @-> returning raw_tensor)
  ;;

  let stubs__functional_sym_constrain_range_for_size =
    foreign
      "atg__functional_sym_constrain_range_for_size"
      (scalar
       @-> int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> gc_tensor
       @-> returning raw_tensor)
  ;;

  let stubs__fused_adagrad =
    foreign
      "atg__fused_adagrad"
      (ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> double
       @-> double
       @-> double
       @-> double
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs__fused_adagrad_ =
    foreign
      "atg__fused_adagrad_"
      (ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> double
       @-> double
       @-> double
       @-> double
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs__fused_adam =
    foreign
      "atg__fused_adam"
      (ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> double
       @-> double
       @-> double
       @-> double
       @-> double
       @-> int
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs__fused_adam_ =
    foreign
      "atg__fused_adam_"
      (ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> double
       @-> double
       @-> double
       @-> double
       @-> double
       @-> int
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs__fused_adam_tensor_lr_ =
    foreign
      "atg__fused_adam_tensor_lr_"
      (ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> gc_tensor
       @-> double
       @-> double
       @-> double
       @-> double
       @-> int
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs__fused_adam_tensor_lr_out =
    foreign
      "atg__fused_adam_tensor_lr_out"
      (ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> gc_tensor
       @-> double
       @-> double
       @-> double
       @-> double
       @-> int
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs__fused_adamw =
    foreign
      "atg__fused_adamw"
      (ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> double
       @-> double
       @-> double
       @-> double
       @-> double
       @-> int
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs__fused_adamw_ =
    foreign
      "atg__fused_adamw_"
      (ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> double
       @-> double
       @-> double
       @-> double
       @-> double
       @-> int
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs__fused_adamw_tensor_lr_ =
    foreign
      "atg__fused_adamw_tensor_lr_"
      (ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> gc_tensor
       @-> double
       @-> double
       @-> double
       @-> double
       @-> int
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs__fused_adamw_tensor_lr_out =
    foreign
      "atg__fused_adamw_tensor_lr_out"
      (ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> gc_tensor
       @-> double
       @-> double
       @-> double
       @-> double
       @-> int
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs__fused_dropout =
    foreign
      "atg__fused_dropout"
      (ptr raw_tensor @-> gc_tensor @-> double @-> returning void)
  ;;

  let stubs__fused_dropout_out =
    foreign
      "atg__fused_dropout_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> returning void)
  ;;

  let stubs__fused_moving_avg_obs_fq_helper =
    foreign
      "atg__fused_moving_avg_obs_fq_helper"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs__fused_moving_avg_obs_fq_helper_functional =
    foreign
      "atg__fused_moving_avg_obs_fq_helper_functional"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs__fused_moving_avg_obs_fq_helper_out =
    foreign
      "atg__fused_moving_avg_obs_fq_helper_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs__fused_sdp_choice =
    foreign
      "atg__fused_sdp_choice"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> int
       @-> double
       @-> int
       @-> int
       @-> returning int64_t)
  ;;

  let stubs__fused_sgd =
    foreign
      "atg__fused_sgd"
      (ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> double
       @-> double
       @-> double
       @-> double
       @-> int
       @-> int
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs__fused_sgd_ =
    foreign
      "atg__fused_sgd_"
      (ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> double
       @-> double
       @-> double
       @-> double
       @-> int
       @-> int
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs__fused_sgd_tensor_lr_ =
    foreign
      "atg__fused_sgd_tensor_lr_"
      (ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> double
       @-> double
       @-> gc_tensor
       @-> double
       @-> int
       @-> int
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs__fused_sgd_tensor_lr_out =
    foreign
      "atg__fused_sgd_tensor_lr_out"
      (ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> double
       @-> double
       @-> gc_tensor
       @-> double
       @-> int
       @-> int
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs__fw_primal =
    foreign "atg__fw_primal" (gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__fw_primal_copy =
    foreign "atg__fw_primal_copy" (gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__fw_primal_copy_out =
    foreign
      "atg__fw_primal_copy_out"
      (gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__gather_sparse_backward =
    foreign
      "atg__gather_sparse_backward"
      (gc_tensor @-> int64_t @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__grid_sampler_2d_cpu_fallback =
    foreign
      "atg__grid_sampler_2d_cpu_fallback"
      (gc_tensor @-> gc_tensor @-> int64_t @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__grid_sampler_2d_cpu_fallback_backward =
    foreign
      "atg__grid_sampler_2d_cpu_fallback_backward"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> int
       @-> returning void)
  ;;

  let stubs__grid_sampler_2d_cpu_fallback_out =
    foreign
      "atg__grid_sampler_2d_cpu_fallback_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__has_compatible_shallow_copy_type =
    foreign
      "atg__has_compatible_shallow_copy_type"
      (gc_tensor @-> gc_tensor @-> returning bool)
  ;;

  let stubs__has_same_storage_numel =
    foreign "atg__has_same_storage_numel" (gc_tensor @-> gc_tensor @-> returning bool)
  ;;

  let stubs__histogramdd_bin_edges =
    foreign
      "atg__histogramdd_bin_edges"
      (gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr double
       @-> int
       @-> gc_tensor
       @-> int
       @-> returning (ptr raw_tensor))
  ;;

  let stubs__histogramdd_bin_edges_out =
    foreign
      "atg__histogramdd_bin_edges_out"
      (ptr gc_tensor
       @-> int
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr double
       @-> int
       @-> gc_tensor
       @-> int
       @-> returning void)
  ;;

  let stubs__histogramdd_from_bin_cts =
    foreign
      "atg__histogramdd_from_bin_cts"
      (gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr double
       @-> int
       @-> gc_tensor
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__histogramdd_from_bin_cts_out =
    foreign
      "atg__histogramdd_from_bin_cts_out"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr double
       @-> int
       @-> gc_tensor
       @-> int
       @-> returning raw_tensor)
  ;;
end

module C2 (F : Cstubs.FOREIGN) = struct
  open F
  open Type_defs

  let stubs__histogramdd_from_bin_tensors =
    foreign
      "atg__histogramdd_from_bin_tensors"
      (gc_tensor @-> ptr gc_tensor @-> int @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__histogramdd_from_bin_tensors_out =
    foreign
      "atg__histogramdd_from_bin_tensors_out"
      (gc_tensor
       @-> gc_tensor
       @-> ptr gc_tensor
       @-> int
       @-> gc_tensor
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__indices = foreign "atg__indices" (gc_tensor @-> returning raw_tensor)

  let stubs__indices_copy =
    foreign "atg__indices_copy" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__indices_copy_out =
    foreign "atg__indices_copy_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__int_mm =
    foreign "atg__int_mm" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__int_mm_out =
    foreign
      "atg__int_mm_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__is_all_true = foreign "atg__is_all_true" (gc_tensor @-> returning raw_tensor)
  let stubs__is_any_true = foreign "atg__is_any_true" (gc_tensor @-> returning raw_tensor)
  let stubs__is_zerotensor = foreign "atg__is_zerotensor" (gc_tensor @-> returning bool)
  let stubs__lazy_clone = foreign "atg__lazy_clone" (gc_tensor @-> returning raw_tensor)

  let stubs__linalg_check_errors =
    foreign "atg__linalg_check_errors" (gc_tensor @-> string @-> int @-> returning void)
  ;;

  let stubs__linalg_det =
    foreign "atg__linalg_det" (ptr raw_tensor @-> gc_tensor @-> returning void)
  ;;

  let stubs__linalg_det_result =
    foreign
      "atg__linalg_det_result"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs__linalg_eigh =
    foreign
      "atg__linalg_eigh"
      (ptr raw_tensor @-> gc_tensor @-> string @-> int @-> returning void)
  ;;

  let stubs__linalg_eigh_eigenvalues =
    foreign
      "atg__linalg_eigh_eigenvalues"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> string
       @-> int
       @-> returning void)
  ;;

  let stubs__linalg_eigvals =
    foreign "atg__linalg_eigvals" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__linalg_slogdet =
    foreign "atg__linalg_slogdet" (ptr raw_tensor @-> gc_tensor @-> returning void)
  ;;

  let stubs__linalg_slogdet_sign =
    foreign
      "atg__linalg_slogdet_sign"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs__linalg_solve_ex =
    foreign
      "atg__linalg_solve_ex"
      (ptr raw_tensor @-> gc_tensor @-> gc_tensor @-> int @-> int @-> returning void)
  ;;

  let stubs__linalg_solve_ex_result =
    foreign
      "atg__linalg_solve_ex_result"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs__linalg_svd =
    foreign
      "atg__linalg_svd"
      (ptr raw_tensor @-> gc_tensor @-> int @-> int @-> string @-> int @-> returning void)
  ;;

  let stubs__linalg_svd_u =
    foreign
      "atg__linalg_svd_u"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> int
       @-> string
       @-> int
       @-> returning void)
  ;;

  let stubs__log_softmax =
    foreign "atg__log_softmax" (gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__log_softmax_backward_data =
    foreign
      "atg__log_softmax_backward_data"
      (gc_tensor @-> gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__log_softmax_backward_data_out =
    foreign
      "atg__log_softmax_backward_data_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__log_softmax_out =
    foreign
      "atg__log_softmax_out"
      (gc_tensor @-> gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__logcumsumexp =
    foreign "atg__logcumsumexp" (gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__logcumsumexp_out =
    foreign
      "atg__logcumsumexp_out"
      (gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__lstm_mps =
    foreign
      "atg__lstm_mps"
      (ptr raw_tensor
       @-> gc_tensor
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> int
       @-> int64_t
       @-> double
       @-> int
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs__lstm_mps_out =
    foreign
      "atg__lstm_mps_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> int
       @-> int64_t
       @-> double
       @-> int
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs__lu_with_info =
    foreign
      "atg__lu_with_info"
      (ptr raw_tensor @-> gc_tensor @-> int @-> int @-> returning void)
  ;;

  let stubs__make_dep_token =
    foreign "atg__make_dep_token" (int @-> int @-> returning raw_tensor)
  ;;

  let stubs__make_dual =
    foreign "atg__make_dual" (gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__make_dual_copy =
    foreign
      "atg__make_dual_copy"
      (gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__make_dual_copy_out =
    foreign
      "atg__make_dual_copy_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__make_per_channel_quantized_tensor =
    foreign
      "atg__make_per_channel_quantized_tensor"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__make_per_channel_quantized_tensor_out =
    foreign
      "atg__make_per_channel_quantized_tensor_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs__make_per_tensor_quantized_tensor =
    foreign
      "atg__make_per_tensor_quantized_tensor"
      (gc_tensor @-> double @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__make_per_tensor_quantized_tensor_out =
    foreign
      "atg__make_per_tensor_quantized_tensor_out"
      (gc_tensor @-> gc_tensor @-> double @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__masked_scale =
    foreign
      "atg__masked_scale"
      (gc_tensor @-> gc_tensor @-> double @-> returning raw_tensor)
  ;;

  let stubs__masked_scale_out =
    foreign
      "atg__masked_scale_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> double @-> returning raw_tensor)
  ;;

  let stubs__masked_softmax =
    foreign
      "atg__masked_softmax"
      (gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__masked_softmax_backward =
    foreign
      "atg__masked_softmax_backward"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__masked_softmax_backward_out =
    foreign
      "atg__masked_softmax_backward_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__masked_softmax_out =
    foreign
      "atg__masked_softmax_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__mixed_dtypes_linear =
    foreign
      "atg__mixed_dtypes_linear"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> string
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__mkldnn_reshape =
    foreign
      "atg__mkldnn_reshape"
      (gc_tensor @-> ptr int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__mkldnn_reshape_out =
    foreign
      "atg__mkldnn_reshape_out"
      (gc_tensor @-> gc_tensor @-> ptr int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__mkldnn_transpose =
    foreign
      "atg__mkldnn_transpose"
      (gc_tensor @-> int64_t @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__mkldnn_transpose_ =
    foreign
      "atg__mkldnn_transpose_"
      (gc_tensor @-> int64_t @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__mkldnn_transpose_out =
    foreign
      "atg__mkldnn_transpose_out"
      (gc_tensor @-> gc_tensor @-> int64_t @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__mps_convolution =
    foreign
      "atg__mps_convolution"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs__mps_convolution_out =
    foreign
      "atg__mps_convolution_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs__mps_convolution_transpose =
    foreign
      "atg__mps_convolution_transpose"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs__mps_convolution_transpose_out =
    foreign
      "atg__mps_convolution_transpose_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs__native_batch_norm_legit =
    foreign
      "atg__native_batch_norm_legit"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> double
       @-> double
       @-> returning void)
  ;;

  let stubs__native_batch_norm_legit_functional =
    foreign
      "atg__native_batch_norm_legit_functional"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> double
       @-> double
       @-> returning void)
  ;;

  let stubs__native_batch_norm_legit_no_stats =
    foreign
      "atg__native_batch_norm_legit_no_stats"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> double
       @-> double
       @-> returning void)
  ;;

  let stubs__native_batch_norm_legit_no_stats_out =
    foreign
      "atg__native_batch_norm_legit_no_stats_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> double
       @-> double
       @-> returning void)
  ;;

  let stubs__native_batch_norm_legit_no_training =
    foreign
      "atg__native_batch_norm_legit_no_training"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> double
       @-> returning void)
  ;;

  let stubs__native_batch_norm_legit_no_training_out =
    foreign
      "atg__native_batch_norm_legit_no_training_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> double
       @-> returning void)
  ;;

  let stubs__native_batch_norm_legit_out =
    foreign
      "atg__native_batch_norm_legit_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> double
       @-> double
       @-> returning void)
  ;;

  let stubs__native_multi_head_attention =
    foreign
      "atg__native_multi_head_attention"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> int
       @-> int64_t
       @-> int
       @-> returning void)
  ;;

  let stubs__native_multi_head_attention_out =
    foreign
      "atg__native_multi_head_attention_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> int
       @-> int64_t
       @-> int
       @-> returning void)
  ;;

  let stubs__neg_view = foreign "atg__neg_view" (gc_tensor @-> returning raw_tensor)

  let stubs__neg_view_copy =
    foreign "atg__neg_view_copy" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__neg_view_copy_out =
    foreign "atg__neg_view_copy_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__nested_compute_contiguous_strides_offsets =
    foreign
      "atg__nested_compute_contiguous_strides_offsets"
      (ptr raw_tensor @-> gc_tensor @-> returning void)
  ;;

  let stubs__nested_from_padded =
    foreign
      "atg__nested_from_padded"
      (gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__nested_from_padded_and_nested_example =
    foreign
      "atg__nested_from_padded_and_nested_example"
      (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__nested_from_padded_and_nested_example_out =
    foreign
      "atg__nested_from_padded_and_nested_example_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__nested_from_padded_out =
    foreign
      "atg__nested_from_padded_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__nested_from_padded_tensor =
    foreign
      "atg__nested_from_padded_tensor"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__nested_get_jagged_dummy =
    foreign "atg__nested_get_jagged_dummy" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__nested_get_lengths =
    foreign "atg__nested_get_lengths" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__nested_get_max_seqlen =
    foreign "atg__nested_get_max_seqlen" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__nested_get_min_seqlen =
    foreign "atg__nested_get_min_seqlen" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__nested_get_offsets =
    foreign "atg__nested_get_offsets" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__nested_get_ragged_idx =
    foreign "atg__nested_get_ragged_idx" (gc_tensor @-> returning int64_t)
  ;;

  let stubs__nested_get_values =
    foreign "atg__nested_get_values" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__nested_get_values_copy =
    foreign "atg__nested_get_values_copy" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__nested_get_values_copy_out =
    foreign
      "atg__nested_get_values_copy_out"
      (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__nested_select_backward =
    foreign
      "atg__nested_select_backward"
      (gc_tensor @-> gc_tensor @-> int64_t @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__nested_sum_backward =
    foreign
      "atg__nested_sum_backward"
      (gc_tensor @-> gc_tensor @-> ptr int64_t @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs__nested_view_from_buffer =
    foreign
      "atg__nested_view_from_buffer"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__nested_view_from_buffer_copy =
    foreign
      "atg__nested_view_from_buffer_copy"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__nested_view_from_buffer_copy_out =
    foreign
      "atg__nested_view_from_buffer_copy_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> returning raw_tensor)
  ;;

  let stubs__nested_view_from_jagged =
    foreign
      "atg__nested_view_from_jagged"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> gc_tensor
       @-> gc_tensor
       @-> returning raw_tensor)
  ;;

  let stubs__nested_view_from_jagged_copy =
    foreign
      "atg__nested_view_from_jagged_copy"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> gc_tensor
       @-> gc_tensor
       @-> returning raw_tensor)
  ;;

  let stubs__nested_view_from_jagged_copy_out =
    foreign
      "atg__nested_view_from_jagged_copy_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> gc_tensor
       @-> gc_tensor
       @-> returning raw_tensor)
  ;;

  let stubs__new_zeros_with_same_feature_meta =
    foreign
      "atg__new_zeros_with_same_feature_meta"
      (gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__new_zeros_with_same_feature_meta_out =
    foreign
      "atg__new_zeros_with_same_feature_meta_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__nnpack_available = foreign "atg__nnpack_available" (void @-> returning bool)

  let stubs__nnpack_spatial_convolution =
    foreign
      "atg__nnpack_spatial_convolution"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__nnpack_spatial_convolution_out =
    foreign
      "atg__nnpack_spatial_convolution_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__nnz = foreign "atg__nnz" (gc_tensor @-> returning int64_t)

  let stubs__pack_padded_sequence =
    foreign
      "atg__pack_padded_sequence"
      (ptr raw_tensor @-> gc_tensor @-> gc_tensor @-> int @-> returning void)
  ;;

  let stubs__pack_padded_sequence_backward =
    foreign
      "atg__pack_padded_sequence_backward"
      (gc_tensor @-> ptr int64_t @-> int @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__pack_padded_sequence_out =
    foreign
      "atg__pack_padded_sequence_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> returning void)
  ;;
end

module C3 (F : Cstubs.FOREIGN) = struct
  open F
  open Type_defs

  let stubs__pad_circular =
    foreign
      "atg__pad_circular"
      (gc_tensor @-> ptr int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__pad_enum =
    foreign
      "atg__pad_enum"
      (gc_tensor
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> double
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__pad_packed_sequence =
    foreign
      "atg__pad_packed_sequence"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> scalar
       @-> int64_t
       @-> returning void)
  ;;

  let stubs__pdist_backward =
    foreign
      "atg__pdist_backward"
      (gc_tensor @-> gc_tensor @-> double @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__pdist_backward_out =
    foreign
      "atg__pdist_backward_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> gc_tensor
       @-> returning raw_tensor)
  ;;

  let stubs__pin_memory =
    foreign "atg__pin_memory" (gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__pin_memory_out =
    foreign
      "atg__pin_memory_out"
      (gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs__prelu_kernel =
    foreign "atg__prelu_kernel" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__prelu_kernel_backward =
    foreign
      "atg__prelu_kernel_backward"
      (ptr raw_tensor @-> gc_tensor @-> gc_tensor @-> gc_tensor @-> returning void)
  ;;

  let stubs__print = foreign "atg__print" (string @-> returning void)

  let stubs__propagate_xla_data =
    foreign "atg__propagate_xla_data" (gc_tensor @-> gc_tensor @-> returning void)
  ;;

  let stubs__remove_batch_dim =
    foreign
      "atg__remove_batch_dim"
      (gc_tensor @-> int64_t @-> int64_t @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs__reshape_alias =
    foreign
      "atg__reshape_alias"
      (gc_tensor @-> ptr int64_t @-> int @-> ptr int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__reshape_alias_copy =
    foreign
      "atg__reshape_alias_copy"
      (gc_tensor @-> ptr int64_t @-> int @-> ptr int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__reshape_alias_copy_out =
    foreign
      "atg__reshape_alias_copy_out"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs__reshape_copy =
    foreign
      "atg__reshape_copy"
      (gc_tensor @-> ptr int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__reshape_from_tensor =
    foreign "atg__reshape_from_tensor" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__resize_output =
    foreign
      "atg__resize_output"
      (gc_tensor @-> ptr int64_t @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs__resize_output_ =
    foreign
      "atg__resize_output_"
      (gc_tensor @-> ptr int64_t @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs__resize_output_out =
    foreign
      "atg__resize_output_out"
      (gc_tensor @-> gc_tensor @-> ptr int64_t @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs__rowwise_prune =
    foreign
      "atg__rowwise_prune"
      (ptr raw_tensor @-> gc_tensor @-> gc_tensor @-> int @-> returning void)
  ;;

  let stubs__safe_softmax =
    foreign "atg__safe_softmax" (gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs__sample_dirichlet =
    foreign "atg__sample_dirichlet" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__sample_dirichlet_out =
    foreign "atg__sample_dirichlet_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__saturate_weight_to_fp16 =
    foreign "atg__saturate_weight_to_fp16" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs__scaled_dot_product_attention_math =
    foreign
      "atg__scaled_dot_product_attention_math"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> int
       @-> gc_tensor
       @-> double
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs__scaled_dot_product_attention_math_for_mps =
    foreign
      "atg__scaled_dot_product_attention_math_for_mps"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> int
       @-> gc_tensor
       @-> double
       @-> int
       @-> returning void)
  ;;

  let stubs__scaled_dot_product_cudnn_attention_backward =
    foreign
      "atg__scaled_dot_product_cudnn_attention_backward"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> double
       @-> int
       @-> double
       @-> int
       @-> returning void)
  ;;
end

module C (F : Cstubs.FOREIGN) = struct
  include C0 (F)
  include C1 (F)
  include C2 (F)
  include C3 (F)
end
