(* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT BY HAND! *)

open Ctypes

module C0 (F : Cstubs.FOREIGN) = struct
  open F
  open Type_defs

  let stubs_index_fill_int_scalar_out =
    foreign
      "atg_index_fill_int_scalar_out"
      (gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> gc_tensor
       @-> scalar
       @-> returning raw_tensor)
  ;;

  let stubs_index_fill_int_tensor =
    foreign
      "atg_index_fill_int_tensor"
      (gc_tensor @-> int64_t @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_index_fill_int_tensor_ =
    foreign
      "atg_index_fill_int_tensor_"
      (gc_tensor @-> int64_t @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_index_fill_int_tensor_out =
    foreign
      "atg_index_fill_int_tensor_out"
      (gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> gc_tensor
       @-> gc_tensor
       @-> returning raw_tensor)
  ;;

  let stubs_index_reduce =
    foreign
      "atg_index_reduce"
      (gc_tensor
       @-> int64_t
       @-> gc_tensor
       @-> gc_tensor
       @-> string
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_index_reduce_ =
    foreign
      "atg_index_reduce_"
      (gc_tensor
       @-> int64_t
       @-> gc_tensor
       @-> gc_tensor
       @-> string
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_index_reduce_out =
    foreign
      "atg_index_reduce_out"
      (gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> gc_tensor
       @-> gc_tensor
       @-> string
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_index_select =
    foreign
      "atg_index_select"
      (gc_tensor @-> int64_t @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_index_select_backward =
    foreign
      "atg_index_select_backward"
      (gc_tensor
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> gc_tensor
       @-> returning raw_tensor)
  ;;

  let stubs_index_select_out =
    foreign
      "atg_index_select_out"
      (gc_tensor @-> gc_tensor @-> int64_t @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_indices = foreign "atg_indices" (gc_tensor @-> returning raw_tensor)
  let stubs_indices_copy = foreign "atg_indices_copy" (gc_tensor @-> returning raw_tensor)

  let stubs_indices_copy_out =
    foreign "atg_indices_copy_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_infinitely_differentiable_gelu_backward =
    foreign
      "atg_infinitely_differentiable_gelu_backward"
      (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_inner = foreign "atg_inner" (gc_tensor @-> gc_tensor @-> returning raw_tensor)

  let stubs_inner_out =
    foreign
      "atg_inner_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_instance_norm =
    foreign
      "atg_instance_norm"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> double
       @-> double
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_int_repr = foreign "atg_int_repr" (gc_tensor @-> returning raw_tensor)

  let stubs_int_repr_out =
    foreign "atg_int_repr_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_inverse = foreign "atg_inverse" (gc_tensor @-> returning raw_tensor)

  let stubs_inverse_out =
    foreign "atg_inverse_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_is_coalesced = foreign "atg_is_coalesced" (gc_tensor @-> returning bool)
  let stubs_is_complex = foreign "atg_is_complex" (gc_tensor @-> returning bool)
  let stubs_is_conj = foreign "atg_is_conj" (gc_tensor @-> returning bool)
  let stubs_is_distributed = foreign "atg_is_distributed" (gc_tensor @-> returning bool)

  let stubs_is_floating_point =
    foreign "atg_is_floating_point" (gc_tensor @-> returning bool)
  ;;

  let stubs_is_inference = foreign "atg_is_inference" (gc_tensor @-> returning bool)
  let stubs_is_leaf = foreign "atg_is_leaf" (gc_tensor @-> returning bool)
  let stubs_is_neg = foreign "atg_is_neg" (gc_tensor @-> returning bool)
  let stubs_is_nonzero = foreign "atg_is_nonzero" (gc_tensor @-> returning bool)
  let stubs_is_pinned = foreign "atg_is_pinned" (gc_tensor @-> int @-> returning bool)

  let stubs_is_same_size =
    foreign "atg_is_same_size" (gc_tensor @-> gc_tensor @-> returning bool)
  ;;

  let stubs_is_set_to =
    foreign "atg_is_set_to" (gc_tensor @-> gc_tensor @-> returning bool)
  ;;

  let stubs_is_signed = foreign "atg_is_signed" (gc_tensor @-> returning bool)

  let stubs_is_vulkan_available =
    foreign "atg_is_vulkan_available" (void @-> returning bool)
  ;;

  let stubs_isclose =
    foreign
      "atg_isclose"
      (gc_tensor @-> gc_tensor @-> double @-> double @-> int @-> returning raw_tensor)
  ;;

  let stubs_isfinite = foreign "atg_isfinite" (gc_tensor @-> returning raw_tensor)

  let stubs_isin =
    foreign "atg_isin" (gc_tensor @-> gc_tensor @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_isin_scalar_tensor =
    foreign
      "atg_isin_scalar_tensor"
      (scalar @-> gc_tensor @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_isin_scalar_tensor_out =
    foreign
      "atg_isin_scalar_tensor_out"
      (gc_tensor @-> scalar @-> gc_tensor @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_isin_tensor_scalar =
    foreign
      "atg_isin_tensor_scalar"
      (gc_tensor @-> scalar @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_isin_tensor_scalar_out =
    foreign
      "atg_isin_tensor_scalar_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_isin_tensor_tensor_out =
    foreign
      "atg_isin_tensor_tensor_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_isinf = foreign "atg_isinf" (gc_tensor @-> returning raw_tensor)

  let stubs_isinf_out =
    foreign "atg_isinf_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_isnan = foreign "atg_isnan" (gc_tensor @-> returning raw_tensor)

  let stubs_isnan_out =
    foreign "atg_isnan_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_isneginf = foreign "atg_isneginf" (gc_tensor @-> returning raw_tensor)

  let stubs_isneginf_out =
    foreign "atg_isneginf_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_isposinf = foreign "atg_isposinf" (gc_tensor @-> returning raw_tensor)

  let stubs_isposinf_out =
    foreign "atg_isposinf_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_isreal = foreign "atg_isreal" (gc_tensor @-> returning raw_tensor)

  let stubs_istft =
    foreign
      "atg_istft"
      (gc_tensor
       @-> int64_t
       @-> int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> gc_tensor
       @-> int
       @-> int
       @-> int
       @-> int64_t
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_kaiser_window =
    foreign "atg_kaiser_window" (int64_t @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_kaiser_window_beta =
    foreign
      "atg_kaiser_window_beta"
      (int64_t @-> int @-> double @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_kaiser_window_beta_out =
    foreign
      "atg_kaiser_window_beta_out"
      (gc_tensor @-> int64_t @-> int @-> double @-> returning raw_tensor)
  ;;

  let stubs_kaiser_window_out =
    foreign "atg_kaiser_window_out" (gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_kaiser_window_periodic =
    foreign
      "atg_kaiser_window_periodic"
      (int64_t @-> int @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_kaiser_window_periodic_out =
    foreign
      "atg_kaiser_window_periodic_out"
      (gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_kl_div =
    foreign
      "atg_kl_div"
      (gc_tensor @-> gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_kron = foreign "atg_kron" (gc_tensor @-> gc_tensor @-> returning raw_tensor)

  let stubs_kron_out =
    foreign "atg_kron_out" (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_kthvalue =
    foreign
      "atg_kthvalue"
      (ptr raw_tensor @-> gc_tensor @-> int64_t @-> int64_t @-> int @-> returning void)
  ;;

  let stubs_kthvalue_values =
    foreign
      "atg_kthvalue_values"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> int
       @-> returning void)
  ;;

  let stubs_l1_loss =
    foreign "atg_l1_loss" (gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_layer_norm =
    foreign
      "atg_layer_norm"
      (gc_tensor
       @-> ptr int64_t
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_lcm = foreign "atg_lcm" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  let stubs_lcm_ = foreign "atg_lcm_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)

  let stubs_lcm_out =
    foreign "atg_lcm_out" (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_ldexp = foreign "atg_ldexp" (gc_tensor @-> gc_tensor @-> returning raw_tensor)

  let stubs_ldexp_ =
    foreign "atg_ldexp_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_ldexp_out =
    foreign
      "atg_ldexp_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_le = foreign "atg_le" (gc_tensor @-> scalar @-> returning raw_tensor)
  let stubs_le_ = foreign "atg_le_" (gc_tensor @-> scalar @-> returning raw_tensor)

  let stubs_le_scalar_out =
    foreign
      "atg_le_scalar_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_le_tensor =
    foreign "atg_le_tensor" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_le_tensor_ =
    foreign "atg_le_tensor_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_le_tensor_out =
    foreign
      "atg_le_tensor_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_leaky_relu =
    foreign "atg_leaky_relu" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_leaky_relu_ =
    foreign "atg_leaky_relu_" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_leaky_relu_backward =
    foreign
      "atg_leaky_relu_backward"
      (gc_tensor @-> gc_tensor @-> scalar @-> int @-> returning raw_tensor)
  ;;

  let stubs_leaky_relu_backward_grad_input =
    foreign
      "atg_leaky_relu_backward_grad_input"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> scalar @-> int @-> returning raw_tensor)
  ;;

  let stubs_leaky_relu_out =
    foreign
      "atg_leaky_relu_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_lerp =
    foreign "atg_lerp" (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_lerp_ =
    foreign "atg_lerp_" (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_lerp_scalar_out =
    foreign
      "atg_lerp_scalar_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_lerp_tensor =
    foreign
      "atg_lerp_tensor"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_lerp_tensor_ =
    foreign
      "atg_lerp_tensor_"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_lerp_tensor_out =
    foreign
      "atg_lerp_tensor_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_less = foreign "atg_less" (gc_tensor @-> scalar @-> returning raw_tensor)
  let stubs_less_ = foreign "atg_less_" (gc_tensor @-> scalar @-> returning raw_tensor)

  let stubs_less_equal =
    foreign "atg_less_equal" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_less_equal_ =
    foreign "atg_less_equal_" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_less_equal_scalar_out =
    foreign
      "atg_less_equal_scalar_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_less_equal_tensor =
    foreign "atg_less_equal_tensor" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_less_equal_tensor_ =
    foreign "atg_less_equal_tensor_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_less_equal_tensor_out =
    foreign
      "atg_less_equal_tensor_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_less_scalar_out =
    foreign
      "atg_less_scalar_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_less_tensor =
    foreign "atg_less_tensor" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_less_tensor_ =
    foreign "atg_less_tensor_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;
end

module C1 (F : Cstubs.FOREIGN) = struct
  open F
  open Type_defs

  let stubs_less_tensor_out =
    foreign
      "atg_less_tensor_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_lgamma = foreign "atg_lgamma" (gc_tensor @-> returning raw_tensor)
  let stubs_lgamma_ = foreign "atg_lgamma_" (gc_tensor @-> returning raw_tensor)

  let stubs_lgamma_out =
    foreign "atg_lgamma_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_lift = foreign "atg_lift" (gc_tensor @-> returning raw_tensor)
  let stubs_lift_fresh = foreign "atg_lift_fresh" (gc_tensor @-> returning raw_tensor)

  let stubs_lift_fresh_copy =
    foreign "atg_lift_fresh_copy" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_lift_fresh_copy_out =
    foreign "atg_lift_fresh_copy_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_lift_out =
    foreign "atg_lift_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_linalg_cholesky =
    foreign "atg_linalg_cholesky" (gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_cholesky_ex =
    foreign
      "atg_linalg_cholesky_ex"
      (ptr raw_tensor @-> gc_tensor @-> int @-> int @-> returning void)
  ;;

  let stubs_linalg_cholesky_ex_l =
    foreign
      "atg_linalg_cholesky_ex_l"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs_linalg_cholesky_out =
    foreign
      "atg_linalg_cholesky_out"
      (gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_cond =
    foreign "atg_linalg_cond" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_linalg_cond_out =
    foreign
      "atg_linalg_cond_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_linalg_cond_p_str =
    foreign "atg_linalg_cond_p_str" (gc_tensor @-> string @-> returning raw_tensor)
  ;;

  let stubs_linalg_cond_p_str_out =
    foreign
      "atg_linalg_cond_p_str_out"
      (gc_tensor @-> gc_tensor @-> string @-> returning raw_tensor)
  ;;

  let stubs_linalg_cross =
    foreign
      "atg_linalg_cross"
      (gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_linalg_cross_out =
    foreign
      "atg_linalg_cross_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_linalg_det = foreign "atg_linalg_det" (gc_tensor @-> returning raw_tensor)

  let stubs_linalg_det_out =
    foreign "atg_linalg_det_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_linalg_diagonal =
    foreign
      "atg_linalg_diagonal"
      (gc_tensor @-> int64_t @-> int64_t @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_linalg_eig =
    foreign "atg_linalg_eig" (ptr raw_tensor @-> gc_tensor @-> returning void)
  ;;

  let stubs_linalg_eig_out =
    foreign
      "atg_linalg_eig_out"
      (ptr raw_tensor @-> gc_tensor @-> gc_tensor @-> gc_tensor @-> returning void)
  ;;

  let stubs_linalg_eigh =
    foreign "atg_linalg_eigh" (ptr raw_tensor @-> gc_tensor @-> string @-> returning void)
  ;;

  let stubs_linalg_eigh_eigvals =
    foreign
      "atg_linalg_eigh_eigvals"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> string
       @-> returning void)
  ;;

  let stubs_linalg_eigvals =
    foreign "atg_linalg_eigvals" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_linalg_eigvals_out =
    foreign "atg_linalg_eigvals_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_linalg_eigvalsh =
    foreign "atg_linalg_eigvalsh" (gc_tensor @-> string @-> returning raw_tensor)
  ;;

  let stubs_linalg_eigvalsh_out =
    foreign
      "atg_linalg_eigvalsh_out"
      (gc_tensor @-> gc_tensor @-> string @-> returning raw_tensor)
  ;;

  let stubs_linalg_householder_product =
    foreign
      "atg_linalg_householder_product"
      (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_linalg_householder_product_out =
    foreign
      "atg_linalg_householder_product_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_linalg_inv = foreign "atg_linalg_inv" (gc_tensor @-> returning raw_tensor)

  let stubs_linalg_inv_ex =
    foreign "atg_linalg_inv_ex" (ptr raw_tensor @-> gc_tensor @-> int @-> returning void)
  ;;

  let stubs_linalg_inv_ex_inverse =
    foreign
      "atg_linalg_inv_ex_inverse"
      (ptr raw_tensor @-> gc_tensor @-> gc_tensor @-> gc_tensor @-> int @-> returning void)
  ;;

  let stubs_linalg_inv_out =
    foreign "atg_linalg_inv_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_linalg_ldl_factor =
    foreign
      "atg_linalg_ldl_factor"
      (ptr raw_tensor @-> gc_tensor @-> int @-> returning void)
  ;;

  let stubs_linalg_ldl_factor_ex =
    foreign
      "atg_linalg_ldl_factor_ex"
      (ptr raw_tensor @-> gc_tensor @-> int @-> int @-> returning void)
  ;;

  let stubs_linalg_ldl_factor_ex_out =
    foreign
      "atg_linalg_ldl_factor_ex_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs_linalg_ldl_factor_out =
    foreign
      "atg_linalg_ldl_factor_out"
      (ptr raw_tensor @-> gc_tensor @-> gc_tensor @-> gc_tensor @-> int @-> returning void)
  ;;

  let stubs_linalg_ldl_solve =
    foreign
      "atg_linalg_ldl_solve"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_ldl_solve_out =
    foreign
      "atg_linalg_ldl_solve_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_linalg_lstsq =
    foreign
      "atg_linalg_lstsq"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> int
       @-> string
       @-> int
       @-> returning void)
  ;;

  let stubs_linalg_lstsq_out =
    foreign
      "atg_linalg_lstsq_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> int
       @-> string
       @-> int
       @-> returning void)
  ;;

  let stubs_linalg_lu =
    foreign "atg_linalg_lu" (ptr raw_tensor @-> gc_tensor @-> int @-> returning void)
  ;;

  let stubs_linalg_lu_factor =
    foreign
      "atg_linalg_lu_factor"
      (ptr raw_tensor @-> gc_tensor @-> int @-> returning void)
  ;;

  let stubs_linalg_lu_factor_ex =
    foreign
      "atg_linalg_lu_factor_ex"
      (ptr raw_tensor @-> gc_tensor @-> int @-> int @-> returning void)
  ;;

  let stubs_linalg_lu_factor_ex_out =
    foreign
      "atg_linalg_lu_factor_ex_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs_linalg_lu_factor_out =
    foreign
      "atg_linalg_lu_factor_out"
      (ptr raw_tensor @-> gc_tensor @-> gc_tensor @-> gc_tensor @-> int @-> returning void)
  ;;

  let stubs_linalg_lu_out =
    foreign
      "atg_linalg_lu_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> returning void)
  ;;

  let stubs_linalg_lu_solve =
    foreign
      "atg_linalg_lu_solve"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_lu_solve_out =
    foreign
      "atg_linalg_lu_solve_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_linalg_matmul =
    foreign "atg_linalg_matmul" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_linalg_matmul_out =
    foreign
      "atg_linalg_matmul_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_linalg_matrix_exp =
    foreign "atg_linalg_matrix_exp" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_linalg_matrix_exp_out =
    foreign "atg_linalg_matrix_exp_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_linalg_matrix_power =
    foreign "atg_linalg_matrix_power" (gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_linalg_matrix_power_out =
    foreign
      "atg_linalg_matrix_power_out"
      (gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_linalg_matrix_rank =
    foreign
      "atg_linalg_matrix_rank"
      (gc_tensor @-> double @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_matrix_rank_atol_rtol_float =
    foreign
      "atg_linalg_matrix_rank_atol_rtol_float"
      (gc_tensor @-> double @-> int @-> double @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_matrix_rank_atol_rtol_float_out =
    foreign
      "atg_linalg_matrix_rank_atol_rtol_float_out"
      (gc_tensor
       @-> gc_tensor
       @-> double
       @-> int
       @-> double
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_linalg_matrix_rank_atol_rtol_tensor =
    foreign
      "atg_linalg_matrix_rank_atol_rtol_tensor"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_matrix_rank_atol_rtol_tensor_out =
    foreign
      "atg_linalg_matrix_rank_atol_rtol_tensor_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_linalg_matrix_rank_out =
    foreign
      "atg_linalg_matrix_rank_out"
      (gc_tensor @-> gc_tensor @-> double @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_matrix_rank_out_tol_tensor =
    foreign
      "atg_linalg_matrix_rank_out_tol_tensor"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_matrix_rank_tol_tensor =
    foreign
      "atg_linalg_matrix_rank_tol_tensor"
      (gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_multi_dot =
    foreign "atg_linalg_multi_dot" (ptr gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_multi_dot_out =
    foreign
      "atg_linalg_multi_dot_out"
      (gc_tensor @-> ptr gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_pinv =
    foreign "atg_linalg_pinv" (gc_tensor @-> double @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_pinv_atol_rtol_float =
    foreign
      "atg_linalg_pinv_atol_rtol_float"
      (gc_tensor @-> double @-> int @-> double @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_pinv_atol_rtol_float_out =
    foreign
      "atg_linalg_pinv_atol_rtol_float_out"
      (gc_tensor
       @-> gc_tensor
       @-> double
       @-> int
       @-> double
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_linalg_pinv_atol_rtol_tensor =
    foreign
      "atg_linalg_pinv_atol_rtol_tensor"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_pinv_atol_rtol_tensor_out =
    foreign
      "atg_linalg_pinv_atol_rtol_tensor_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_linalg_pinv_out =
    foreign
      "atg_linalg_pinv_out"
      (gc_tensor @-> gc_tensor @-> double @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_pinv_out_rcond_tensor =
    foreign
      "atg_linalg_pinv_out_rcond_tensor"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_pinv_rcond_tensor =
    foreign
      "atg_linalg_pinv_rcond_tensor"
      (gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_qr =
    foreign "atg_linalg_qr" (ptr raw_tensor @-> gc_tensor @-> string @-> returning void)
  ;;

  let stubs_linalg_qr_out =
    foreign
      "atg_linalg_qr_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> string
       @-> returning void)
  ;;

  let stubs_linalg_slogdet =
    foreign "atg_linalg_slogdet" (ptr raw_tensor @-> gc_tensor @-> returning void)
  ;;

  let stubs_linalg_slogdet_out =
    foreign
      "atg_linalg_slogdet_out"
      (ptr raw_tensor @-> gc_tensor @-> gc_tensor @-> gc_tensor @-> returning void)
  ;;

  let stubs_linalg_solve =
    foreign "atg_linalg_solve" (gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_solve_ex =
    foreign
      "atg_linalg_solve_ex"
      (ptr raw_tensor @-> gc_tensor @-> gc_tensor @-> int @-> int @-> returning void)
  ;;

  let stubs_linalg_solve_ex_out =
    foreign
      "atg_linalg_solve_ex_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs_linalg_solve_out =
    foreign
      "atg_linalg_solve_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_solve_triangular =
    foreign
      "atg_linalg_solve_triangular"
      (gc_tensor @-> gc_tensor @-> int @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_solve_triangular_out =
    foreign
      "atg_linalg_solve_triangular_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_linalg_svd =
    foreign
      "atg_linalg_svd"
      (ptr raw_tensor @-> gc_tensor @-> int @-> string @-> int @-> returning void)
  ;;

  let stubs_linalg_svd_u =
    foreign
      "atg_linalg_svd_u"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> string
       @-> int
       @-> returning void)
  ;;

  let stubs_linalg_svdvals =
    foreign "atg_linalg_svdvals" (gc_tensor @-> string @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_svdvals_out =
    foreign
      "atg_linalg_svdvals_out"
      (gc_tensor @-> gc_tensor @-> string @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_tensorinv =
    foreign "atg_linalg_tensorinv" (gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_linalg_tensorinv_out =
    foreign
      "atg_linalg_tensorinv_out"
      (gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_linalg_tensorsolve =
    foreign
      "atg_linalg_tensorsolve"
      (gc_tensor @-> gc_tensor @-> ptr int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_tensorsolve_out =
    foreign
      "atg_linalg_tensorsolve_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_linalg_vander =
    foreign "atg_linalg_vander" (gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_linalg_vecdot =
    foreign
      "atg_linalg_vecdot"
      (gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_linalg_vecdot_out =
    foreign
      "atg_linalg_vecdot_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_linear =
    foreign "atg_linear" (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_linear_out =
    foreign
      "atg_linear_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_linspace =
    foreign
      "atg_linspace"
      (scalar @-> scalar @-> int64_t @-> int @-> int @-> returning raw_tensor)
  ;;
end

module C2 (F : Cstubs.FOREIGN) = struct
  open F
  open Type_defs

  let stubs_linspace_out =
    foreign
      "atg_linspace_out"
      (gc_tensor @-> scalar @-> scalar @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_linspace_scalar_tensor =
    foreign
      "atg_linspace_scalar_tensor"
      (scalar @-> gc_tensor @-> int64_t @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_linspace_scalar_tensor_out =
    foreign
      "atg_linspace_scalar_tensor_out"
      (gc_tensor @-> scalar @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_linspace_tensor_scalar =
    foreign
      "atg_linspace_tensor_scalar"
      (gc_tensor @-> scalar @-> int64_t @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_linspace_tensor_scalar_out =
    foreign
      "atg_linspace_tensor_scalar_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_linspace_tensor_tensor =
    foreign
      "atg_linspace_tensor_tensor"
      (gc_tensor @-> gc_tensor @-> int64_t @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_linspace_tensor_tensor_out =
    foreign
      "atg_linspace_tensor_tensor_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_log = foreign "atg_log" (gc_tensor @-> returning raw_tensor)
  let stubs_log10 = foreign "atg_log10" (gc_tensor @-> returning raw_tensor)
  let stubs_log10_ = foreign "atg_log10_" (gc_tensor @-> returning raw_tensor)

  let stubs_log10_out =
    foreign "atg_log10_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_log1p = foreign "atg_log1p" (gc_tensor @-> returning raw_tensor)
  let stubs_log1p_ = foreign "atg_log1p_" (gc_tensor @-> returning raw_tensor)

  let stubs_log1p_out =
    foreign "atg_log1p_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_log2 = foreign "atg_log2" (gc_tensor @-> returning raw_tensor)
  let stubs_log2_ = foreign "atg_log2_" (gc_tensor @-> returning raw_tensor)

  let stubs_log2_out =
    foreign "atg_log2_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_log_ = foreign "atg_log_" (gc_tensor @-> returning raw_tensor)

  let stubs_log_normal =
    foreign "atg_log_normal" (gc_tensor @-> double @-> double @-> returning raw_tensor)
  ;;

  let stubs_log_normal_ =
    foreign "atg_log_normal_" (gc_tensor @-> double @-> double @-> returning raw_tensor)
  ;;

  let stubs_log_normal_out =
    foreign
      "atg_log_normal_out"
      (gc_tensor @-> gc_tensor @-> double @-> double @-> returning raw_tensor)
  ;;

  let stubs_log_out =
    foreign "atg_log_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_log_sigmoid = foreign "atg_log_sigmoid" (gc_tensor @-> returning raw_tensor)

  let stubs_log_sigmoid_backward =
    foreign
      "atg_log_sigmoid_backward"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_log_sigmoid_backward_grad_input =
    foreign
      "atg_log_sigmoid_backward_grad_input"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_log_sigmoid_out =
    foreign "atg_log_sigmoid_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_log_softmax =
    foreign "atg_log_softmax" (gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_log_softmax_int_out =
    foreign
      "atg_log_softmax_int_out"
      (gc_tensor @-> gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_logaddexp =
    foreign "atg_logaddexp" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_logaddexp2 =
    foreign "atg_logaddexp2" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_logaddexp2_out =
    foreign
      "atg_logaddexp2_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_logaddexp_out =
    foreign
      "atg_logaddexp_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_logcumsumexp =
    foreign "atg_logcumsumexp" (gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_logcumsumexp_out =
    foreign
      "atg_logcumsumexp_out"
      (gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_logdet = foreign "atg_logdet" (gc_tensor @-> returning raw_tensor)

  let stubs_logical_and =
    foreign "atg_logical_and" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_logical_and_ =
    foreign "atg_logical_and_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_logical_and_out =
    foreign
      "atg_logical_and_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_logical_not = foreign "atg_logical_not" (gc_tensor @-> returning raw_tensor)
  let stubs_logical_not_ = foreign "atg_logical_not_" (gc_tensor @-> returning raw_tensor)

  let stubs_logical_not_out =
    foreign "atg_logical_not_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_logical_or =
    foreign "atg_logical_or" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_logical_or_ =
    foreign "atg_logical_or_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_logical_or_out =
    foreign
      "atg_logical_or_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_logical_xor =
    foreign "atg_logical_xor" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_logical_xor_ =
    foreign "atg_logical_xor_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_logical_xor_out =
    foreign
      "atg_logical_xor_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_logit =
    foreign "atg_logit" (gc_tensor @-> double @-> int @-> returning raw_tensor)
  ;;

  let stubs_logit_ =
    foreign "atg_logit_" (gc_tensor @-> double @-> int @-> returning raw_tensor)
  ;;

  let stubs_logit_backward =
    foreign
      "atg_logit_backward"
      (gc_tensor @-> gc_tensor @-> double @-> int @-> returning raw_tensor)
  ;;

  let stubs_logit_backward_grad_input =
    foreign
      "atg_logit_backward_grad_input"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> double @-> int @-> returning raw_tensor)
  ;;

  let stubs_logit_out =
    foreign
      "atg_logit_out"
      (gc_tensor @-> gc_tensor @-> double @-> int @-> returning raw_tensor)
  ;;

  let stubs_logspace =
    foreign
      "atg_logspace"
      (scalar @-> scalar @-> int64_t @-> double @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_logspace_out =
    foreign
      "atg_logspace_out"
      (gc_tensor @-> scalar @-> scalar @-> int64_t @-> double @-> returning raw_tensor)
  ;;

  let stubs_logspace_scalar_tensor =
    foreign
      "atg_logspace_scalar_tensor"
      (scalar
       @-> gc_tensor
       @-> int64_t
       @-> double
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_logspace_scalar_tensor_out =
    foreign
      "atg_logspace_scalar_tensor_out"
      (gc_tensor @-> scalar @-> gc_tensor @-> int64_t @-> double @-> returning raw_tensor)
  ;;

  let stubs_logspace_tensor_scalar =
    foreign
      "atg_logspace_tensor_scalar"
      (gc_tensor
       @-> scalar
       @-> int64_t
       @-> double
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_logspace_tensor_scalar_out =
    foreign
      "atg_logspace_tensor_scalar_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> int64_t @-> double @-> returning raw_tensor)
  ;;

  let stubs_logspace_tensor_tensor =
    foreign
      "atg_logspace_tensor_tensor"
      (gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> double
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_logspace_tensor_tensor_out =
    foreign
      "atg_logspace_tensor_tensor_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> double
       @-> returning raw_tensor)
  ;;

  let stubs_logsumexp =
    foreign
      "atg_logsumexp"
      (gc_tensor @-> ptr int64_t @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_logsumexp_out =
    foreign
      "atg_logsumexp_out"
      (gc_tensor @-> gc_tensor @-> ptr int64_t @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_lstm =
    foreign
      "atg_lstm"
      (ptr raw_tensor
       @-> gc_tensor
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> int
       @-> int64_t
       @-> double
       @-> int
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs_lstm_cell =
    foreign
      "atg_lstm_cell"
      (ptr raw_tensor
       @-> gc_tensor
       @-> ptr gc_tensor
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs_lstm_data =
    foreign
      "atg_lstm_data"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> int
       @-> int64_t
       @-> double
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs_lstm_mps_backward =
    foreign
      "atg_lstm_mps_backward"
      (gc_tensor
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr gc_tensor
       @-> int
       @-> ptr gc_tensor
       @-> int
       @-> int
       @-> int64_t
       @-> double
       @-> int
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs_lt = foreign "atg_lt" (gc_tensor @-> scalar @-> returning raw_tensor)
  let stubs_lt_ = foreign "atg_lt_" (gc_tensor @-> scalar @-> returning raw_tensor)

  let stubs_lt_scalar_out =
    foreign
      "atg_lt_scalar_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_lt_tensor =
    foreign "atg_lt_tensor" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_lt_tensor_ =
    foreign "atg_lt_tensor_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_lt_tensor_out =
    foreign
      "atg_lt_tensor_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_lu_solve =
    foreign "atg_lu_solve" (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_lu_solve_out =
    foreign
      "atg_lu_solve_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_lu_unpack =
    foreign
      "atg_lu_unpack"
      (ptr raw_tensor @-> gc_tensor @-> gc_tensor @-> int @-> int @-> returning void)
  ;;

  let stubs_lu_unpack_out =
    foreign
      "atg_lu_unpack_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs_margin_ranking_loss =
    foreign
      "atg_margin_ranking_loss"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_masked_fill =
    foreign "atg_masked_fill" (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_masked_fill_ =
    foreign
      "atg_masked_fill_"
      (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_masked_fill_scalar_out =
    foreign
      "atg_masked_fill_scalar_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_masked_fill_tensor =
    foreign
      "atg_masked_fill_tensor"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_masked_fill_tensor_ =
    foreign
      "atg_masked_fill_tensor_"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_masked_fill_tensor_out =
    foreign
      "atg_masked_fill_tensor_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_masked_scatter =
    foreign
      "atg_masked_scatter"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_masked_scatter_ =
    foreign
      "atg_masked_scatter_"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_masked_scatter_backward =
    foreign
      "atg_masked_scatter_backward"
      (gc_tensor @-> gc_tensor @-> ptr int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_masked_scatter_out =
    foreign
      "atg_masked_scatter_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_masked_select =
    foreign "atg_masked_select" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_masked_select_backward =
    foreign
      "atg_masked_select_backward"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_masked_select_out =
    foreign
      "atg_masked_select_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_matmul =
    foreign "atg_matmul" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_matmul_out =
    foreign
      "atg_matmul_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_matrix_exp = foreign "atg_matrix_exp" (gc_tensor @-> returning raw_tensor)

  let stubs_matrix_exp_backward =
    foreign "atg_matrix_exp_backward" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_matrix_h = foreign "atg_matrix_h" (gc_tensor @-> returning raw_tensor)

  let stubs_matrix_power =
    foreign "atg_matrix_power" (gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_matrix_power_out =
    foreign
      "atg_matrix_power_out"
      (gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_max = foreign "atg_max" (gc_tensor @-> returning raw_tensor)

  let stubs_max_dim =
    foreign
      "atg_max_dim"
      (ptr raw_tensor @-> gc_tensor @-> int64_t @-> int @-> returning void)
  ;;

  let stubs_max_dim_max =
    foreign
      "atg_max_dim_max"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int
       @-> returning void)
  ;;
end

module C3 (F : Cstubs.FOREIGN) = struct
  open F
  open Type_defs

  let stubs_max_other =
    foreign "atg_max_other" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_max_out =
    foreign "atg_max_out" (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_max_pool1d =
    foreign
      "atg_max_pool1d"
      (gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_max_pool1d_with_indices =
    foreign
      "atg_max_pool1d_with_indices"
      (ptr raw_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs_max_pool2d =
    foreign
      "atg_max_pool2d"
      (gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_max_pool2d_backward =
    foreign
      "atg_max_pool2d_backward"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_max_pool2d_backward_out =
    foreign
      "atg_max_pool2d_backward_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_max_pool2d_with_indices =
    foreign
      "atg_max_pool2d_with_indices"
      (ptr raw_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs_max_pool2d_with_indices_backward =
    foreign
      "atg_max_pool2d_with_indices_backward"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> gc_tensor
       @-> returning raw_tensor)
  ;;

  let stubs_max_pool2d_with_indices_backward_grad_input =
    foreign
      "atg_max_pool2d_with_indices_backward_grad_input"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> gc_tensor
       @-> returning raw_tensor)
  ;;

  let stubs_max_pool2d_with_indices_out =
    foreign
      "atg_max_pool2d_with_indices_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs_max_pool3d =
    foreign
      "atg_max_pool3d"
      (gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_max_pool3d_with_indices =
    foreign
      "atg_max_pool3d_with_indices"
      (ptr raw_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs_max_pool3d_with_indices_backward =
    foreign
      "atg_max_pool3d_with_indices_backward"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> gc_tensor
       @-> returning raw_tensor)
  ;;

  let stubs_max_pool3d_with_indices_backward_grad_input =
    foreign
      "atg_max_pool3d_with_indices_backward_grad_input"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> gc_tensor
       @-> returning raw_tensor)
  ;;

  let stubs_max_pool3d_with_indices_out =
    foreign
      "atg_max_pool3d_with_indices_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs_max_unary_out =
    foreign "atg_max_unary_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_max_unpool2d =
    foreign
      "atg_max_unpool2d"
      (gc_tensor @-> gc_tensor @-> ptr int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_max_unpool2d_out =
    foreign
      "atg_max_unpool2d_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_max_unpool3d =
    foreign
      "atg_max_unpool3d"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_max_unpool3d_out =
    foreign
      "atg_max_unpool3d_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_maximum =
    foreign "atg_maximum" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_maximum_out =
    foreign
      "atg_maximum_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_mean = foreign "atg_mean" (gc_tensor @-> int @-> returning raw_tensor)

  let stubs_mean_dim =
    foreign
      "atg_mean_dim"
      (gc_tensor @-> ptr int64_t @-> int @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_mean_dtype_out =
    foreign "atg_mean_dtype_out" (gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_mean_out =
    foreign
      "atg_mean_out"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_median = foreign "atg_median" (gc_tensor @-> returning raw_tensor)
end

module C (F : Cstubs.FOREIGN) = struct
  include C0 (F)
  include C1 (F)
  include C2 (F)
  include C3 (F)
end
