(* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT BY HAND! *)

open Ctypes

module C0 (F : Cstubs.FOREIGN) = struct
  open F
  open Type_defs

  let stubs_atleast_1d = foreign "atg_atleast_1d" (gc_tensor @-> returning raw_tensor)

  let stubs_atleast_1d_sequence =
    foreign
      "atg_atleast_1d_sequence"
      (ptr gc_tensor @-> int @-> returning (ptr raw_tensor))
  ;;

  let stubs_atleast_2d = foreign "atg_atleast_2d" (gc_tensor @-> returning raw_tensor)

  let stubs_atleast_2d_sequence =
    foreign
      "atg_atleast_2d_sequence"
      (ptr gc_tensor @-> int @-> returning (ptr raw_tensor))
  ;;

  let stubs_atleast_3d = foreign "atg_atleast_3d" (gc_tensor @-> returning raw_tensor)

  let stubs_atleast_3d_sequence =
    foreign
      "atg_atleast_3d_sequence"
      (ptr gc_tensor @-> int @-> returning (ptr raw_tensor))
  ;;

  let stubs_avg_pool1d =
    foreign
      "atg_avg_pool1d"
      (gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_avg_pool1d_out =
    foreign
      "atg_avg_pool1d_out"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_avg_pool2d =
    foreign
      "atg_avg_pool2d"
      (gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> int
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_avg_pool2d_backward =
    foreign
      "atg_avg_pool2d_backward"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> int
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_avg_pool2d_backward_grad_input =
    foreign
      "atg_avg_pool2d_backward_grad_input"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> int
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_avg_pool2d_out =
    foreign
      "atg_avg_pool2d_out"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> int
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_avg_pool3d =
    foreign
      "atg_avg_pool3d"
      (gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> int
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_avg_pool3d_backward =
    foreign
      "atg_avg_pool3d_backward"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> int
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_avg_pool3d_backward_grad_input =
    foreign
      "atg_avg_pool3d_backward_grad_input"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> int
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_avg_pool3d_out =
    foreign
      "atg_avg_pool3d_out"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> int
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_baddbmm =
    foreign
      "atg_baddbmm"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> scalar
       @-> scalar
       @-> returning raw_tensor)
  ;;

  let stubs_baddbmm_ =
    foreign
      "atg_baddbmm_"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> scalar
       @-> scalar
       @-> returning raw_tensor)
  ;;

  let stubs_baddbmm_out =
    foreign
      "atg_baddbmm_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> scalar
       @-> scalar
       @-> returning raw_tensor)
  ;;

  let stubs_bartlett_window =
    foreign "atg_bartlett_window" (int64_t @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_bartlett_window_out =
    foreign "atg_bartlett_window_out" (gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_bartlett_window_periodic =
    foreign
      "atg_bartlett_window_periodic"
      (int64_t @-> int @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_bartlett_window_periodic_out =
    foreign
      "atg_bartlett_window_periodic_out"
      (gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_batch_norm =
    foreign
      "atg_batch_norm"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> double
       @-> double
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_batch_norm_backward_elemt =
    foreign
      "atg_batch_norm_backward_elemt"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> returning raw_tensor)
  ;;

  let stubs_batch_norm_backward_elemt_out =
    foreign
      "atg_batch_norm_backward_elemt_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> returning raw_tensor)
  ;;

  let stubs_batch_norm_backward_reduce =
    foreign
      "atg_batch_norm_backward_reduce"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs_batch_norm_backward_reduce_out =
    foreign
      "atg_batch_norm_backward_reduce_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> int
       @-> int
       @-> returning void)
  ;;

  let stubs_batch_norm_elemt =
    foreign
      "atg_batch_norm_elemt"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> returning raw_tensor)
  ;;

  let stubs_batch_norm_elemt_out =
    foreign
      "atg_batch_norm_elemt_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> returning raw_tensor)
  ;;

  let stubs_batch_norm_gather_stats =
    foreign
      "atg_batch_norm_gather_stats"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> double
       @-> int64_t
       @-> returning void)
  ;;

  let stubs_batch_norm_gather_stats_out =
    foreign
      "atg_batch_norm_gather_stats_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> double
       @-> int64_t
       @-> returning void)
  ;;

  let stubs_batch_norm_gather_stats_with_counts =
    foreign
      "atg_batch_norm_gather_stats_with_counts"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> double
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs_batch_norm_gather_stats_with_counts_out =
    foreign
      "atg_batch_norm_gather_stats_with_counts_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> double
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs_batch_norm_stats =
    foreign
      "atg_batch_norm_stats"
      (ptr raw_tensor @-> gc_tensor @-> double @-> returning void)
  ;;

  let stubs_batch_norm_stats_out =
    foreign
      "atg_batch_norm_stats_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> returning void)
  ;;

  let stubs_batch_norm_update_stats =
    foreign
      "atg_batch_norm_update_stats"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> returning void)
  ;;

  let stubs_batch_norm_update_stats_out =
    foreign
      "atg_batch_norm_update_stats_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> returning void)
  ;;

  let stubs_bernoulli = foreign "atg_bernoulli" (gc_tensor @-> returning raw_tensor)

  let stubs_bernoulli_ =
    foreign "atg_bernoulli_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bernoulli_float_ =
    foreign "atg_bernoulli_float_" (gc_tensor @-> double @-> returning raw_tensor)
  ;;

  let stubs_bernoulli_p =
    foreign "atg_bernoulli_p" (gc_tensor @-> double @-> returning raw_tensor)
  ;;

  let stubs_bernoulli_tensor =
    foreign "atg_bernoulli_tensor" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bilinear =
    foreign
      "atg_bilinear"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_binary_cross_entropy =
    foreign
      "atg_binary_cross_entropy"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_binary_cross_entropy_backward =
    foreign
      "atg_binary_cross_entropy_backward"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_binary_cross_entropy_backward_grad_input =
    foreign
      "atg_binary_cross_entropy_backward_grad_input"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_binary_cross_entropy_out =
    foreign
      "atg_binary_cross_entropy_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_binary_cross_entropy_with_logits =
    foreign
      "atg_binary_cross_entropy_with_logits"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_binary_cross_entropy_with_logits_out =
    foreign
      "atg_binary_cross_entropy_with_logits_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_bincount =
    foreign "atg_bincount" (gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_bincount_out =
    foreign
      "atg_bincount_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_binomial =
    foreign "atg_binomial" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_binomial_out =
    foreign
      "atg_binomial_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_and =
    foreign "atg_bitwise_and" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_bitwise_and_ =
    foreign "atg_bitwise_and_" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_bitwise_and_scalar_out =
    foreign
      "atg_bitwise_and_scalar_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_bitwise_and_scalar_tensor =
    foreign "atg_bitwise_and_scalar_tensor" (scalar @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_and_scalar_tensor_out =
    foreign
      "atg_bitwise_and_scalar_tensor_out"
      (gc_tensor @-> scalar @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_and_tensor =
    foreign "atg_bitwise_and_tensor" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_and_tensor_ =
    foreign "atg_bitwise_and_tensor_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_and_tensor_out =
    foreign
      "atg_bitwise_and_tensor_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_left_shift =
    foreign "atg_bitwise_left_shift" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_left_shift_ =
    foreign "atg_bitwise_left_shift_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_left_shift_scalar_tensor =
    foreign
      "atg_bitwise_left_shift_scalar_tensor"
      (scalar @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_left_shift_scalar_tensor_out =
    foreign
      "atg_bitwise_left_shift_scalar_tensor_out"
      (gc_tensor @-> scalar @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_left_shift_tensor_out =
    foreign
      "atg_bitwise_left_shift_tensor_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_left_shift_tensor_scalar =
    foreign
      "atg_bitwise_left_shift_tensor_scalar"
      (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_bitwise_left_shift_tensor_scalar_ =
    foreign
      "atg_bitwise_left_shift_tensor_scalar_"
      (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_bitwise_left_shift_tensor_scalar_out =
    foreign
      "atg_bitwise_left_shift_tensor_scalar_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_bitwise_not = foreign "atg_bitwise_not" (gc_tensor @-> returning raw_tensor)
  let stubs_bitwise_not_ = foreign "atg_bitwise_not_" (gc_tensor @-> returning raw_tensor)

  let stubs_bitwise_not_out =
    foreign "atg_bitwise_not_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_or =
    foreign "atg_bitwise_or" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_bitwise_or_ =
    foreign "atg_bitwise_or_" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_bitwise_or_scalar_out =
    foreign
      "atg_bitwise_or_scalar_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_bitwise_or_scalar_tensor =
    foreign "atg_bitwise_or_scalar_tensor" (scalar @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_or_scalar_tensor_out =
    foreign
      "atg_bitwise_or_scalar_tensor_out"
      (gc_tensor @-> scalar @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_or_tensor =
    foreign "atg_bitwise_or_tensor" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_or_tensor_ =
    foreign "atg_bitwise_or_tensor_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_or_tensor_out =
    foreign
      "atg_bitwise_or_tensor_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_right_shift =
    foreign "atg_bitwise_right_shift" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_right_shift_ =
    foreign "atg_bitwise_right_shift_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_right_shift_scalar_tensor =
    foreign
      "atg_bitwise_right_shift_scalar_tensor"
      (scalar @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_right_shift_scalar_tensor_out =
    foreign
      "atg_bitwise_right_shift_scalar_tensor_out"
      (gc_tensor @-> scalar @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_right_shift_tensor_out =
    foreign
      "atg_bitwise_right_shift_tensor_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_right_shift_tensor_scalar =
    foreign
      "atg_bitwise_right_shift_tensor_scalar"
      (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_bitwise_right_shift_tensor_scalar_ =
    foreign
      "atg_bitwise_right_shift_tensor_scalar_"
      (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_bitwise_right_shift_tensor_scalar_out =
    foreign
      "atg_bitwise_right_shift_tensor_scalar_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_bitwise_xor =
    foreign "atg_bitwise_xor" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_bitwise_xor_ =
    foreign "atg_bitwise_xor_" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_bitwise_xor_scalar_out =
    foreign
      "atg_bitwise_xor_scalar_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_bitwise_xor_scalar_tensor =
    foreign "atg_bitwise_xor_scalar_tensor" (scalar @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_xor_scalar_tensor_out =
    foreign
      "atg_bitwise_xor_scalar_tensor_out"
      (gc_tensor @-> scalar @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_xor_tensor =
    foreign "atg_bitwise_xor_tensor" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_xor_tensor_ =
    foreign "atg_bitwise_xor_tensor_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_bitwise_xor_tensor_out =
    foreign
      "atg_bitwise_xor_tensor_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_blackman_window =
    foreign "atg_blackman_window" (int64_t @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_blackman_window_out =
    foreign "atg_blackman_window_out" (gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_blackman_window_periodic =
    foreign
      "atg_blackman_window_periodic"
      (int64_t @-> int @-> int @-> int @-> returning raw_tensor)
  ;;
end

module C1 (F : Cstubs.FOREIGN) = struct
  open F
  open Type_defs

  let stubs_blackman_window_periodic_out =
    foreign
      "atg_blackman_window_periodic_out"
      (gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_block_diag =
    foreign "atg_block_diag" (ptr gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_block_diag_out =
    foreign
      "atg_block_diag_out"
      (gc_tensor @-> ptr gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_bmm = foreign "atg_bmm" (gc_tensor @-> gc_tensor @-> returning raw_tensor)

  let stubs_bmm_out =
    foreign "atg_bmm_out" (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_broadcast_tensors =
    foreign "atg_broadcast_tensors" (ptr gc_tensor @-> int @-> returning (ptr raw_tensor))
  ;;

  let stubs_broadcast_to =
    foreign "atg_broadcast_to" (gc_tensor @-> ptr int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_bucketize =
    foreign
      "atg_bucketize"
      (gc_tensor @-> gc_tensor @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_bucketize_scalar =
    foreign
      "atg_bucketize_scalar"
      (scalar @-> gc_tensor @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_bucketize_scalar_out =
    foreign
      "atg_bucketize_scalar_out"
      (gc_tensor @-> scalar @-> gc_tensor @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_bucketize_tensor_out =
    foreign
      "atg_bucketize_tensor_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int @-> int @-> returning raw_tensor)
  ;;

  let stubs_can_cast = foreign "atg_can_cast" (int @-> int @-> returning bool)

  let stubs_cartesian_prod =
    foreign "atg_cartesian_prod" (ptr gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_cat =
    foreign "atg_cat" (ptr gc_tensor @-> int @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_cat_out =
    foreign
      "atg_cat_out"
      (gc_tensor @-> ptr gc_tensor @-> int @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_cauchy =
    foreign "atg_cauchy" (gc_tensor @-> double @-> double @-> returning raw_tensor)
  ;;

  let stubs_cauchy_ =
    foreign "atg_cauchy_" (gc_tensor @-> double @-> double @-> returning raw_tensor)
  ;;

  let stubs_cauchy_out =
    foreign
      "atg_cauchy_out"
      (gc_tensor @-> gc_tensor @-> double @-> double @-> returning raw_tensor)
  ;;

  let stubs_ccol_indices = foreign "atg_ccol_indices" (gc_tensor @-> returning raw_tensor)

  let stubs_ccol_indices_copy =
    foreign "atg_ccol_indices_copy" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_ccol_indices_copy_out =
    foreign "atg_ccol_indices_copy_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_cdist =
    foreign
      "atg_cdist"
      (gc_tensor @-> gc_tensor @-> double @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_ceil = foreign "atg_ceil" (gc_tensor @-> returning raw_tensor)
  let stubs_ceil_ = foreign "atg_ceil_" (gc_tensor @-> returning raw_tensor)

  let stubs_ceil_out =
    foreign "atg_ceil_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_celu = foreign "atg_celu" (gc_tensor @-> scalar @-> returning raw_tensor)
  let stubs_celu_ = foreign "atg_celu_" (gc_tensor @-> scalar @-> returning raw_tensor)

  let stubs_celu_out =
    foreign "atg_celu_out" (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_chain_matmul =
    foreign "atg_chain_matmul" (ptr gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_chain_matmul_out =
    foreign
      "atg_chain_matmul_out"
      (gc_tensor @-> ptr gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_chalf = foreign "atg_chalf" (gc_tensor @-> returning raw_tensor)

  let stubs_channel_shuffle =
    foreign "atg_channel_shuffle" (gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_channel_shuffle_out =
    foreign
      "atg_channel_shuffle_out"
      (gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_cholesky = foreign "atg_cholesky" (gc_tensor @-> int @-> returning raw_tensor)

  let stubs_cholesky_inverse =
    foreign "atg_cholesky_inverse" (gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_cholesky_inverse_out =
    foreign
      "atg_cholesky_inverse_out"
      (gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_cholesky_out =
    foreign "atg_cholesky_out" (gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_cholesky_solve =
    foreign "atg_cholesky_solve" (gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_cholesky_solve_out =
    foreign
      "atg_cholesky_solve_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_choose_qparams_optimized =
    foreign
      "atg_choose_qparams_optimized"
      (ptr raw_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> double
       @-> int64_t
       @-> returning void)
  ;;

  let stubs_chunk =
    foreign "atg_chunk" (gc_tensor @-> int64_t @-> int64_t @-> returning (ptr raw_tensor))
  ;;

  let stubs_clamp =
    foreign "atg_clamp" (gc_tensor @-> scalar @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_clamp_ =
    foreign "atg_clamp_" (gc_tensor @-> scalar @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_clamp_max =
    foreign "atg_clamp_max" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_clamp_max_ =
    foreign "atg_clamp_max_" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_clamp_max_out =
    foreign
      "atg_clamp_max_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_clamp_max_tensor =
    foreign "atg_clamp_max_tensor" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_clamp_max_tensor_ =
    foreign "atg_clamp_max_tensor_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_clamp_max_tensor_out =
    foreign
      "atg_clamp_max_tensor_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_clamp_min =
    foreign "atg_clamp_min" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_clamp_min_ =
    foreign "atg_clamp_min_" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_clamp_min_out =
    foreign
      "atg_clamp_min_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_clamp_min_tensor =
    foreign "atg_clamp_min_tensor" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_clamp_min_tensor_ =
    foreign "atg_clamp_min_tensor_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_clamp_min_tensor_out =
    foreign
      "atg_clamp_min_tensor_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_clamp_out =
    foreign
      "atg_clamp_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_clamp_tensor =
    foreign
      "atg_clamp_tensor"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_clamp_tensor_ =
    foreign
      "atg_clamp_tensor_"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_clamp_tensor_out =
    foreign
      "atg_clamp_tensor_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_clip =
    foreign "atg_clip" (gc_tensor @-> scalar @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_clip_ =
    foreign "atg_clip_" (gc_tensor @-> scalar @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_clip_out =
    foreign
      "atg_clip_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_clip_tensor =
    foreign
      "atg_clip_tensor"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_clip_tensor_ =
    foreign
      "atg_clip_tensor_"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_clip_tensor_out =
    foreign
      "atg_clip_tensor_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_clone = foreign "atg_clone" (gc_tensor @-> returning raw_tensor)

  let stubs_clone_out =
    foreign "atg_clone_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_coalesce = foreign "atg_coalesce" (gc_tensor @-> returning raw_tensor)

  let stubs_col2im =
    foreign
      "atg_col2im"
      (gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_col2im_out =
    foreign
      "atg_col2im_out"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_col_indices = foreign "atg_col_indices" (gc_tensor @-> returning raw_tensor)

  let stubs_col_indices_copy =
    foreign "atg_col_indices_copy" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_col_indices_copy_out =
    foreign "atg_col_indices_copy_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_column_stack =
    foreign "atg_column_stack" (ptr gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_column_stack_out =
    foreign
      "atg_column_stack_out"
      (gc_tensor @-> ptr gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_combinations =
    foreign "atg_combinations" (gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_complex =
    foreign "atg_complex" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_complex_out =
    foreign
      "atg_complex_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_concat =
    foreign "atg_concat" (ptr gc_tensor @-> int @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_concat_out =
    foreign
      "atg_concat_out"
      (gc_tensor @-> ptr gc_tensor @-> int @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_concatenate =
    foreign "atg_concatenate" (ptr gc_tensor @-> int @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_concatenate_out =
    foreign
      "atg_concatenate_out"
      (gc_tensor @-> ptr gc_tensor @-> int @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_conj = foreign "atg_conj" (gc_tensor @-> returning raw_tensor)

  let stubs_conj_physical =
    foreign "atg_conj_physical" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_conj_physical_ =
    foreign "atg_conj_physical_" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_conj_physical_out =
    foreign "atg_conj_physical_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_constant_pad_nd =
    foreign
      "atg_constant_pad_nd"
      (gc_tensor @-> ptr int64_t @-> int @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_constant_pad_nd_out =
    foreign
      "atg_constant_pad_nd_out"
      (gc_tensor @-> gc_tensor @-> ptr int64_t @-> int @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_contiguous = foreign "atg_contiguous" (gc_tensor @-> returning raw_tensor)

  let stubs_conv1d =
    foreign
      "atg_conv1d"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_conv1d_padding =
    foreign
      "atg_conv1d_padding"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> string
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_conv2d =
    foreign
      "atg_conv2d"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_conv2d_padding =
    foreign
      "atg_conv2d_padding"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> string
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_conv3d =
    foreign
      "atg_conv3d"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_conv3d_padding =
    foreign
      "atg_conv3d_padding"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> string
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_conv_depthwise3d =
    foreign
      "atg_conv_depthwise3d"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_conv_depthwise3d_out =
    foreign
      "atg_conv_depthwise3d_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_conv_tbc =
    foreign
      "atg_conv_tbc"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_conv_tbc_backward =
    foreign
      "atg_conv_tbc_backward"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> returning void)
  ;;

  let stubs_conv_tbc_out =
    foreign
      "atg_conv_tbc_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> returning raw_tensor)
  ;;
end

module C2 (F : Cstubs.FOREIGN) = struct
  open F
  open Type_defs

  let stubs_conv_transpose1d =
    foreign
      "atg_conv_transpose1d"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> ptr int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_conv_transpose2d =
    foreign
      "atg_conv_transpose2d"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> ptr int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_conv_transpose3d =
    foreign
      "atg_conv_transpose3d"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> ptr int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_convolution =
    foreign
      "atg_convolution"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_convolution_out =
    foreign
      "atg_convolution_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_convolution_overrideable =
    foreign
      "atg_convolution_overrideable"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_convolution_overrideable_out =
    foreign
      "atg_convolution_overrideable_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_copy =
    foreign "atg_copy" (gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_copy_out =
    foreign
      "atg_copy_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_copy_sparse_to_sparse =
    foreign
      "atg_copy_sparse_to_sparse"
      (gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_copy_sparse_to_sparse_ =
    foreign
      "atg_copy_sparse_to_sparse_"
      (gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_copy_sparse_to_sparse_out =
    foreign
      "atg_copy_sparse_to_sparse_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int @-> returning raw_tensor)
  ;;

  let stubs_copysign =
    foreign "atg_copysign" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_copysign_ =
    foreign "atg_copysign_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_copysign_out =
    foreign
      "atg_copysign_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_copysign_scalar =
    foreign "atg_copysign_scalar" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_copysign_scalar_ =
    foreign "atg_copysign_scalar_" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_copysign_scalar_out =
    foreign
      "atg_copysign_scalar_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_corrcoef = foreign "atg_corrcoef" (gc_tensor @-> returning raw_tensor)
  let stubs_cos = foreign "atg_cos" (gc_tensor @-> returning raw_tensor)
  let stubs_cos_ = foreign "atg_cos_" (gc_tensor @-> returning raw_tensor)

  let stubs_cos_out =
    foreign "atg_cos_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_cosh = foreign "atg_cosh" (gc_tensor @-> returning raw_tensor)
  let stubs_cosh_ = foreign "atg_cosh_" (gc_tensor @-> returning raw_tensor)

  let stubs_cosh_out =
    foreign "atg_cosh_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_cosine_embedding_loss =
    foreign
      "atg_cosine_embedding_loss"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_cosine_similarity =
    foreign
      "atg_cosine_similarity"
      (gc_tensor @-> gc_tensor @-> int64_t @-> double @-> returning raw_tensor)
  ;;

  let stubs_count_nonzero =
    foreign
      "atg_count_nonzero"
      (gc_tensor @-> gc_tensor @-> ptr int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_count_nonzero_out =
    foreign
      "atg_count_nonzero_out"
      (gc_tensor @-> gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_cov =
    foreign
      "atg_cov"
      (gc_tensor @-> int64_t @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_cross =
    foreign
      "atg_cross"
      (gc_tensor @-> gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_cross_entropy_loss =
    foreign
      "atg_cross_entropy_loss"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> double
       @-> returning raw_tensor)
  ;;

  let stubs_cross_out =
    foreign
      "atg_cross_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_crow_indices = foreign "atg_crow_indices" (gc_tensor @-> returning raw_tensor)

  let stubs_crow_indices_copy =
    foreign "atg_crow_indices_copy" (gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_crow_indices_copy_out =
    foreign "atg_crow_indices_copy_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_ctc_loss =
    foreign
      "atg_ctc_loss"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_ctc_loss_tensor =
    foreign
      "atg_ctc_loss_tensor"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_cudnn_affine_grid_generator =
    foreign
      "atg_cudnn_affine_grid_generator"
      (gc_tensor @-> int64_t @-> int64_t @-> int64_t @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_cudnn_affine_grid_generator_backward =
    foreign
      "atg_cudnn_affine_grid_generator_backward"
      (gc_tensor @-> int64_t @-> int64_t @-> int64_t @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_cudnn_affine_grid_generator_backward_out =
    foreign
      "atg_cudnn_affine_grid_generator_backward_out"
      (gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_cudnn_affine_grid_generator_out =
    foreign
      "atg_cudnn_affine_grid_generator_out"
      (gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_cudnn_batch_norm =
    foreign
      "atg_cudnn_batch_norm"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> double
       @-> double
       @-> returning void)
  ;;

  let stubs_cudnn_batch_norm_backward =
    foreign
      "atg_cudnn_batch_norm_backward"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs_cudnn_batch_norm_backward_out =
    foreign
      "atg_cudnn_batch_norm_backward_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> double
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs_cudnn_batch_norm_out =
    foreign
      "atg_cudnn_batch_norm_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int
       @-> double
       @-> double
       @-> returning void)
  ;;

  let stubs_cudnn_convolution =
    foreign
      "atg_cudnn_convolution"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_cudnn_convolution_add_relu =
    foreign
      "atg_cudnn_convolution_add_relu"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> scalar
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_cudnn_convolution_add_relu_out =
    foreign
      "atg_cudnn_convolution_add_relu_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> scalar
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_cudnn_convolution_out =
    foreign
      "atg_cudnn_convolution_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_cudnn_convolution_relu =
    foreign
      "atg_cudnn_convolution_relu"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_cudnn_convolution_relu_out =
    foreign
      "atg_cudnn_convolution_relu_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_cudnn_convolution_transpose =
    foreign
      "atg_cudnn_convolution_transpose"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_cudnn_convolution_transpose_out =
    foreign
      "atg_cudnn_convolution_transpose_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> int
       @-> int
       @-> int
       @-> returning raw_tensor)
  ;;

  let stubs_cudnn_grid_sampler =
    foreign "atg_cudnn_grid_sampler" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_cudnn_grid_sampler_backward =
    foreign
      "atg_cudnn_grid_sampler_backward"
      (ptr raw_tensor @-> gc_tensor @-> gc_tensor @-> gc_tensor @-> returning void)
  ;;

  let stubs_cudnn_grid_sampler_backward_out =
    foreign
      "atg_cudnn_grid_sampler_backward_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> returning void)
  ;;

  let stubs_cudnn_grid_sampler_out =
    foreign
      "atg_cudnn_grid_sampler_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_cudnn_is_acceptable =
    foreign "atg_cudnn_is_acceptable" (gc_tensor @-> returning bool)
  ;;

  let stubs_cummax =
    foreign "atg_cummax" (ptr raw_tensor @-> gc_tensor @-> int64_t @-> returning void)
  ;;

  let stubs_cummax_out =
    foreign
      "atg_cummax_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> returning void)
  ;;

  let stubs_cummaxmin_backward =
    foreign
      "atg_cummaxmin_backward"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_cummin =
    foreign "atg_cummin" (ptr raw_tensor @-> gc_tensor @-> int64_t @-> returning void)
  ;;

  let stubs_cummin_out =
    foreign
      "atg_cummin_out"
      (ptr raw_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> returning void)
  ;;

  let stubs_cumprod =
    foreign "atg_cumprod" (gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_cumprod_ =
    foreign "atg_cumprod_" (gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_cumprod_backward =
    foreign
      "atg_cumprod_backward"
      (gc_tensor @-> gc_tensor @-> int64_t @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_cumprod_out =
    foreign
      "atg_cumprod_out"
      (gc_tensor @-> gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_cumsum =
    foreign "atg_cumsum" (gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_cumsum_ =
    foreign "atg_cumsum_" (gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_cumsum_out =
    foreign
      "atg_cumsum_out"
      (gc_tensor @-> gc_tensor @-> int64_t @-> int @-> returning raw_tensor)
  ;;

  let stubs_cumulative_trapezoid =
    foreign
      "atg_cumulative_trapezoid"
      (gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_cumulative_trapezoid_dx =
    foreign
      "atg_cumulative_trapezoid_dx"
      (gc_tensor @-> scalar @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_data = foreign "atg_data" (gc_tensor @-> returning raw_tensor)
  let stubs_deg2rad = foreign "atg_deg2rad" (gc_tensor @-> returning raw_tensor)
  let stubs_deg2rad_ = foreign "atg_deg2rad_" (gc_tensor @-> returning raw_tensor)

  let stubs_deg2rad_out =
    foreign "atg_deg2rad_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_dense_dim = foreign "atg_dense_dim" (gc_tensor @-> returning int64_t)
  let stubs_dequantize = foreign "atg_dequantize" (gc_tensor @-> returning raw_tensor)

  let stubs_dequantize_self_out =
    foreign "atg_dequantize_self_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_dequantize_tensors =
    foreign "atg_dequantize_tensors" (ptr gc_tensor @-> int @-> returning (ptr raw_tensor))
  ;;

  let stubs_dequantize_tensors_out =
    foreign
      "atg_dequantize_tensors_out"
      (ptr gc_tensor @-> int @-> ptr gc_tensor @-> int @-> returning void)
  ;;

  let stubs_det = foreign "atg_det" (gc_tensor @-> returning raw_tensor)
  let stubs_detach = foreign "atg_detach" (gc_tensor @-> returning raw_tensor)
  let stubs_detach_ = foreign "atg_detach_" (gc_tensor @-> returning raw_tensor)
  let stubs_detach_copy = foreign "atg_detach_copy" (gc_tensor @-> returning raw_tensor)

  let stubs_detach_copy_out =
    foreign "atg_detach_copy_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_diag = foreign "atg_diag" (gc_tensor @-> int64_t @-> returning raw_tensor)

  let stubs_diag_embed =
    foreign
      "atg_diag_embed"
      (gc_tensor @-> int64_t @-> int64_t @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_diag_embed_out =
    foreign
      "atg_diag_embed_out"
      (gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_diag_out =
    foreign "atg_diag_out" (gc_tensor @-> gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_diagflat =
    foreign "atg_diagflat" (gc_tensor @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_diagonal =
    foreign
      "atg_diagonal"
      (gc_tensor @-> int64_t @-> int64_t @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_diagonal_backward =
    foreign
      "atg_diagonal_backward"
      (gc_tensor
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_diagonal_backward_out =
    foreign
      "atg_diagonal_backward_out"
      (gc_tensor
       @-> gc_tensor
       @-> ptr int64_t
       @-> int
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_diagonal_copy =
    foreign
      "atg_diagonal_copy"
      (gc_tensor @-> int64_t @-> int64_t @-> int64_t @-> returning raw_tensor)
  ;;

  let stubs_diagonal_copy_out =
    foreign
      "atg_diagonal_copy_out"
      (gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_diagonal_scatter =
    foreign
      "atg_diagonal_scatter"
      (gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_diagonal_scatter_out =
    foreign
      "atg_diagonal_scatter_out"
      (gc_tensor
       @-> gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> int64_t
       @-> returning raw_tensor)
  ;;

  let stubs_diff =
    foreign
      "atg_diff"
      (gc_tensor
       @-> int64_t
       @-> int64_t
       @-> gc_tensor
       @-> gc_tensor
       @-> returning raw_tensor)
  ;;
end

module C3 (F : Cstubs.FOREIGN) = struct
  open F
  open Type_defs

  let stubs_diff_out =
    foreign
      "atg_diff_out"
      (gc_tensor
       @-> gc_tensor
       @-> int64_t
       @-> int64_t
       @-> gc_tensor
       @-> gc_tensor
       @-> returning raw_tensor)
  ;;

  let stubs_digamma = foreign "atg_digamma" (gc_tensor @-> returning raw_tensor)
  let stubs_digamma_ = foreign "atg_digamma_" (gc_tensor @-> returning raw_tensor)

  let stubs_digamma_out =
    foreign "atg_digamma_out" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_dist =
    foreign "atg_dist" (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_dist_out =
    foreign
      "atg_dist_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_div = foreign "atg_div" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  let stubs_div_ = foreign "atg_div_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)

  let stubs_div_out =
    foreign "atg_div_out" (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_div_out_mode =
    foreign
      "atg_div_out_mode"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> string @-> int @-> returning raw_tensor)
  ;;

  let stubs_div_scalar =
    foreign "atg_div_scalar" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_div_scalar_ =
    foreign "atg_div_scalar_" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_div_scalar_mode =
    foreign
      "atg_div_scalar_mode"
      (gc_tensor @-> scalar @-> string @-> int @-> returning raw_tensor)
  ;;

  let stubs_div_scalar_mode_ =
    foreign
      "atg_div_scalar_mode_"
      (gc_tensor @-> scalar @-> string @-> int @-> returning raw_tensor)
  ;;

  let stubs_div_scalar_mode_out =
    foreign
      "atg_div_scalar_mode_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> string @-> int @-> returning raw_tensor)
  ;;

  let stubs_div_scalar_out =
    foreign
      "atg_div_scalar_out"
      (gc_tensor @-> gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_div_tensor_mode =
    foreign
      "atg_div_tensor_mode"
      (gc_tensor @-> gc_tensor @-> string @-> int @-> returning raw_tensor)
  ;;

  let stubs_div_tensor_mode_ =
    foreign
      "atg_div_tensor_mode_"
      (gc_tensor @-> gc_tensor @-> string @-> int @-> returning raw_tensor)
  ;;

  let stubs_divide =
    foreign "atg_divide" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_divide_ =
    foreign "atg_divide_" (gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_divide_out =
    foreign
      "atg_divide_out"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> returning raw_tensor)
  ;;

  let stubs_divide_out_mode =
    foreign
      "atg_divide_out_mode"
      (gc_tensor @-> gc_tensor @-> gc_tensor @-> string @-> int @-> returning raw_tensor)
  ;;

  let stubs_divide_scalar =
    foreign "atg_divide_scalar" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_divide_scalar_ =
    foreign "atg_divide_scalar_" (gc_tensor @-> scalar @-> returning raw_tensor)
  ;;

  let stubs_divide_scalar_mode =
    foreign
      "atg_divide_scalar_mode"
      (gc_tensor @-> scalar @-> string @-> int @-> returning raw_tensor)
  ;;

  let stubs_divide_scalar_mode_ =
    foreign
      "atg_divide_scalar_mode_"
      (gc_tensor @-> scalar @-> string @-> int @-> returning raw_tensor)
  ;;

  let stubs_divide_tensor_mode =
    foreign
      "atg_divide_tensor_mode"
      (gc_tensor @-> gc_tensor @-> string @-> int @-> returning raw_tensor)
  ;;

  let stubs_divide_tensor_mode_ =
    foreign
      "atg_divide_tensor_mode_"
      (gc_tensor @-> gc_tensor @-> string @-> int @-> returning raw_tensor)
  ;;
end

module C (F : Cstubs.FOREIGN) = struct
  include C0 (F)
  include C1 (F)
  include C2 (F)
  include C3 (F)
end
