(* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT BY HAND! *)

open Ctypes
open Torch_bindings.Type_defs
open Torch_stubs
open Torch_wrapper_types
open Wrapper_utils
open C.Generated

let reflection_pad3d_backward ~grad_output self ~padding =
  stubs_reflection_pad3d_backward
    grad_output
    self
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
  |> with_tensor_gc
;;

let reflection_pad3d_backward_grad_input ~grad_input ~grad_output self ~padding =
  stubs_reflection_pad3d_backward_grad_input
    grad_input
    grad_output
    self
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
  |> with_tensor_gc
;;

let reflection_pad3d_out ~out self ~padding =
  stubs_reflection_pad3d_out
    out
    self
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
  |> with_tensor_gc
;;

let relu self = stubs_relu self |> with_tensor_gc
let relu6 self = stubs_relu6 self |> with_tensor_gc
let relu6_ self = stubs_relu6_ self |> with_tensor_gc
let relu_ self = stubs_relu_ self |> with_tensor_gc
let relu_out ~out self = stubs_relu_out out self |> with_tensor_gc
let remainder self other = stubs_remainder self other |> with_tensor_gc
let remainder_ self other = stubs_remainder_ self other |> with_tensor_gc

let remainder_scalar_out ~out self other =
  stubs_remainder_scalar_out out self other |> with_tensor_gc
;;

let remainder_scalar_tensor self other =
  stubs_remainder_scalar_tensor self other |> with_tensor_gc
;;

let remainder_scalar_tensor_out ~out self other =
  stubs_remainder_scalar_tensor_out out self other |> with_tensor_gc
;;

let remainder_tensor self other = stubs_remainder_tensor self other |> with_tensor_gc
let remainder_tensor_ self other = stubs_remainder_tensor_ self other |> with_tensor_gc

let remainder_tensor_out ~out self other =
  stubs_remainder_tensor_out out self other |> with_tensor_gc
;;

let renorm self ~p ~dim ~maxnorm =
  stubs_renorm self p (Int64.of_int dim) maxnorm |> with_tensor_gc
;;

let renorm_ self ~p ~dim ~maxnorm =
  stubs_renorm_ self p (Int64.of_int dim) maxnorm |> with_tensor_gc
;;

let renorm_out ~out self ~p ~dim ~maxnorm =
  stubs_renorm_out out self p (Int64.of_int dim) maxnorm |> with_tensor_gc
;;

let repeat self ~repeats =
  stubs_repeat
    self
    (List.map Int64.of_int repeats |> CArray.of_list int64_t |> CArray.start)
    (List.length repeats)
  |> with_tensor_gc
;;

let repeat_interleave ~repeats ~output_size =
  stubs_repeat_interleave
    repeats
    (match output_size with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match output_size with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let repeat_interleave_self_int self ~repeats ~dim ~output_size =
  stubs_repeat_interleave_self_int
    self
    (Int64.of_int repeats)
    (match dim with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match dim with
     | Some _ -> 0
     | None -> 1)
    (match output_size with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match output_size with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let repeat_interleave_self_tensor self ~repeats ~dim ~output_size =
  stubs_repeat_interleave_self_tensor
    self
    repeats
    (match dim with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match dim with
     | Some _ -> 0
     | None -> 1)
    (match output_size with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match output_size with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let repeat_interleave_tensor_out ~out ~repeats ~output_size =
  stubs_repeat_interleave_tensor_out
    out
    repeats
    (match output_size with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match output_size with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let repeat_out ~out self ~repeats =
  stubs_repeat_out
    out
    self
    (List.map Int64.of_int repeats |> CArray.of_list int64_t |> CArray.start)
    (List.length repeats)
  |> with_tensor_gc
;;

let replication_pad1d self ~padding =
  stubs_replication_pad1d
    self
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
  |> with_tensor_gc
;;

let replication_pad1d_backward ~grad_output self ~padding =
  stubs_replication_pad1d_backward
    grad_output
    self
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
  |> with_tensor_gc
;;

let replication_pad1d_backward_grad_input ~grad_input ~grad_output self ~padding =
  stubs_replication_pad1d_backward_grad_input
    grad_input
    grad_output
    self
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
  |> with_tensor_gc
;;

let replication_pad1d_out ~out self ~padding =
  stubs_replication_pad1d_out
    out
    self
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
  |> with_tensor_gc
;;

let replication_pad2d self ~padding =
  stubs_replication_pad2d
    self
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
  |> with_tensor_gc
;;

let replication_pad2d_backward ~grad_output self ~padding =
  stubs_replication_pad2d_backward
    grad_output
    self
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
  |> with_tensor_gc
;;

let replication_pad2d_backward_grad_input ~grad_input ~grad_output self ~padding =
  stubs_replication_pad2d_backward_grad_input
    grad_input
    grad_output
    self
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
  |> with_tensor_gc
;;

let replication_pad2d_out ~out self ~padding =
  stubs_replication_pad2d_out
    out
    self
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
  |> with_tensor_gc
;;

let replication_pad3d self ~padding =
  stubs_replication_pad3d
    self
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
  |> with_tensor_gc
;;

let replication_pad3d_backward ~grad_output self ~padding =
  stubs_replication_pad3d_backward
    grad_output
    self
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
  |> with_tensor_gc
;;

let replication_pad3d_backward_grad_input ~grad_input ~grad_output self ~padding =
  stubs_replication_pad3d_backward_grad_input
    grad_input
    grad_output
    self
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
  |> with_tensor_gc
;;

let replication_pad3d_out ~out self ~padding =
  stubs_replication_pad3d_out
    out
    self
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
  |> with_tensor_gc
;;

let requires_grad_ self ~requires_grad =
  stubs_requires_grad_ self (if requires_grad then 1 else 0) |> with_tensor_gc
;;

let reshape self ~shape =
  stubs_reshape
    self
    (List.map Int64.of_int shape |> CArray.of_list int64_t |> CArray.start)
    (List.length shape)
  |> with_tensor_gc
;;

let reshape_as self other = stubs_reshape_as self other |> with_tensor_gc

let resize self ~size =
  stubs_resize
    self
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
  |> with_tensor_gc
;;

let resize_ self ~size =
  stubs_resize_
    self
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
  |> with_tensor_gc
;;

let resize_as self ~the_template = stubs_resize_as self the_template |> with_tensor_gc
let resize_as_ self ~the_template = stubs_resize_as_ self the_template |> with_tensor_gc

let resize_as_out ~out self ~the_template =
  stubs_resize_as_out out self the_template |> with_tensor_gc
;;

let resize_as_sparse self ~the_template =
  stubs_resize_as_sparse self the_template |> with_tensor_gc
;;

let resize_as_sparse_ self ~the_template =
  stubs_resize_as_sparse_ self the_template |> with_tensor_gc
;;

let resize_as_sparse_out ~out self ~the_template =
  stubs_resize_as_sparse_out out self the_template |> with_tensor_gc
;;

let resize_out ~out self ~size =
  stubs_resize_out
    out
    self
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
  |> with_tensor_gc
;;

let resolve_conj self = stubs_resolve_conj self |> with_tensor_gc
let resolve_neg self = stubs_resolve_neg self |> with_tensor_gc
let retains_grad self = stubs_retains_grad self

let rms_norm input ~normalized_shape ~weight ~eps =
  stubs_rms_norm
    input
    (List.map Int64.of_int normalized_shape |> CArray.of_list int64_t |> CArray.start)
    (List.length normalized_shape)
    (match weight with
     | Some v -> v
     | None -> none_gc_tensor)
    (Option.value eps ~default:0.0)
    (match eps with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let rnn_relu
  input
  ~hx
  ~params
  ~has_biases
  ~num_layers
  ~dropout
  ~train
  ~bidirectional
  ~batch_first
  =
  let out__ = CArray.make raw_tensor 2 in
  stubs_rnn_relu
    (CArray.start out__)
    input
    hx
    (CArray.of_list gc_tensor params |> CArray.start)
    (List.length params)
    (if has_biases then 1 else 0)
    (Int64.of_int num_layers)
    dropout
    (if train then 1 else 0)
    (if bidirectional then 1 else 0)
    (if batch_first then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  keep_values_alive params;
  t0, t1
;;

let rnn_relu_cell input ~hx ~w_ih ~w_hh ~b_ih ~b_hh =
  stubs_rnn_relu_cell
    input
    hx
    w_ih
    w_hh
    (match b_ih with
     | Some v -> v
     | None -> none_gc_tensor)
    (match b_hh with
     | Some v -> v
     | None -> none_gc_tensor)
  |> with_tensor_gc
;;

let rnn_relu_data
  ~data
  ~batch_sizes
  ~hx
  ~params
  ~has_biases
  ~num_layers
  ~dropout
  ~train
  ~bidirectional
  =
  let out__ = CArray.make raw_tensor 2 in
  stubs_rnn_relu_data
    (CArray.start out__)
    data
    batch_sizes
    hx
    (CArray.of_list gc_tensor params |> CArray.start)
    (List.length params)
    (if has_biases then 1 else 0)
    (Int64.of_int num_layers)
    dropout
    (if train then 1 else 0)
    (if bidirectional then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  keep_values_alive params;
  t0, t1
;;

let rnn_tanh
  input
  ~hx
  ~params
  ~has_biases
  ~num_layers
  ~dropout
  ~train
  ~bidirectional
  ~batch_first
  =
  let out__ = CArray.make raw_tensor 2 in
  stubs_rnn_tanh
    (CArray.start out__)
    input
    hx
    (CArray.of_list gc_tensor params |> CArray.start)
    (List.length params)
    (if has_biases then 1 else 0)
    (Int64.of_int num_layers)
    dropout
    (if train then 1 else 0)
    (if bidirectional then 1 else 0)
    (if batch_first then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  keep_values_alive params;
  t0, t1
;;

let rnn_tanh_cell input ~hx ~w_ih ~w_hh ~b_ih ~b_hh =
  stubs_rnn_tanh_cell
    input
    hx
    w_ih
    w_hh
    (match b_ih with
     | Some v -> v
     | None -> none_gc_tensor)
    (match b_hh with
     | Some v -> v
     | None -> none_gc_tensor)
  |> with_tensor_gc
;;

let rnn_tanh_data
  ~data
  ~batch_sizes
  ~hx
  ~params
  ~has_biases
  ~num_layers
  ~dropout
  ~train
  ~bidirectional
  =
  let out__ = CArray.make raw_tensor 2 in
  stubs_rnn_tanh_data
    (CArray.start out__)
    data
    batch_sizes
    hx
    (CArray.of_list gc_tensor params |> CArray.start)
    (List.length params)
    (if has_biases then 1 else 0)
    (Int64.of_int num_layers)
    dropout
    (if train then 1 else 0)
    (if bidirectional then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  keep_values_alive params;
  t0, t1
;;

let roll self ~shifts ~dims =
  stubs_roll
    self
    (List.map Int64.of_int shifts |> CArray.of_list int64_t |> CArray.start)
    (List.length shifts)
    (List.map Int64.of_int dims |> CArray.of_list int64_t |> CArray.start)
    (List.length dims)
  |> with_tensor_gc
;;

let roll_out ~out self ~shifts ~dims =
  stubs_roll_out
    out
    self
    (List.map Int64.of_int shifts |> CArray.of_list int64_t |> CArray.start)
    (List.length shifts)
    (List.map Int64.of_int dims |> CArray.of_list int64_t |> CArray.start)
    (List.length dims)
  |> with_tensor_gc
;;

let rot90 self ~k ~dims =
  stubs_rot90
    self
    (Int64.of_int k)
    (List.map Int64.of_int dims |> CArray.of_list int64_t |> CArray.start)
    (List.length dims)
  |> with_tensor_gc
;;

let rot90_out ~out self ~k ~dims =
  stubs_rot90_out
    out
    self
    (Int64.of_int k)
    (List.map Int64.of_int dims |> CArray.of_list int64_t |> CArray.start)
    (List.length dims)
  |> with_tensor_gc
;;

let round self = stubs_round self |> with_tensor_gc
let round_ self = stubs_round_ self |> with_tensor_gc

let round_decimals self ~decimals =
  stubs_round_decimals self (Int64.of_int decimals) |> with_tensor_gc
;;

let round_decimals_ self ~decimals =
  stubs_round_decimals_ self (Int64.of_int decimals) |> with_tensor_gc
;;

let round_decimals_out ~out self ~decimals =
  stubs_round_decimals_out out self (Int64.of_int decimals) |> with_tensor_gc
;;

let round_out ~out self = stubs_round_out out self |> with_tensor_gc
let row_indices self = stubs_row_indices self |> with_tensor_gc
let row_indices_copy self = stubs_row_indices_copy self |> with_tensor_gc
let row_indices_copy_out ~out self = stubs_row_indices_copy_out out self |> with_tensor_gc

let row_stack tensors =
  let result =
    stubs_row_stack
      (CArray.of_list gc_tensor tensors |> CArray.start)
      (List.length tensors)
    |> with_tensor_gc
  in
  keep_values_alive tensors;
  result
;;

let row_stack_out ~out tensors =
  let result =
    stubs_row_stack_out
      out
      (CArray.of_list gc_tensor tensors |> CArray.start)
      (List.length tensors)
    |> with_tensor_gc
  in
  keep_values_alive tensors;
  result
;;

let rrelu ?lower ?upper self ~training =
  stubs_rrelu
    self
    (match lower with
     | Some v -> v
     | None -> none_scalar)
    (match upper with
     | Some v -> v
     | None -> none_scalar)
    (if training then 1 else 0)
  |> with_tensor_gc
;;

let rrelu_ ?lower ?upper self ~training =
  stubs_rrelu_
    self
    (match lower with
     | Some v -> v
     | None -> none_scalar)
    (match upper with
     | Some v -> v
     | None -> none_scalar)
    (if training then 1 else 0)
  |> with_tensor_gc
;;

let rrelu_with_noise ?lower ?upper self ~noise ~training =
  stubs_rrelu_with_noise
    self
    noise
    (match lower with
     | Some v -> v
     | None -> none_scalar)
    (match upper with
     | Some v -> v
     | None -> none_scalar)
    (if training then 1 else 0)
  |> with_tensor_gc
;;

let rrelu_with_noise_ ?lower ?upper self ~noise ~training =
  stubs_rrelu_with_noise_
    self
    noise
    (match lower with
     | Some v -> v
     | None -> none_scalar)
    (match upper with
     | Some v -> v
     | None -> none_scalar)
    (if training then 1 else 0)
  |> with_tensor_gc
;;

let rrelu_with_noise_backward
  ~grad_output
  self
  ~noise
  ~lower
  ~upper
  ~training
  ~self_is_result
  =
  stubs_rrelu_with_noise_backward
    grad_output
    self
    noise
    lower
    upper
    (if training then 1 else 0)
    (if self_is_result then 1 else 0)
  |> with_tensor_gc
;;

let rrelu_with_noise_backward_out
  ~out
  ~grad_output
  self
  ~noise
  ~lower
  ~upper
  ~training
  ~self_is_result
  =
  stubs_rrelu_with_noise_backward_out
    out
    grad_output
    self
    noise
    lower
    upper
    (if training then 1 else 0)
    (if self_is_result then 1 else 0)
  |> with_tensor_gc
;;

let rrelu_with_noise_functional ?lower ?upper self ~noise ~training =
  let out__ = CArray.make raw_tensor 2 in
  stubs_rrelu_with_noise_functional
    (CArray.start out__)
    self
    noise
    (match lower with
     | Some v -> v
     | None -> none_scalar)
    (match upper with
     | Some v -> v
     | None -> none_scalar)
    (if training then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  t0, t1
;;

let rrelu_with_noise_out ?lower ?upper ~out self ~noise ~training =
  stubs_rrelu_with_noise_out
    out
    self
    noise
    (match lower with
     | Some v -> v
     | None -> none_scalar)
    (match upper with
     | Some v -> v
     | None -> none_scalar)
    (if training then 1 else 0)
  |> with_tensor_gc
;;

let rsqrt self = stubs_rsqrt self |> with_tensor_gc
let rsqrt_ self = stubs_rsqrt_ self |> with_tensor_gc
let rsqrt_out ~out self = stubs_rsqrt_out out self |> with_tensor_gc

let rsub ?alpha self other =
  stubs_rsub
    self
    other
    (match alpha with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let rsub_scalar ?alpha self other =
  stubs_rsub_scalar
    self
    other
    (match alpha with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let rsub_scalar_out ?alpha ~out self other =
  stubs_rsub_scalar_out
    out
    self
    other
    (match alpha with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let rsub_tensor_out ?alpha ~out self other =
  stubs_rsub_tensor_out
    out
    self
    other
    (match alpha with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let scalar_tensor ~s ~options =
  stubs_scalar_tensor s (Kind.packed_to_int (fst options)) (Device.to_int (snd options))
  |> with_tensor_gc
;;

let scalar_tensor_out ~out ~s = stubs_scalar_tensor_out out s |> with_tensor_gc

let scaled_dot_product_attention
  ~query
  ~key
  ~value
  ~attn_mask
  ~dropout_p
  ~is_causal
  ~scale
  ~enable_gqa
  =
  stubs_scaled_dot_product_attention
    query
    key
    value
    (match attn_mask with
     | Some v -> v
     | None -> none_gc_tensor)
    dropout_p
    (if is_causal then 1 else 0)
    (Option.value scale ~default:0.0)
    (match scale with
     | Some _ -> 0
     | None -> 1)
    (if enable_gqa then 1 else 0)
  |> with_tensor_gc
;;

let scatter self ~dim ~index ~src =
  stubs_scatter self (Int64.of_int dim) index src |> with_tensor_gc
;;

let scatter_ self ~dim ~index ~src =
  stubs_scatter_ self (Int64.of_int dim) index src |> with_tensor_gc
;;

let scatter_add self ~dim ~index ~src =
  stubs_scatter_add self (Int64.of_int dim) index src |> with_tensor_gc
;;

let scatter_add_ self ~dim ~index ~src =
  stubs_scatter_add_ self (Int64.of_int dim) index src |> with_tensor_gc
;;

let scatter_add_out ~out self ~dim ~index ~src =
  stubs_scatter_add_out out self (Int64.of_int dim) index src |> with_tensor_gc
;;

let scatter_reduce self ~dim ~index ~src ~reduce =
  stubs_scatter_reduce self (Int64.of_int dim) index src reduce |> with_tensor_gc
;;

let scatter_reduce_ self ~dim ~index ~src ~reduce =
  stubs_scatter_reduce_ self (Int64.of_int dim) index src reduce |> with_tensor_gc
;;

let scatter_reduce_out ~out self ~dim ~index ~src ~reduce =
  stubs_scatter_reduce_out out self (Int64.of_int dim) index src reduce |> with_tensor_gc
;;

let scatter_src_out ~out self ~dim ~index ~src =
  stubs_scatter_src_out out self (Int64.of_int dim) index src |> with_tensor_gc
;;

let scatter_value self ~dim ~index ~value =
  stubs_scatter_value self (Int64.of_int dim) index value |> with_tensor_gc
;;

let scatter_value_ self ~dim ~index ~value =
  stubs_scatter_value_ self (Int64.of_int dim) index value |> with_tensor_gc
;;

let scatter_value_out ~out self ~dim ~index ~value =
  stubs_scatter_value_out out self (Int64.of_int dim) index value |> with_tensor_gc
;;

let scatter_value_reduce self ~dim ~index ~value ~reduce =
  stubs_scatter_value_reduce self (Int64.of_int dim) index value reduce |> with_tensor_gc
;;

let scatter_value_reduce_ self ~dim ~index ~value ~reduce =
  stubs_scatter_value_reduce_ self (Int64.of_int dim) index value reduce |> with_tensor_gc
;;

let scatter_value_reduce_out ~out self ~dim ~index ~value ~reduce =
  stubs_scatter_value_reduce_out out self (Int64.of_int dim) index value reduce
  |> with_tensor_gc
;;

let searchsorted ~sorted_sequence self ~out_int32 ~right ~side ~sorter =
  stubs_searchsorted
    sorted_sequence
    self
    (if out_int32 then 1 else 0)
    (if right then 1 else 0)
    (Option.value side ~default:"")
    (match side with
     | Some _ -> 0
     | None -> 1)
    (match sorter with
     | Some v -> v
     | None -> none_gc_tensor)
  |> with_tensor_gc
;;

let searchsorted_scalar ~sorted_sequence self ~out_int32 ~right ~side ~sorter =
  stubs_searchsorted_scalar
    sorted_sequence
    self
    (if out_int32 then 1 else 0)
    (if right then 1 else 0)
    (Option.value side ~default:"")
    (match side with
     | Some _ -> 0
     | None -> 1)
    (match sorter with
     | Some v -> v
     | None -> none_gc_tensor)
  |> with_tensor_gc
;;

let searchsorted_scalar_out ~out ~sorted_sequence self ~out_int32 ~right ~side ~sorter =
  stubs_searchsorted_scalar_out
    out
    sorted_sequence
    self
    (if out_int32 then 1 else 0)
    (if right then 1 else 0)
    (Option.value side ~default:"")
    (match side with
     | Some _ -> 0
     | None -> 1)
    (match sorter with
     | Some v -> v
     | None -> none_gc_tensor)
  |> with_tensor_gc
;;

let searchsorted_tensor_out ~out ~sorted_sequence self ~out_int32 ~right ~side ~sorter =
  stubs_searchsorted_tensor_out
    out
    sorted_sequence
    self
    (if out_int32 then 1 else 0)
    (if right then 1 else 0)
    (Option.value side ~default:"")
    (match side with
     | Some _ -> 0
     | None -> 1)
    (match sorter with
     | Some v -> v
     | None -> none_gc_tensor)
  |> with_tensor_gc
;;

let segment_reduce ~data ~reduce ~lengths ~indices ~offsets ~axis ~unsafe ~initial =
  stubs_segment_reduce
    data
    reduce
    (match lengths with
     | Some v -> v
     | None -> none_gc_tensor)
    (match indices with
     | Some v -> v
     | None -> none_gc_tensor)
    (match offsets with
     | Some v -> v
     | None -> none_gc_tensor)
    (Int64.of_int axis)
    (if unsafe then 1 else 0)
    initial
  |> with_tensor_gc
;;

let segment_reduce_out
  ~out
  ~data
  ~reduce
  ~lengths
  ~indices
  ~offsets
  ~axis
  ~unsafe
  ~initial
  =
  stubs_segment_reduce_out
    out
    data
    reduce
    (match lengths with
     | Some v -> v
     | None -> none_gc_tensor)
    (match indices with
     | Some v -> v
     | None -> none_gc_tensor)
    (match offsets with
     | Some v -> v
     | None -> none_gc_tensor)
    (Int64.of_int axis)
    (if unsafe then 1 else 0)
    initial
  |> with_tensor_gc
;;

let select self ~dim ~index =
  stubs_select self (Int64.of_int dim) (Int64.of_int index) |> with_tensor_gc
;;

let select_backward ~grad_output ~input_sizes ~dim ~index =
  stubs_select_backward
    grad_output
    (List.map Int64.of_int input_sizes |> CArray.of_list int64_t |> CArray.start)
    (List.length input_sizes)
    (Int64.of_int dim)
    (Int64.of_int index)
  |> with_tensor_gc
;;

let select_backward_out ~out ~grad_output ~input_sizes ~dim ~index =
  stubs_select_backward_out
    out
    grad_output
    (List.map Int64.of_int input_sizes |> CArray.of_list int64_t |> CArray.start)
    (List.length input_sizes)
    (Int64.of_int dim)
    (Int64.of_int index)
  |> with_tensor_gc
;;

let select_copy self ~dim ~index =
  stubs_select_copy self (Int64.of_int dim) (Int64.of_int index) |> with_tensor_gc
;;

let select_copy_int_out ~out self ~dim ~index =
  stubs_select_copy_int_out out self (Int64.of_int dim) (Int64.of_int index)
  |> with_tensor_gc
;;

let select_scatter self ~src ~dim ~index =
  stubs_select_scatter self src (Int64.of_int dim) (Int64.of_int index) |> with_tensor_gc
;;

let select_scatter_out ~out self ~src ~dim ~index =
  stubs_select_scatter_out out self src (Int64.of_int dim) (Int64.of_int index)
  |> with_tensor_gc
;;

let selu self = stubs_selu self |> with_tensor_gc
let selu_ self = stubs_selu_ self |> with_tensor_gc
let set self = stubs_set self |> with_tensor_gc
let set_ self = stubs_set_ self |> with_tensor_gc
let set_out ~out self = stubs_set_out out self |> with_tensor_gc

let set_requires_grad self ~r =
  stubs_set_requires_grad self (if r then 1 else 0) |> with_tensor_gc
;;

let set_source_tensor self ~source = stubs_set_source_tensor self source |> with_tensor_gc

let set_source_tensor_ self ~source =
  stubs_set_source_tensor_ self source |> with_tensor_gc
;;

let set_source_tensor_out ~out self ~source =
  stubs_set_source_tensor_out out self source |> with_tensor_gc
;;

let set_source_tensor_storage_offset_ self ~source ~storage_offset ~size ~stride =
  stubs_set_source_tensor_storage_offset_
    self
    source
    (Int64.of_int storage_offset)
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
    (List.map Int64.of_int stride |> CArray.of_list int64_t |> CArray.start)
    (List.length stride)
  |> with_tensor_gc
;;

let sgn self = stubs_sgn self |> with_tensor_gc
let sgn_ self = stubs_sgn_ self |> with_tensor_gc
let sgn_out ~out self = stubs_sgn_out out self |> with_tensor_gc
let sigmoid self = stubs_sigmoid self |> with_tensor_gc
let sigmoid_ self = stubs_sigmoid_ self |> with_tensor_gc

let sigmoid_backward ~grad_output ~output =
  stubs_sigmoid_backward grad_output output |> with_tensor_gc
;;

let sigmoid_backward_grad_input ~grad_input ~grad_output ~output =
  stubs_sigmoid_backward_grad_input grad_input grad_output output |> with_tensor_gc
;;

let sigmoid_out ~out self = stubs_sigmoid_out out self |> with_tensor_gc
let sign self = stubs_sign self |> with_tensor_gc
let sign_ self = stubs_sign_ self |> with_tensor_gc
let sign_out ~out self = stubs_sign_out out self |> with_tensor_gc
let signbit self = stubs_signbit self |> with_tensor_gc
let signbit_out ~out self = stubs_signbit_out out self |> with_tensor_gc
let silu self = stubs_silu self |> with_tensor_gc
let silu_ self = stubs_silu_ self |> with_tensor_gc

let silu_backward ~grad_output self =
  stubs_silu_backward grad_output self |> with_tensor_gc
;;

let silu_backward_grad_input ~grad_input ~grad_output self =
  stubs_silu_backward_grad_input grad_input grad_output self |> with_tensor_gc
;;

let silu_out ~out self = stubs_silu_out out self |> with_tensor_gc
let sin self = stubs_sin self |> with_tensor_gc
let sin_ self = stubs_sin_ self |> with_tensor_gc
let sin_out ~out self = stubs_sin_out out self |> with_tensor_gc
let sinc self = stubs_sinc self |> with_tensor_gc
let sinc_ self = stubs_sinc_ self |> with_tensor_gc
let sinc_out ~out self = stubs_sinc_out out self |> with_tensor_gc
let sinh self = stubs_sinh self |> with_tensor_gc
let sinh_ self = stubs_sinh_ self |> with_tensor_gc
let sinh_out ~out self = stubs_sinh_out out self |> with_tensor_gc
let size self ~dim = stubs_size self (Int64.of_int dim)

let slice self ~dim ~start ~end_ ~step =
  stubs_slice
    self
    (Int64.of_int dim)
    (match start with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match start with
     | Some _ -> 0
     | None -> 1)
    (match end_ with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match end_ with
     | Some _ -> 0
     | None -> 1)
    (Int64.of_int step)
  |> with_tensor_gc
;;

let slice_backward ~grad_output ~input_sizes ~dim ~start ~end_ ~step =
  stubs_slice_backward
    grad_output
    (List.map Int64.of_int input_sizes |> CArray.of_list int64_t |> CArray.start)
    (List.length input_sizes)
    (Int64.of_int dim)
    (Int64.of_int start)
    (Int64.of_int end_)
    (Int64.of_int step)
  |> with_tensor_gc
;;

let slice_backward_out ~out ~grad_output ~input_sizes ~dim ~start ~end_ ~step =
  stubs_slice_backward_out
    out
    grad_output
    (List.map Int64.of_int input_sizes |> CArray.of_list int64_t |> CArray.start)
    (List.length input_sizes)
    (Int64.of_int dim)
    (Int64.of_int start)
    (Int64.of_int end_)
    (Int64.of_int step)
  |> with_tensor_gc
;;

let slice_copy self ~dim ~start ~end_ ~step =
  stubs_slice_copy
    self
    (Int64.of_int dim)
    (match start with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match start with
     | Some _ -> 0
     | None -> 1)
    (match end_ with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match end_ with
     | Some _ -> 0
     | None -> 1)
    (Int64.of_int step)
  |> with_tensor_gc
;;

let slice_copy_tensor_out ~out self ~dim ~start ~end_ ~step =
  stubs_slice_copy_tensor_out
    out
    self
    (Int64.of_int dim)
    (match start with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match start with
     | Some _ -> 0
     | None -> 1)
    (match end_ with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match end_ with
     | Some _ -> 0
     | None -> 1)
    (Int64.of_int step)
  |> with_tensor_gc
;;

let slice_inverse self ~src ~dim ~start ~end_ ~step =
  stubs_slice_inverse
    self
    src
    (Int64.of_int dim)
    (match start with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match start with
     | Some _ -> 0
     | None -> 1)
    (match end_ with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match end_ with
     | Some _ -> 0
     | None -> 1)
    (Int64.of_int step)
  |> with_tensor_gc
;;

let slice_scatter self ~src ~dim ~start ~end_ ~step =
  stubs_slice_scatter
    self
    src
    (Int64.of_int dim)
    (match start with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match start with
     | Some _ -> 0
     | None -> 1)
    (match end_ with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match end_ with
     | Some _ -> 0
     | None -> 1)
    (Int64.of_int step)
  |> with_tensor_gc
;;

let slice_scatter_out ~out self ~src ~dim ~start ~end_ ~step =
  stubs_slice_scatter_out
    out
    self
    src
    (Int64.of_int dim)
    (match start with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match start with
     | Some _ -> 0
     | None -> 1)
    (match end_ with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match end_ with
     | Some _ -> 0
     | None -> 1)
    (Int64.of_int step)
  |> with_tensor_gc
;;

let slogdet self =
  let out__ = CArray.make raw_tensor 2 in
  stubs_slogdet (CArray.start out__) self;
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  t0, t1
;;

let slogdet_out ~sign ~logabsdet self =
  let out__ = CArray.make raw_tensor 2 in
  stubs_slogdet_out (CArray.start out__) sign logabsdet self;
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  t0, t1
;;

let slow_conv3d self ~weight ~kernel_size ~bias ~stride ~padding =
  stubs_slow_conv3d
    self
    weight
    (List.map Int64.of_int kernel_size |> CArray.of_list int64_t |> CArray.start)
    (List.length kernel_size)
    (match bias with
     | Some v -> v
     | None -> none_gc_tensor)
    (List.map Int64.of_int stride |> CArray.of_list int64_t |> CArray.start)
    (List.length stride)
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
  |> with_tensor_gc
;;

let slow_conv3d_out ~out self ~weight ~kernel_size ~bias ~stride ~padding =
  stubs_slow_conv3d_out
    out
    self
    weight
    (List.map Int64.of_int kernel_size |> CArray.of_list int64_t |> CArray.start)
    (List.length kernel_size)
    (match bias with
     | Some v -> v
     | None -> none_gc_tensor)
    (List.map Int64.of_int stride |> CArray.of_list int64_t |> CArray.start)
    (List.length stride)
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
  |> with_tensor_gc
;;

let slow_conv_dilated2d self ~weight ~kernel_size ~bias ~stride ~padding ~dilation =
  stubs_slow_conv_dilated2d
    self
    weight
    (List.map Int64.of_int kernel_size |> CArray.of_list int64_t |> CArray.start)
    (List.length kernel_size)
    (match bias with
     | Some v -> v
     | None -> none_gc_tensor)
    (List.map Int64.of_int stride |> CArray.of_list int64_t |> CArray.start)
    (List.length stride)
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
    (List.map Int64.of_int dilation |> CArray.of_list int64_t |> CArray.start)
    (List.length dilation)
  |> with_tensor_gc
;;

let slow_conv_dilated2d_out
  ~out
  self
  ~weight
  ~kernel_size
  ~bias
  ~stride
  ~padding
  ~dilation
  =
  stubs_slow_conv_dilated2d_out
    out
    self
    weight
    (List.map Int64.of_int kernel_size |> CArray.of_list int64_t |> CArray.start)
    (List.length kernel_size)
    (match bias with
     | Some v -> v
     | None -> none_gc_tensor)
    (List.map Int64.of_int stride |> CArray.of_list int64_t |> CArray.start)
    (List.length stride)
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
    (List.map Int64.of_int dilation |> CArray.of_list int64_t |> CArray.start)
    (List.length dilation)
  |> with_tensor_gc
;;

let slow_conv_dilated3d self ~weight ~kernel_size ~bias ~stride ~padding ~dilation =
  stubs_slow_conv_dilated3d
    self
    weight
    (List.map Int64.of_int kernel_size |> CArray.of_list int64_t |> CArray.start)
    (List.length kernel_size)
    (match bias with
     | Some v -> v
     | None -> none_gc_tensor)
    (List.map Int64.of_int stride |> CArray.of_list int64_t |> CArray.start)
    (List.length stride)
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
    (List.map Int64.of_int dilation |> CArray.of_list int64_t |> CArray.start)
    (List.length dilation)
  |> with_tensor_gc
;;

let slow_conv_dilated3d_out
  ~out
  self
  ~weight
  ~kernel_size
  ~bias
  ~stride
  ~padding
  ~dilation
  =
  stubs_slow_conv_dilated3d_out
    out
    self
    weight
    (List.map Int64.of_int kernel_size |> CArray.of_list int64_t |> CArray.start)
    (List.length kernel_size)
    (match bias with
     | Some v -> v
     | None -> none_gc_tensor)
    (List.map Int64.of_int stride |> CArray.of_list int64_t |> CArray.start)
    (List.length stride)
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
    (List.map Int64.of_int dilation |> CArray.of_list int64_t |> CArray.start)
    (List.length dilation)
  |> with_tensor_gc
;;

let slow_conv_transpose2d
  self
  ~weight
  ~kernel_size
  ~bias
  ~stride
  ~padding
  ~output_padding
  ~dilation
  =
  stubs_slow_conv_transpose2d
    self
    weight
    (List.map Int64.of_int kernel_size |> CArray.of_list int64_t |> CArray.start)
    (List.length kernel_size)
    (match bias with
     | Some v -> v
     | None -> none_gc_tensor)
    (List.map Int64.of_int stride |> CArray.of_list int64_t |> CArray.start)
    (List.length stride)
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
    (List.map Int64.of_int output_padding |> CArray.of_list int64_t |> CArray.start)
    (List.length output_padding)
    (List.map Int64.of_int dilation |> CArray.of_list int64_t |> CArray.start)
    (List.length dilation)
  |> with_tensor_gc
;;

let slow_conv_transpose2d_out
  ~out
  self
  ~weight
  ~kernel_size
  ~bias
  ~stride
  ~padding
  ~output_padding
  ~dilation
  =
  stubs_slow_conv_transpose2d_out
    out
    self
    weight
    (List.map Int64.of_int kernel_size |> CArray.of_list int64_t |> CArray.start)
    (List.length kernel_size)
    (match bias with
     | Some v -> v
     | None -> none_gc_tensor)
    (List.map Int64.of_int stride |> CArray.of_list int64_t |> CArray.start)
    (List.length stride)
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
    (List.map Int64.of_int output_padding |> CArray.of_list int64_t |> CArray.start)
    (List.length output_padding)
    (List.map Int64.of_int dilation |> CArray.of_list int64_t |> CArray.start)
    (List.length dilation)
  |> with_tensor_gc
;;

let slow_conv_transpose3d
  self
  ~weight
  ~kernel_size
  ~bias
  ~stride
  ~padding
  ~output_padding
  ~dilation
  =
  stubs_slow_conv_transpose3d
    self
    weight
    (List.map Int64.of_int kernel_size |> CArray.of_list int64_t |> CArray.start)
    (List.length kernel_size)
    (match bias with
     | Some v -> v
     | None -> none_gc_tensor)
    (List.map Int64.of_int stride |> CArray.of_list int64_t |> CArray.start)
    (List.length stride)
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
    (List.map Int64.of_int output_padding |> CArray.of_list int64_t |> CArray.start)
    (List.length output_padding)
    (List.map Int64.of_int dilation |> CArray.of_list int64_t |> CArray.start)
    (List.length dilation)
  |> with_tensor_gc
;;

let slow_conv_transpose3d_out
  ~out
  self
  ~weight
  ~kernel_size
  ~bias
  ~stride
  ~padding
  ~output_padding
  ~dilation
  =
  stubs_slow_conv_transpose3d_out
    out
    self
    weight
    (List.map Int64.of_int kernel_size |> CArray.of_list int64_t |> CArray.start)
    (List.length kernel_size)
    (match bias with
     | Some v -> v
     | None -> none_gc_tensor)
    (List.map Int64.of_int stride |> CArray.of_list int64_t |> CArray.start)
    (List.length stride)
    (List.map Int64.of_int padding |> CArray.of_list int64_t |> CArray.start)
    (List.length padding)
    (List.map Int64.of_int output_padding |> CArray.of_list int64_t |> CArray.start)
    (List.length output_padding)
    (List.map Int64.of_int dilation |> CArray.of_list int64_t |> CArray.start)
    (List.length dilation)
  |> with_tensor_gc
;;

let smm self ~mat2 = stubs_smm self mat2 |> with_tensor_gc

let smooth_l1_loss self ~target ~reduction ~beta =
  stubs_smooth_l1_loss self target (Reduction.to_int reduction |> Int64.of_int) beta
  |> with_tensor_gc
;;

let smooth_l1_loss_backward ~grad_output self ~target ~reduction ~beta =
  stubs_smooth_l1_loss_backward
    grad_output
    self
    target
    (Reduction.to_int reduction |> Int64.of_int)
    beta
  |> with_tensor_gc
;;

let smooth_l1_loss_backward_grad_input
  ~grad_input
  ~grad_output
  self
  ~target
  ~reduction
  ~beta
  =
  stubs_smooth_l1_loss_backward_grad_input
    grad_input
    grad_output
    self
    target
    (Reduction.to_int reduction |> Int64.of_int)
    beta
  |> with_tensor_gc
;;

let smooth_l1_loss_out ~out self ~target ~reduction ~beta =
  stubs_smooth_l1_loss_out
    out
    self
    target
    (Reduction.to_int reduction |> Int64.of_int)
    beta
  |> with_tensor_gc
;;

let soft_margin_loss self ~target ~reduction =
  stubs_soft_margin_loss self target (Reduction.to_int reduction |> Int64.of_int)
  |> with_tensor_gc
;;

let soft_margin_loss_backward ~grad_output self ~target ~reduction =
  stubs_soft_margin_loss_backward
    grad_output
    self
    target
    (Reduction.to_int reduction |> Int64.of_int)
  |> with_tensor_gc
;;

let soft_margin_loss_backward_grad_input ~grad_input ~grad_output self ~target ~reduction =
  stubs_soft_margin_loss_backward_grad_input
    grad_input
    grad_output
    self
    target
    (Reduction.to_int reduction |> Int64.of_int)
  |> with_tensor_gc
;;

let soft_margin_loss_out ~out self ~target ~reduction =
  stubs_soft_margin_loss_out out self target (Reduction.to_int reduction |> Int64.of_int)
  |> with_tensor_gc
;;

let softmax self ~dim ~dtype =
  stubs_softmax self (Int64.of_int dim) (Kind.packed_to_int dtype) |> with_tensor_gc
;;

let softmax_int_out ~out self ~dim ~dtype =
  stubs_softmax_int_out out self (Int64.of_int dim) (Kind.packed_to_int dtype)
  |> with_tensor_gc
;;

let softplus ?beta ?threshold self =
  stubs_softplus
    self
    (match beta with
     | Some v -> v
     | None -> none_scalar)
    (match threshold with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let softplus_backward ~grad_output self ~beta ~threshold =
  stubs_softplus_backward grad_output self beta threshold |> with_tensor_gc
;;

let softplus_backward_grad_input ~grad_input ~grad_output self ~beta ~threshold =
  stubs_softplus_backward_grad_input grad_input grad_output self beta threshold
  |> with_tensor_gc
;;

let softplus_out ?beta ?threshold ~out self =
  stubs_softplus_out
    out
    self
    (match beta with
     | Some v -> v
     | None -> none_scalar)
    (match threshold with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let softshrink ?lambd self =
  stubs_softshrink
    self
    (match lambd with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let softshrink_backward ~grad_output self ~lambd =
  stubs_softshrink_backward grad_output self lambd |> with_tensor_gc
;;

let softshrink_backward_grad_input ~grad_input ~grad_output self ~lambd =
  stubs_softshrink_backward_grad_input grad_input grad_output self lambd |> with_tensor_gc
;;

let softshrink_out ?lambd ~out self =
  stubs_softshrink_out
    out
    self
    (match lambd with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let sort self ~dim ~descending =
  let out__ = CArray.make raw_tensor 2 in
  stubs_sort (CArray.start out__) self (Int64.of_int dim) (if descending then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  t0, t1
;;

let sort_stable self ~stable ~dim ~descending =
  let out__ = CArray.make raw_tensor 2 in
  stubs_sort_stable
    (CArray.start out__)
    self
    (if stable then 1 else 0)
    (Int64.of_int dim)
    (if descending then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  t0, t1
;;

let sort_values ~values ~indices self ~dim ~descending =
  let out__ = CArray.make raw_tensor 2 in
  stubs_sort_values
    (CArray.start out__)
    values
    indices
    self
    (Int64.of_int dim)
    (if descending then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  t0, t1
;;

let sort_values_stable ~values ~indices self ~stable ~dim ~descending =
  let out__ = CArray.make raw_tensor 2 in
  stubs_sort_values_stable
    (CArray.start out__)
    values
    indices
    self
    (if stable then 1 else 0)
    (Int64.of_int dim)
    (if descending then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  t0, t1
;;

let sparse_bsc_tensor ~ccol_indices ~row_indices ~values ~options =
  stubs_sparse_bsc_tensor
    ccol_indices
    row_indices
    values
    (Kind.packed_to_int (fst options))
    (Device.to_int (snd options))
  |> with_tensor_gc
;;

let sparse_bsc_tensor_ccol_row_value_size
  ~ccol_indices
  ~row_indices
  ~values
  ~size
  ~options
  =
  stubs_sparse_bsc_tensor_ccol_row_value_size
    ccol_indices
    row_indices
    values
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
    (Kind.packed_to_int (fst options))
    (Device.to_int (snd options))
  |> with_tensor_gc
;;

let sparse_bsr_tensor ~crow_indices ~col_indices ~values ~options =
  stubs_sparse_bsr_tensor
    crow_indices
    col_indices
    values
    (Kind.packed_to_int (fst options))
    (Device.to_int (snd options))
  |> with_tensor_gc
;;

let sparse_bsr_tensor_crow_col_value_size
  ~crow_indices
  ~col_indices
  ~values
  ~size
  ~options
  =
  stubs_sparse_bsr_tensor_crow_col_value_size
    crow_indices
    col_indices
    values
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
    (Kind.packed_to_int (fst options))
    (Device.to_int (snd options))
  |> with_tensor_gc
;;

let sparse_compressed_tensor ~compressed_indices ~plain_indices ~values ~options =
  stubs_sparse_compressed_tensor
    compressed_indices
    plain_indices
    values
    (Kind.packed_to_int (fst options))
    (Device.to_int (snd options))
  |> with_tensor_gc
;;

let sparse_compressed_tensor_comp_plain_value_size
  ~compressed_indices
  ~plain_indices
  ~values
  ~size
  ~options
  =
  stubs_sparse_compressed_tensor_comp_plain_value_size
    compressed_indices
    plain_indices
    values
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
    (Kind.packed_to_int (fst options))
    (Device.to_int (snd options))
  |> with_tensor_gc
;;

let sparse_coo_tensor ~size ~options =
  stubs_sparse_coo_tensor
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
    (Kind.packed_to_int (fst options))
    (Device.to_int (snd options))
  |> with_tensor_gc
;;

let sparse_coo_tensor_indices ~indices ~values ~options ~is_coalesced =
  stubs_sparse_coo_tensor_indices
    indices
    values
    (Kind.packed_to_int (fst options))
    (Device.to_int (snd options))
    (if is_coalesced then 1 else 0)
  |> with_tensor_gc
;;

let sparse_coo_tensor_indices_size ~indices ~values ~size ~options ~is_coalesced =
  stubs_sparse_coo_tensor_indices_size
    indices
    values
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
    (Kind.packed_to_int (fst options))
    (Device.to_int (snd options))
    (if is_coalesced then 1 else 0)
  |> with_tensor_gc
;;

let sparse_coo_tensor_size_out ~out ~size =
  stubs_sparse_coo_tensor_size_out
    out
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
  |> with_tensor_gc
;;

let sparse_csc_tensor ~ccol_indices ~row_indices ~values ~options =
  stubs_sparse_csc_tensor
    ccol_indices
    row_indices
    values
    (Kind.packed_to_int (fst options))
    (Device.to_int (snd options))
  |> with_tensor_gc
;;

let sparse_csc_tensor_ccol_row_value_size
  ~ccol_indices
  ~row_indices
  ~values
  ~size
  ~options
  =
  stubs_sparse_csc_tensor_ccol_row_value_size
    ccol_indices
    row_indices
    values
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
    (Kind.packed_to_int (fst options))
    (Device.to_int (snd options))
  |> with_tensor_gc
;;

let sparse_csr_tensor ~crow_indices ~col_indices ~values ~options =
  stubs_sparse_csr_tensor
    crow_indices
    col_indices
    values
    (Kind.packed_to_int (fst options))
    (Device.to_int (snd options))
  |> with_tensor_gc
;;

let sparse_csr_tensor_crow_col_value_size
  ~crow_indices
  ~col_indices
  ~values
  ~size
  ~options
  =
  stubs_sparse_csr_tensor_crow_col_value_size
    crow_indices
    col_indices
    values
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
    (Kind.packed_to_int (fst options))
    (Device.to_int (snd options))
  |> with_tensor_gc
;;

let sparse_dim self = stubs_sparse_dim self
let sparse_mask self ~mask = stubs_sparse_mask self mask |> with_tensor_gc

let sparse_mask_out ~out self ~mask =
  stubs_sparse_mask_out out self mask |> with_tensor_gc
;;

let sparse_resize self ~size ~sparse_dim ~dense_dim =
  stubs_sparse_resize
    self
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
    (Int64.of_int sparse_dim)
    (Int64.of_int dense_dim)
  |> with_tensor_gc
;;

let sparse_resize_ self ~size ~sparse_dim ~dense_dim =
  stubs_sparse_resize_
    self
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
    (Int64.of_int sparse_dim)
    (Int64.of_int dense_dim)
  |> with_tensor_gc
;;

let sparse_resize_and_clear self ~size ~sparse_dim ~dense_dim =
  stubs_sparse_resize_and_clear
    self
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
    (Int64.of_int sparse_dim)
    (Int64.of_int dense_dim)
  |> with_tensor_gc
;;

let sparse_resize_and_clear_ self ~size ~sparse_dim ~dense_dim =
  stubs_sparse_resize_and_clear_
    self
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
    (Int64.of_int sparse_dim)
    (Int64.of_int dense_dim)
  |> with_tensor_gc
;;

let sparse_resize_and_clear_out ~out self ~size ~sparse_dim ~dense_dim =
  stubs_sparse_resize_and_clear_out
    out
    self
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
    (Int64.of_int sparse_dim)
    (Int64.of_int dense_dim)
  |> with_tensor_gc
;;

let sparse_resize_out ~out self ~size ~sparse_dim ~dense_dim =
  stubs_sparse_resize_out
    out
    self
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
    (Int64.of_int sparse_dim)
    (Int64.of_int dense_dim)
  |> with_tensor_gc
;;

let sparse_sampled_addmm ?beta ?alpha self ~mat1 ~mat2 =
  stubs_sparse_sampled_addmm
    self
    mat1
    mat2
    (match beta with
     | Some v -> v
     | None -> none_scalar)
    (match alpha with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let sparse_sampled_addmm_out ?beta ?alpha ~out self ~mat1 ~mat2 =
  stubs_sparse_sampled_addmm_out
    out
    self
    mat1
    mat2
    (match beta with
     | Some v -> v
     | None -> none_scalar)
    (match alpha with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let special_airy_ai ~x = stubs_special_airy_ai x |> with_tensor_gc
let special_airy_ai_out ~out ~x = stubs_special_airy_ai_out out x |> with_tensor_gc
let special_bessel_j0 self = stubs_special_bessel_j0 self |> with_tensor_gc

let special_bessel_j0_out ~out self =
  stubs_special_bessel_j0_out out self |> with_tensor_gc
;;

let special_bessel_j1 self = stubs_special_bessel_j1 self |> with_tensor_gc

let special_bessel_j1_out ~out self =
  stubs_special_bessel_j1_out out self |> with_tensor_gc
;;

let special_bessel_y0 self = stubs_special_bessel_y0 self |> with_tensor_gc

let special_bessel_y0_out ~out self =
  stubs_special_bessel_y0_out out self |> with_tensor_gc
;;

let special_bessel_y1 self = stubs_special_bessel_y1 self |> with_tensor_gc

let special_bessel_y1_out ~out self =
  stubs_special_bessel_y1_out out self |> with_tensor_gc
;;

let special_chebyshev_polynomial_t ~x ~n =
  stubs_special_chebyshev_polynomial_t x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_t_n_scalar ~x ~n =
  stubs_special_chebyshev_polynomial_t_n_scalar x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_t_n_scalar_out ~out ~x ~n =
  stubs_special_chebyshev_polynomial_t_n_scalar_out out x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_t_out ~out ~x ~n =
  stubs_special_chebyshev_polynomial_t_out out x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_t_x_scalar ~x ~n =
  stubs_special_chebyshev_polynomial_t_x_scalar x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_t_x_scalar_out ~out ~x ~n =
  stubs_special_chebyshev_polynomial_t_x_scalar_out out x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_u ~x ~n =
  stubs_special_chebyshev_polynomial_u x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_u_n_scalar ~x ~n =
  stubs_special_chebyshev_polynomial_u_n_scalar x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_u_n_scalar_out ~out ~x ~n =
  stubs_special_chebyshev_polynomial_u_n_scalar_out out x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_u_out ~out ~x ~n =
  stubs_special_chebyshev_polynomial_u_out out x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_u_x_scalar ~x ~n =
  stubs_special_chebyshev_polynomial_u_x_scalar x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_u_x_scalar_out ~out ~x ~n =
  stubs_special_chebyshev_polynomial_u_x_scalar_out out x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_v ~x ~n =
  stubs_special_chebyshev_polynomial_v x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_v_n_scalar ~x ~n =
  stubs_special_chebyshev_polynomial_v_n_scalar x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_v_n_scalar_out ~out ~x ~n =
  stubs_special_chebyshev_polynomial_v_n_scalar_out out x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_v_out ~out ~x ~n =
  stubs_special_chebyshev_polynomial_v_out out x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_v_x_scalar ~x ~n =
  stubs_special_chebyshev_polynomial_v_x_scalar x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_v_x_scalar_out ~out ~x ~n =
  stubs_special_chebyshev_polynomial_v_x_scalar_out out x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_w ~x ~n =
  stubs_special_chebyshev_polynomial_w x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_w_n_scalar ~x ~n =
  stubs_special_chebyshev_polynomial_w_n_scalar x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_w_n_scalar_out ~out ~x ~n =
  stubs_special_chebyshev_polynomial_w_n_scalar_out out x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_w_out ~out ~x ~n =
  stubs_special_chebyshev_polynomial_w_out out x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_w_x_scalar ~x ~n =
  stubs_special_chebyshev_polynomial_w_x_scalar x n |> with_tensor_gc
;;

let special_chebyshev_polynomial_w_x_scalar_out ~out ~x ~n =
  stubs_special_chebyshev_polynomial_w_x_scalar_out out x n |> with_tensor_gc
;;

let special_digamma self = stubs_special_digamma self |> with_tensor_gc
let special_digamma_out ~out self = stubs_special_digamma_out out self |> with_tensor_gc
let special_entr self = stubs_special_entr self |> with_tensor_gc
let special_entr_out ~out self = stubs_special_entr_out out self |> with_tensor_gc
let special_erf self = stubs_special_erf self |> with_tensor_gc
let special_erf_out ~out self = stubs_special_erf_out out self |> with_tensor_gc
let special_erfc self = stubs_special_erfc self |> with_tensor_gc
let special_erfc_out ~out self = stubs_special_erfc_out out self |> with_tensor_gc
let special_erfcx self = stubs_special_erfcx self |> with_tensor_gc
let special_erfcx_out ~out self = stubs_special_erfcx_out out self |> with_tensor_gc
let special_erfinv self = stubs_special_erfinv self |> with_tensor_gc
let special_erfinv_out ~out self = stubs_special_erfinv_out out self |> with_tensor_gc
let special_exp2 self = stubs_special_exp2 self |> with_tensor_gc
let special_exp2_out ~out self = stubs_special_exp2_out out self |> with_tensor_gc
let special_expit self = stubs_special_expit self |> with_tensor_gc
let special_expit_out ~out self = stubs_special_expit_out out self |> with_tensor_gc
let special_expm1 self = stubs_special_expm1 self |> with_tensor_gc
let special_expm1_out ~out self = stubs_special_expm1_out out self |> with_tensor_gc
let special_gammainc self other = stubs_special_gammainc self other |> with_tensor_gc

let special_gammainc_out ~out self other =
  stubs_special_gammainc_out out self other |> with_tensor_gc
;;

let special_gammaincc self other = stubs_special_gammaincc self other |> with_tensor_gc

let special_gammaincc_out ~out self other =
  stubs_special_gammaincc_out out self other |> with_tensor_gc
;;

let special_gammaln self = stubs_special_gammaln self |> with_tensor_gc
let special_gammaln_out ~out self = stubs_special_gammaln_out out self |> with_tensor_gc

let special_hermite_polynomial_h ~x ~n =
  stubs_special_hermite_polynomial_h x n |> with_tensor_gc
;;

let special_hermite_polynomial_h_n_scalar ~x ~n =
  stubs_special_hermite_polynomial_h_n_scalar x n |> with_tensor_gc
;;

let special_hermite_polynomial_h_n_scalar_out ~out ~x ~n =
  stubs_special_hermite_polynomial_h_n_scalar_out out x n |> with_tensor_gc
;;

let special_hermite_polynomial_h_out ~out ~x ~n =
  stubs_special_hermite_polynomial_h_out out x n |> with_tensor_gc
;;

let special_hermite_polynomial_h_x_scalar ~x ~n =
  stubs_special_hermite_polynomial_h_x_scalar x n |> with_tensor_gc
;;

let special_hermite_polynomial_h_x_scalar_out ~out ~x ~n =
  stubs_special_hermite_polynomial_h_x_scalar_out out x n |> with_tensor_gc
;;

let special_hermite_polynomial_he ~x ~n =
  stubs_special_hermite_polynomial_he x n |> with_tensor_gc
;;

let special_hermite_polynomial_he_n_scalar ~x ~n =
  stubs_special_hermite_polynomial_he_n_scalar x n |> with_tensor_gc
;;

let special_hermite_polynomial_he_n_scalar_out ~out ~x ~n =
  stubs_special_hermite_polynomial_he_n_scalar_out out x n |> with_tensor_gc
;;

let special_hermite_polynomial_he_out ~out ~x ~n =
  stubs_special_hermite_polynomial_he_out out x n |> with_tensor_gc
;;

let special_hermite_polynomial_he_x_scalar ~x ~n =
  stubs_special_hermite_polynomial_he_x_scalar x n |> with_tensor_gc
;;

let special_hermite_polynomial_he_x_scalar_out ~out ~x ~n =
  stubs_special_hermite_polynomial_he_x_scalar_out out x n |> with_tensor_gc
;;

let special_i0 self = stubs_special_i0 self |> with_tensor_gc
let special_i0_out ~out self = stubs_special_i0_out out self |> with_tensor_gc
let special_i0e self = stubs_special_i0e self |> with_tensor_gc
let special_i0e_out ~out self = stubs_special_i0e_out out self |> with_tensor_gc
let special_i1 self = stubs_special_i1 self |> with_tensor_gc
let special_i1_out ~out self = stubs_special_i1_out out self |> with_tensor_gc
let special_i1e self = stubs_special_i1e self |> with_tensor_gc
let special_i1e_out ~out self = stubs_special_i1e_out out self |> with_tensor_gc

let special_laguerre_polynomial_l ~x ~n =
  stubs_special_laguerre_polynomial_l x n |> with_tensor_gc
;;

let special_laguerre_polynomial_l_n_scalar ~x ~n =
  stubs_special_laguerre_polynomial_l_n_scalar x n |> with_tensor_gc
;;

let special_laguerre_polynomial_l_n_scalar_out ~out ~x ~n =
  stubs_special_laguerre_polynomial_l_n_scalar_out out x n |> with_tensor_gc
;;

let special_laguerre_polynomial_l_out ~out ~x ~n =
  stubs_special_laguerre_polynomial_l_out out x n |> with_tensor_gc
;;

let special_laguerre_polynomial_l_x_scalar ~x ~n =
  stubs_special_laguerre_polynomial_l_x_scalar x n |> with_tensor_gc
;;

let special_laguerre_polynomial_l_x_scalar_out ~out ~x ~n =
  stubs_special_laguerre_polynomial_l_x_scalar_out out x n |> with_tensor_gc
;;

let special_legendre_polynomial_p ~x ~n =
  stubs_special_legendre_polynomial_p x n |> with_tensor_gc
;;

let special_legendre_polynomial_p_n_scalar ~x ~n =
  stubs_special_legendre_polynomial_p_n_scalar x n |> with_tensor_gc
;;

let special_legendre_polynomial_p_n_scalar_out ~out ~x ~n =
  stubs_special_legendre_polynomial_p_n_scalar_out out x n |> with_tensor_gc
;;

let special_legendre_polynomial_p_out ~out ~x ~n =
  stubs_special_legendre_polynomial_p_out out x n |> with_tensor_gc
;;

let special_legendre_polynomial_p_x_scalar ~x ~n =
  stubs_special_legendre_polynomial_p_x_scalar x n |> with_tensor_gc
;;

let special_legendre_polynomial_p_x_scalar_out ~out ~x ~n =
  stubs_special_legendre_polynomial_p_x_scalar_out out x n |> with_tensor_gc
;;

let special_log1p self = stubs_special_log1p self |> with_tensor_gc
let special_log1p_out ~out self = stubs_special_log1p_out out self |> with_tensor_gc
let special_log_ndtr self = stubs_special_log_ndtr self |> with_tensor_gc
let special_log_ndtr_out ~out self = stubs_special_log_ndtr_out out self |> with_tensor_gc

let special_log_softmax self ~dim ~dtype =
  stubs_special_log_softmax self (Int64.of_int dim) (Kind.packed_to_int dtype)
  |> with_tensor_gc
;;

let special_logit self ~eps =
  stubs_special_logit
    self
    (Option.value eps ~default:0.0)
    (match eps with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let special_logit_out ~out self ~eps =
  stubs_special_logit_out
    out
    self
    (Option.value eps ~default:0.0)
    (match eps with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let special_logsumexp self ~dim ~keepdim =
  stubs_special_logsumexp
    self
    (List.map Int64.of_int dim |> CArray.of_list int64_t |> CArray.start)
    (List.length dim)
    (if keepdim then 1 else 0)
  |> with_tensor_gc
;;

let special_logsumexp_out ~out self ~dim ~keepdim =
  stubs_special_logsumexp_out
    out
    self
    (List.map Int64.of_int dim |> CArray.of_list int64_t |> CArray.start)
    (List.length dim)
    (if keepdim then 1 else 0)
  |> with_tensor_gc
;;

let special_modified_bessel_i0 self =
  stubs_special_modified_bessel_i0 self |> with_tensor_gc
;;

let special_modified_bessel_i0_out ~out self =
  stubs_special_modified_bessel_i0_out out self |> with_tensor_gc
;;

let special_modified_bessel_i1 self =
  stubs_special_modified_bessel_i1 self |> with_tensor_gc
;;
