(* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT BY HAND! *)

open Ctypes
open Torch_bindings.Type_defs
open Torch_stubs
open Torch_wrapper_types
open Wrapper_utils
open C.Generated

let special_modified_bessel_i1_out ~out self =
  stubs_special_modified_bessel_i1_out out self |> with_tensor_gc
;;

let special_modified_bessel_k0 self =
  stubs_special_modified_bessel_k0 self |> with_tensor_gc
;;

let special_modified_bessel_k0_out ~out self =
  stubs_special_modified_bessel_k0_out out self |> with_tensor_gc
;;

let special_modified_bessel_k1 self =
  stubs_special_modified_bessel_k1 self |> with_tensor_gc
;;

let special_modified_bessel_k1_out ~out self =
  stubs_special_modified_bessel_k1_out out self |> with_tensor_gc
;;

let special_multigammaln self ~p =
  stubs_special_multigammaln self (Int64.of_int p) |> with_tensor_gc
;;

let special_multigammaln_out ~out self ~p =
  stubs_special_multigammaln_out out self (Int64.of_int p) |> with_tensor_gc
;;

let special_ndtr self = stubs_special_ndtr self |> with_tensor_gc
let special_ndtr_out ~out self = stubs_special_ndtr_out out self |> with_tensor_gc
let special_ndtri self = stubs_special_ndtri self |> with_tensor_gc
let special_ndtri_out ~out self = stubs_special_ndtri_out out self |> with_tensor_gc

let special_polygamma ~n self =
  stubs_special_polygamma (Int64.of_int n) self |> with_tensor_gc
;;

let special_polygamma_out ~out ~n self =
  stubs_special_polygamma_out out (Int64.of_int n) self |> with_tensor_gc
;;

let special_psi self = stubs_special_psi self |> with_tensor_gc
let special_psi_out ~out self = stubs_special_psi_out out self |> with_tensor_gc

let special_round self ~decimals =
  stubs_special_round self (Int64.of_int decimals) |> with_tensor_gc
;;

let special_round_out ~out self ~decimals =
  stubs_special_round_out out self (Int64.of_int decimals) |> with_tensor_gc
;;

let special_scaled_modified_bessel_k0 ~x =
  stubs_special_scaled_modified_bessel_k0 x |> with_tensor_gc
;;

let special_scaled_modified_bessel_k0_out ~out ~x =
  stubs_special_scaled_modified_bessel_k0_out out x |> with_tensor_gc
;;

let special_scaled_modified_bessel_k1 ~x =
  stubs_special_scaled_modified_bessel_k1 x |> with_tensor_gc
;;

let special_scaled_modified_bessel_k1_out ~out ~x =
  stubs_special_scaled_modified_bessel_k1_out out x |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_t ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_t x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_t_n_scalar ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_t_n_scalar x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_t_n_scalar_out ~out ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_t_n_scalar_out out x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_t_out ~out ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_t_out out x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_t_x_scalar ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_t_x_scalar x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_t_x_scalar_out ~out ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_t_x_scalar_out out x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_u ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_u x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_u_n_scalar ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_u_n_scalar x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_u_n_scalar_out ~out ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_u_n_scalar_out out x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_u_out ~out ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_u_out out x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_u_x_scalar ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_u_x_scalar x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_u_x_scalar_out ~out ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_u_x_scalar_out out x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_v ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_v x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_v_n_scalar ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_v_n_scalar x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_v_n_scalar_out ~out ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_v_n_scalar_out out x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_v_out ~out ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_v_out out x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_v_x_scalar ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_v_x_scalar x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_v_x_scalar_out ~out ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_v_x_scalar_out out x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_w ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_w x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_w_n_scalar ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_w_n_scalar x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_w_n_scalar_out ~out ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_w_n_scalar_out out x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_w_out ~out ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_w_out out x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_w_x_scalar ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_w_x_scalar x n |> with_tensor_gc
;;

let special_shifted_chebyshev_polynomial_w_x_scalar_out ~out ~x ~n =
  stubs_special_shifted_chebyshev_polynomial_w_x_scalar_out out x n |> with_tensor_gc
;;

let special_sinc self = stubs_special_sinc self |> with_tensor_gc
let special_sinc_out ~out self = stubs_special_sinc_out out self |> with_tensor_gc

let special_softmax self ~dim ~dtype =
  stubs_special_softmax self (Int64.of_int dim) (Kind.packed_to_int dtype)
  |> with_tensor_gc
;;

let special_spherical_bessel_j0 ~x = stubs_special_spherical_bessel_j0 x |> with_tensor_gc

let special_spherical_bessel_j0_out ~out ~x =
  stubs_special_spherical_bessel_j0_out out x |> with_tensor_gc
;;

let special_xlog1py self other = stubs_special_xlog1py self other |> with_tensor_gc

let special_xlog1py_other_scalar self other =
  stubs_special_xlog1py_other_scalar self other |> with_tensor_gc
;;

let special_xlog1py_other_scalar_out ~out self other =
  stubs_special_xlog1py_other_scalar_out out self other |> with_tensor_gc
;;

let special_xlog1py_out ~out self other =
  stubs_special_xlog1py_out out self other |> with_tensor_gc
;;

let special_xlog1py_self_scalar self other =
  stubs_special_xlog1py_self_scalar self other |> with_tensor_gc
;;

let special_xlog1py_self_scalar_out ~out self other =
  stubs_special_xlog1py_self_scalar_out out self other |> with_tensor_gc
;;

let special_xlogy self other = stubs_special_xlogy self other |> with_tensor_gc

let special_xlogy_other_scalar self other =
  stubs_special_xlogy_other_scalar self other |> with_tensor_gc
;;

let special_xlogy_other_scalar_out ~out self other =
  stubs_special_xlogy_other_scalar_out out self other |> with_tensor_gc
;;

let special_xlogy_out ~out self other =
  stubs_special_xlogy_out out self other |> with_tensor_gc
;;

let special_xlogy_self_scalar self other =
  stubs_special_xlogy_self_scalar self other |> with_tensor_gc
;;

let special_xlogy_self_scalar_out ~out self other =
  stubs_special_xlogy_self_scalar_out out self other |> with_tensor_gc
;;

let special_zeta self other = stubs_special_zeta self other |> with_tensor_gc

let special_zeta_other_scalar self other =
  stubs_special_zeta_other_scalar self other |> with_tensor_gc
;;

let special_zeta_other_scalar_out ~out self other =
  stubs_special_zeta_other_scalar_out out self other |> with_tensor_gc
;;

let special_zeta_out ~out self other =
  stubs_special_zeta_out out self other |> with_tensor_gc
;;

let special_zeta_self_scalar self other =
  stubs_special_zeta_self_scalar self other |> with_tensor_gc
;;

let special_zeta_self_scalar_out ~out self other =
  stubs_special_zeta_self_scalar_out out self other |> with_tensor_gc
;;

let split self ~split_size ~dim =
  stubs_split self (Int64.of_int split_size) (Int64.of_int dim) |> to_tensor_list
;;

let split_copy self ~split_size ~dim =
  stubs_split_copy self (Int64.of_int split_size) (Int64.of_int dim) |> to_tensor_list
;;

let split_copy_tensor_out ~out self ~split_size ~dim =
  let result =
    stubs_split_copy_tensor_out
      (CArray.of_list gc_tensor out |> CArray.start)
      (List.length out)
      self
      (Int64.of_int split_size)
      (Int64.of_int dim)
  in
  keep_values_alive out;
  result
;;

let split_sizes self ~split_size ~dim =
  stubs_split_sizes
    self
    (List.map Int64.of_int split_size |> CArray.of_list int64_t |> CArray.start)
    (List.length split_size)
    (Int64.of_int dim)
  |> to_tensor_list
;;

let split_with_sizes self ~split_sizes ~dim =
  stubs_split_with_sizes
    self
    (List.map Int64.of_int split_sizes |> CArray.of_list int64_t |> CArray.start)
    (List.length split_sizes)
    (Int64.of_int dim)
  |> to_tensor_list
;;

let split_with_sizes_copy self ~split_sizes ~dim =
  stubs_split_with_sizes_copy
    self
    (List.map Int64.of_int split_sizes |> CArray.of_list int64_t |> CArray.start)
    (List.length split_sizes)
    (Int64.of_int dim)
  |> to_tensor_list
;;

let split_with_sizes_copy_out ~out self ~split_sizes ~dim =
  let result =
    stubs_split_with_sizes_copy_out
      (CArray.of_list gc_tensor out |> CArray.start)
      (List.length out)
      self
      (List.map Int64.of_int split_sizes |> CArray.of_list int64_t |> CArray.start)
      (List.length split_sizes)
      (Int64.of_int dim)
  in
  keep_values_alive out;
  result
;;

let sqrt self = stubs_sqrt self |> with_tensor_gc
let sqrt_ self = stubs_sqrt_ self |> with_tensor_gc
let sqrt_out ~out self = stubs_sqrt_out out self |> with_tensor_gc
let square self = stubs_square self |> with_tensor_gc
let square_ self = stubs_square_ self |> with_tensor_gc
let square_out ~out self = stubs_square_out out self |> with_tensor_gc
let squeeze self = stubs_squeeze self |> with_tensor_gc
let squeeze_ self = stubs_squeeze_ self |> with_tensor_gc
let squeeze_copy self = stubs_squeeze_copy self |> with_tensor_gc

let squeeze_copy_dim self ~dim =
  stubs_squeeze_copy_dim self (Int64.of_int dim) |> with_tensor_gc
;;

let squeeze_copy_dim_out ~out self ~dim =
  stubs_squeeze_copy_dim_out out self (Int64.of_int dim) |> with_tensor_gc
;;

let squeeze_copy_dims self ~dim =
  stubs_squeeze_copy_dims
    self
    (List.map Int64.of_int dim |> CArray.of_list int64_t |> CArray.start)
    (List.length dim)
  |> with_tensor_gc
;;

let squeeze_copy_dims_out ~out self ~dim =
  stubs_squeeze_copy_dims_out
    out
    self
    (List.map Int64.of_int dim |> CArray.of_list int64_t |> CArray.start)
    (List.length dim)
  |> with_tensor_gc
;;

let squeeze_copy_out ~out self = stubs_squeeze_copy_out out self |> with_tensor_gc
let squeeze_dim self ~dim = stubs_squeeze_dim self (Int64.of_int dim) |> with_tensor_gc
let squeeze_dim_ self ~dim = stubs_squeeze_dim_ self (Int64.of_int dim) |> with_tensor_gc

let squeeze_dims self ~dim =
  stubs_squeeze_dims
    self
    (List.map Int64.of_int dim |> CArray.of_list int64_t |> CArray.start)
    (List.length dim)
  |> with_tensor_gc
;;

let squeeze_dims_ self ~dim =
  stubs_squeeze_dims_
    self
    (List.map Int64.of_int dim |> CArray.of_list int64_t |> CArray.start)
    (List.length dim)
  |> with_tensor_gc
;;

let sspaddmm ?beta ?alpha self ~mat1 ~mat2 =
  stubs_sspaddmm
    self
    mat1
    mat2
    (match beta with
     | Some v -> v
     | None -> none_scalar)
    (match alpha with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let sspaddmm_out ?beta ?alpha ~out self ~mat1 ~mat2 =
  stubs_sspaddmm_out
    out
    self
    mat1
    mat2
    (match beta with
     | Some v -> v
     | None -> none_scalar)
    (match alpha with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let stack tensors ~dim =
  let result =
    stubs_stack
      (CArray.of_list gc_tensor tensors |> CArray.start)
      (List.length tensors)
      (Int64.of_int dim)
    |> with_tensor_gc
  in
  keep_values_alive tensors;
  result
;;

let stack_out ~out tensors ~dim =
  let result =
    stubs_stack_out
      out
      (CArray.of_list gc_tensor tensors |> CArray.start)
      (List.length tensors)
      (Int64.of_int dim)
    |> with_tensor_gc
  in
  keep_values_alive tensors;
  result
;;

let std self ~unbiased = stubs_std self (if unbiased then 1 else 0) |> with_tensor_gc

let std_correction self ~dim ~correction ~keepdim =
  stubs_std_correction
    self
    (match dim with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match dim with
     | None -> -1
     | Some v -> List.length v)
    correction
    (if keepdim then 1 else 0)
  |> with_tensor_gc
;;

let std_correction_out ~out self ~dim ~correction ~keepdim =
  stubs_std_correction_out
    out
    self
    (match dim with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match dim with
     | None -> -1
     | Some v -> List.length v)
    correction
    (if keepdim then 1 else 0)
  |> with_tensor_gc
;;

let std_dim self ~dim ~unbiased ~keepdim =
  stubs_std_dim
    self
    (match dim with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match dim with
     | None -> -1
     | Some v -> List.length v)
    (if unbiased then 1 else 0)
    (if keepdim then 1 else 0)
  |> with_tensor_gc
;;

let std_mean self ~unbiased =
  let out__ = CArray.make raw_tensor 2 in
  stubs_std_mean (CArray.start out__) self (if unbiased then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  t0, t1
;;

let std_mean_correction self ~dim ~correction ~keepdim =
  let out__ = CArray.make raw_tensor 2 in
  stubs_std_mean_correction
    (CArray.start out__)
    self
    (match dim with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match dim with
     | None -> -1
     | Some v -> List.length v)
    correction
    (if keepdim then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  t0, t1
;;

let std_mean_correction_out ~out0 ~out1 self ~dim ~correction ~keepdim =
  let out__ = CArray.make raw_tensor 2 in
  stubs_std_mean_correction_out
    (CArray.start out__)
    out0
    out1
    self
    (match dim with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match dim with
     | None -> -1
     | Some v -> List.length v)
    correction
    (if keepdim then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  t0, t1
;;

let std_mean_dim self ~dim ~unbiased ~keepdim =
  let out__ = CArray.make raw_tensor 2 in
  stubs_std_mean_dim
    (CArray.start out__)
    self
    (match dim with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match dim with
     | None -> -1
     | Some v -> List.length v)
    (if unbiased then 1 else 0)
    (if keepdim then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  t0, t1
;;

let std_out ~out self ~dim ~unbiased ~keepdim =
  stubs_std_out
    out
    self
    (match dim with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match dim with
     | None -> -1
     | Some v -> List.length v)
    (if unbiased then 1 else 0)
    (if keepdim then 1 else 0)
  |> with_tensor_gc
;;

let stft
  self
  ~n_fft
  ~hop_length
  ~win_length
  ~window
  ~normalized
  ~onesided
  ~return_complex
  ~align_to_window
  =
  stubs_stft
    self
    (Int64.of_int n_fft)
    (match hop_length with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match hop_length with
     | Some _ -> 0
     | None -> 1)
    (match win_length with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match win_length with
     | Some _ -> 0
     | None -> 1)
    (match window with
     | Some v -> v
     | None -> none_gc_tensor)
    (if normalized then 1 else 0)
    (if onesided then 1 else 0)
    (if return_complex then 1 else 0)
    (if align_to_window then 1 else 0)
  |> with_tensor_gc
;;

let stft_center
  self
  ~n_fft
  ~hop_length
  ~win_length
  ~window
  ~center
  ~pad_mode
  ~normalized
  ~onesided
  ~return_complex
  ~align_to_window
  =
  stubs_stft_center
    self
    (Int64.of_int n_fft)
    (match hop_length with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match hop_length with
     | Some _ -> 0
     | None -> 1)
    (match win_length with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match win_length with
     | Some _ -> 0
     | None -> 1)
    (match window with
     | Some v -> v
     | None -> none_gc_tensor)
    (if center then 1 else 0)
    pad_mode
    (if normalized then 1 else 0)
    (if onesided then 1 else 0)
    (if return_complex then 1 else 0)
    (if align_to_window then 1 else 0)
  |> with_tensor_gc
;;

let stride self ~dim = stubs_stride self (Int64.of_int dim)

let sub ?alpha self other =
  stubs_sub
    self
    other
    (match alpha with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let sub_ ?alpha self other =
  stubs_sub_
    self
    other
    (match alpha with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let sub_out ?alpha ~out self other =
  stubs_sub_out
    out
    self
    other
    (match alpha with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let sub_scalar ?alpha self other =
  stubs_sub_scalar
    self
    other
    (match alpha with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let sub_scalar_ ?alpha self other =
  stubs_sub_scalar_
    self
    other
    (match alpha with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let sub_scalar_out ?alpha ~out self other =
  stubs_sub_scalar_out
    out
    self
    other
    (match alpha with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let subtract ?alpha self other =
  stubs_subtract
    self
    other
    (match alpha with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let subtract_ ?alpha self other =
  stubs_subtract_
    self
    other
    (match alpha with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let subtract_out ?alpha ~out self other =
  stubs_subtract_out
    out
    self
    other
    (match alpha with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let subtract_scalar ?alpha self other =
  stubs_subtract_scalar
    self
    other
    (match alpha with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let subtract_scalar_ ?alpha self other =
  stubs_subtract_scalar_
    self
    other
    (match alpha with
     | Some v -> v
     | None -> none_scalar)
  |> with_tensor_gc
;;

let sum self ~dtype = stubs_sum self (Kind.packed_to_int dtype) |> with_tensor_gc

let sum_dim_intlist self ~dim ~keepdim ~dtype =
  stubs_sum_dim_intlist
    self
    (match dim with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match dim with
     | None -> -1
     | Some v -> List.length v)
    (if keepdim then 1 else 0)
    (Kind.packed_to_int dtype)
  |> with_tensor_gc
;;

let sum_intlist_out ~out self ~dim ~keepdim ~dtype =
  stubs_sum_intlist_out
    out
    self
    (match dim with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match dim with
     | None -> -1
     | Some v -> List.length v)
    (if keepdim then 1 else 0)
    (Kind.packed_to_int dtype)
  |> with_tensor_gc
;;

let sum_out ~out self ~dtype =
  stubs_sum_out out self (Kind.packed_to_int dtype) |> with_tensor_gc
;;

let sum_to_size self ~size =
  stubs_sum_to_size
    self
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
  |> with_tensor_gc
;;

let svd self ~some ~compute_uv =
  let out__ = CArray.make raw_tensor 3 in
  stubs_svd
    (CArray.start out__)
    self
    (if some then 1 else 0)
    (if compute_uv then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  let t2 = CArray.get out__ 2 |> with_tensor_gc in
  t0, t1, t2
;;

let svd_u ~u ~s ~v self ~some ~compute_uv =
  let out__ = CArray.make raw_tensor 3 in
  stubs_svd_u
    (CArray.start out__)
    u
    s
    v
    self
    (if some then 1 else 0)
    (if compute_uv then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  let t2 = CArray.get out__ 2 |> with_tensor_gc in
  t0, t1, t2
;;

let swapaxes self ~axis0 ~axis1 =
  stubs_swapaxes self (Int64.of_int axis0) (Int64.of_int axis1) |> with_tensor_gc
;;

let swapaxes_ self ~axis0 ~axis1 =
  stubs_swapaxes_ self (Int64.of_int axis0) (Int64.of_int axis1) |> with_tensor_gc
;;

let swapdims self ~dim0 ~dim1 =
  stubs_swapdims self (Int64.of_int dim0) (Int64.of_int dim1) |> with_tensor_gc
;;

let swapdims_ self ~dim0 ~dim1 =
  stubs_swapdims_ self (Int64.of_int dim0) (Int64.of_int dim1) |> with_tensor_gc
;;

let tr self = stubs_tr self |> with_tensor_gc
let t_ self = stubs_t_ self |> with_tensor_gc
let t_copy self = stubs_t_copy self |> with_tensor_gc
let t_copy_out ~out self = stubs_t_copy_out out self |> with_tensor_gc
let take self ~index = stubs_take self index |> with_tensor_gc

let take_along_dim self ~indices ~dim =
  stubs_take_along_dim
    self
    indices
    (match dim with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match dim with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let take_along_dim_out ~out self ~indices ~dim =
  stubs_take_along_dim_out
    out
    self
    indices
    (match dim with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match dim with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let take_out ~out self ~index = stubs_take_out out self index |> with_tensor_gc
let tan self = stubs_tan self |> with_tensor_gc
let tan_ self = stubs_tan_ self |> with_tensor_gc
let tan_out ~out self = stubs_tan_out out self |> with_tensor_gc
let tanh self = stubs_tanh self |> with_tensor_gc
let tanh_ self = stubs_tanh_ self |> with_tensor_gc

let tanh_backward ~grad_output ~output =
  stubs_tanh_backward grad_output output |> with_tensor_gc
;;

let tanh_backward_grad_input ~grad_input ~grad_output ~output =
  stubs_tanh_backward_grad_input grad_input grad_output output |> with_tensor_gc
;;

let tanh_out ~out self = stubs_tanh_out out self |> with_tensor_gc

let tensor_split self ~sections ~dim =
  stubs_tensor_split self (Int64.of_int sections) (Int64.of_int dim) |> to_tensor_list
;;

let tensor_split_indices self ~indices ~dim =
  stubs_tensor_split_indices
    self
    (List.map Int64.of_int indices |> CArray.of_list int64_t |> CArray.start)
    (List.length indices)
    (Int64.of_int dim)
  |> to_tensor_list
;;

let tensor_split_tensor_indices_or_sections self ~tensor_indices_or_sections ~dim =
  stubs_tensor_split_tensor_indices_or_sections
    self
    tensor_indices_or_sections
    (Int64.of_int dim)
  |> to_tensor_list
;;

let tensordot self other ~dims_self ~dims_other =
  stubs_tensordot
    self
    other
    (List.map Int64.of_int dims_self |> CArray.of_list int64_t |> CArray.start)
    (List.length dims_self)
    (List.map Int64.of_int dims_other |> CArray.of_list int64_t |> CArray.start)
    (List.length dims_other)
  |> with_tensor_gc
;;

let tensordot_out ~out self other ~dims_self ~dims_other =
  stubs_tensordot_out
    out
    self
    other
    (List.map Int64.of_int dims_self |> CArray.of_list int64_t |> CArray.start)
    (List.length dims_self)
    (List.map Int64.of_int dims_other |> CArray.of_list int64_t |> CArray.start)
    (List.length dims_other)
  |> with_tensor_gc
;;

let threshold self ~threshold ~value =
  stubs_threshold self threshold value |> with_tensor_gc
;;

let threshold_ self ~threshold ~value =
  stubs_threshold_ self threshold value |> with_tensor_gc
;;

let threshold_backward ~grad_output self ~threshold =
  stubs_threshold_backward grad_output self threshold |> with_tensor_gc
;;

let threshold_backward_grad_input ~grad_input ~grad_output self ~threshold =
  stubs_threshold_backward_grad_input grad_input grad_output self threshold
  |> with_tensor_gc
;;

let threshold_out ~out self ~threshold ~value =
  stubs_threshold_out out self threshold value |> with_tensor_gc
;;

let tile self ~dims =
  stubs_tile
    self
    (List.map Int64.of_int dims |> CArray.of_list int64_t |> CArray.start)
    (List.length dims)
  |> with_tensor_gc
;;

let to_ self ~device = stubs_to_ self (Device.to_int device) |> with_tensor_gc

let to_dense self ~dtype ~masked_grad =
  stubs_to_dense self (Kind.packed_to_int dtype) (if masked_grad then 1 else 0)
  |> with_tensor_gc
;;

let to_dense_backward ~grad input ~masked_grad =
  stubs_to_dense_backward grad input (if masked_grad then 1 else 0) |> with_tensor_gc
;;

let to_device self ~device ~dtype ~non_blocking ~copy =
  stubs_to_device
    self
    (Device.to_int device)
    (Kind.packed_to_int dtype)
    (if non_blocking then 1 else 0)
    (if copy then 1 else 0)
  |> with_tensor_gc
;;

let to_dtype self ~dtype ~non_blocking ~copy =
  stubs_to_dtype
    self
    (Kind.packed_to_int dtype)
    (if non_blocking then 1 else 0)
    (if copy then 1 else 0)
  |> with_tensor_gc
;;

let to_dtype_layout self ~options ~non_blocking ~copy =
  stubs_to_dtype_layout
    self
    (Kind.packed_to_int (fst options))
    (Device.to_int (snd options))
    (if non_blocking then 1 else 0)
    (if copy then 1 else 0)
  |> with_tensor_gc
;;

let to_mkldnn self ~dtype =
  stubs_to_mkldnn self (Kind.packed_to_int dtype) |> with_tensor_gc
;;

let to_mkldnn_backward ~grad input = stubs_to_mkldnn_backward grad input |> with_tensor_gc

let to_mkldnn_out ~out self ~dtype =
  stubs_to_mkldnn_out out self (Kind.packed_to_int dtype) |> with_tensor_gc
;;

let to_other self other ~non_blocking ~copy =
  stubs_to_other self other (if non_blocking then 1 else 0) (if copy then 1 else 0)
  |> with_tensor_gc
;;

let to_padded_tensor self ~padding ~output_size =
  stubs_to_padded_tensor
    self
    padding
    (match output_size with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match output_size with
     | None -> -1
     | Some v -> List.length v)
  |> with_tensor_gc
;;

let to_padded_tensor_out ~out self ~padding ~output_size =
  stubs_to_padded_tensor_out
    out
    self
    padding
    (match output_size with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match output_size with
     | None -> -1
     | Some v -> List.length v)
  |> with_tensor_gc
;;

let topk self ~k ~dim ~largest ~sorted =
  let out__ = CArray.make raw_tensor 2 in
  stubs_topk
    (CArray.start out__)
    self
    (Int64.of_int k)
    (Int64.of_int dim)
    (if largest then 1 else 0)
    (if sorted then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  t0, t1
;;

let topk_values ~values ~indices self ~k ~dim ~largest ~sorted =
  let out__ = CArray.make raw_tensor 2 in
  stubs_topk_values
    (CArray.start out__)
    values
    indices
    self
    (Int64.of_int k)
    (Int64.of_int dim)
    (if largest then 1 else 0)
    (if sorted then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  t0, t1
;;

let totype self ~scalar_type =
  stubs_totype self (Kind.packed_to_int scalar_type) |> with_tensor_gc
;;

let trace self = stubs_trace self |> with_tensor_gc

let trace_backward ~grad ~sizes =
  stubs_trace_backward
    grad
    (List.map Int64.of_int sizes |> CArray.of_list int64_t |> CArray.start)
    (List.length sizes)
  |> with_tensor_gc
;;

let trace_out ~out self = stubs_trace_out out self |> with_tensor_gc

let transpose self ~dim0 ~dim1 =
  stubs_transpose self (Int64.of_int dim0) (Int64.of_int dim1) |> with_tensor_gc
;;

let transpose_ self ~dim0 ~dim1 =
  stubs_transpose_ self (Int64.of_int dim0) (Int64.of_int dim1) |> with_tensor_gc
;;

let transpose_copy self ~dim0 ~dim1 =
  stubs_transpose_copy self (Int64.of_int dim0) (Int64.of_int dim1) |> with_tensor_gc
;;

let transpose_copy_int_out ~out self ~dim0 ~dim1 =
  stubs_transpose_copy_int_out out self (Int64.of_int dim0) (Int64.of_int dim1)
  |> with_tensor_gc
;;

let trapezoid ~y ~x ~dim = stubs_trapezoid y x (Int64.of_int dim) |> with_tensor_gc

let trapezoid_dx ?dx ~y ~dim () =
  stubs_trapezoid_dx
    y
    (match dx with
     | Some v -> v
     | None -> none_scalar)
    (Int64.of_int dim)
  |> with_tensor_gc
;;

let trapz ~y ~x ~dim = stubs_trapz y x (Int64.of_int dim) |> with_tensor_gc
let trapz_dx ~y ~dx ~dim = stubs_trapz_dx y dx (Int64.of_int dim) |> with_tensor_gc

let triangular_solve self ~a ~upper ~transpose ~unitriangular =
  let out__ = CArray.make raw_tensor 2 in
  stubs_triangular_solve
    (CArray.start out__)
    self
    a
    (if upper then 1 else 0)
    (if transpose then 1 else 0)
    (if unitriangular then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  t0, t1
;;

let triangular_solve_x ~x ~m self ~a ~upper ~transpose ~unitriangular =
  let out__ = CArray.make raw_tensor 2 in
  stubs_triangular_solve_x
    (CArray.start out__)
    x
    m
    self
    a
    (if upper then 1 else 0)
    (if transpose then 1 else 0)
    (if unitriangular then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  t0, t1
;;

let tril self ~diagonal = stubs_tril self (Int64.of_int diagonal) |> with_tensor_gc
let tril_ self ~diagonal = stubs_tril_ self (Int64.of_int diagonal) |> with_tensor_gc

let tril_indices ~row ~col ~offset ~options =
  stubs_tril_indices
    (Int64.of_int row)
    (Int64.of_int col)
    (Int64.of_int offset)
    (Kind.packed_to_int (fst options))
    (Device.to_int (snd options))
  |> with_tensor_gc
;;

let tril_indices_out ~out ~row ~col ~offset =
  stubs_tril_indices_out out (Int64.of_int row) (Int64.of_int col) (Int64.of_int offset)
  |> with_tensor_gc
;;

let tril_out ~out self ~diagonal =
  stubs_tril_out out self (Int64.of_int diagonal) |> with_tensor_gc
;;

let triplet_margin_loss ~anchor ~positive ~negative ~margin ~p ~eps ~swap ~reduction =
  stubs_triplet_margin_loss
    anchor
    positive
    negative
    margin
    p
    eps
    (if swap then 1 else 0)
    (Reduction.to_int reduction |> Int64.of_int)
  |> with_tensor_gc
;;

let triu self ~diagonal = stubs_triu self (Int64.of_int diagonal) |> with_tensor_gc
let triu_ self ~diagonal = stubs_triu_ self (Int64.of_int diagonal) |> with_tensor_gc

let triu_indices ~row ~col ~offset ~options =
  stubs_triu_indices
    (Int64.of_int row)
    (Int64.of_int col)
    (Int64.of_int offset)
    (Kind.packed_to_int (fst options))
    (Device.to_int (snd options))
  |> with_tensor_gc
;;

let triu_indices_out ~out ~row ~col ~offset =
  stubs_triu_indices_out out (Int64.of_int row) (Int64.of_int col) (Int64.of_int offset)
  |> with_tensor_gc
;;

let triu_out ~out self ~diagonal =
  stubs_triu_out out self (Int64.of_int diagonal) |> with_tensor_gc
;;

let true_divide self other = stubs_true_divide self other |> with_tensor_gc
let true_divide_ self other = stubs_true_divide_ self other |> with_tensor_gc

let true_divide_out ~out self other =
  stubs_true_divide_out out self other |> with_tensor_gc
;;

let true_divide_scalar self other = stubs_true_divide_scalar self other |> with_tensor_gc

let true_divide_scalar_ self other =
  stubs_true_divide_scalar_ self other |> with_tensor_gc
;;

let trunc self = stubs_trunc self |> with_tensor_gc
let trunc_ self = stubs_trunc_ self |> with_tensor_gc
let trunc_out ~out self = stubs_trunc_out out self |> with_tensor_gc
let type_as self other = stubs_type_as self other |> with_tensor_gc
let unbind self ~dim = stubs_unbind self (Int64.of_int dim) |> to_tensor_list
let unbind_copy self ~dim = stubs_unbind_copy self (Int64.of_int dim) |> to_tensor_list

let unbind_copy_int_out ~out self ~dim =
  let result =
    stubs_unbind_copy_int_out
      (CArray.of_list gc_tensor out |> CArray.start)
      (List.length out)
      self
      (Int64.of_int dim)
  in
  keep_values_alive out;
  result
;;

let unflatten self ~dim ~sizes =
  stubs_unflatten
    self
    (Int64.of_int dim)
    (List.map Int64.of_int sizes |> CArray.of_list int64_t |> CArray.start)
    (List.length sizes)
  |> with_tensor_gc
;;

let unflatten_dense_tensors ~flat tensors =
  let result =
    stubs_unflatten_dense_tensors
      flat
      (CArray.of_list gc_tensor tensors |> CArray.start)
      (List.length tensors)
    |> to_tensor_list
  in
  keep_values_alive tensors;
  result
;;

let unfold self ~dimension ~size ~step =
  stubs_unfold self (Int64.of_int dimension) (Int64.of_int size) (Int64.of_int step)
  |> with_tensor_gc
;;

let unfold_backward ~grad_in ~input_sizes ~dim ~size ~step =
  stubs_unfold_backward
    grad_in
    (List.map Int64.of_int input_sizes |> CArray.of_list int64_t |> CArray.start)
    (List.length input_sizes)
    (Int64.of_int dim)
    (Int64.of_int size)
    (Int64.of_int step)
  |> with_tensor_gc
;;

let unfold_backward_out ~out ~grad_in ~input_sizes ~dim ~size ~step =
  stubs_unfold_backward_out
    out
    grad_in
    (List.map Int64.of_int input_sizes |> CArray.of_list int64_t |> CArray.start)
    (List.length input_sizes)
    (Int64.of_int dim)
    (Int64.of_int size)
    (Int64.of_int step)
  |> with_tensor_gc
;;

let unfold_copy self ~dimension ~size ~step =
  stubs_unfold_copy self (Int64.of_int dimension) (Int64.of_int size) (Int64.of_int step)
  |> with_tensor_gc
;;

let unfold_copy_out ~out self ~dimension ~size ~step =
  stubs_unfold_copy_out
    out
    self
    (Int64.of_int dimension)
    (Int64.of_int size)
    (Int64.of_int step)
  |> with_tensor_gc
;;

let uniform self ~from ~to_ = stubs_uniform self from to_ |> with_tensor_gc
let uniform_ self ~from ~to_ = stubs_uniform_ self from to_ |> with_tensor_gc

let uniform_out ~out self ~from ~to_ =
  stubs_uniform_out out self from to_ |> with_tensor_gc
;;

let unique_consecutive self ~return_inverse ~return_counts ~dim =
  let out__ = CArray.make raw_tensor 3 in
  stubs_unique_consecutive
    (CArray.start out__)
    self
    (if return_inverse then 1 else 0)
    (if return_counts then 1 else 0)
    (match dim with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match dim with
     | Some _ -> 0
     | None -> 1);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  let t2 = CArray.get out__ 2 |> with_tensor_gc in
  t0, t1, t2
;;

let unique_consecutive_out ~out0 ~out1 ~out2 self ~return_inverse ~return_counts ~dim =
  let out__ = CArray.make raw_tensor 3 in
  stubs_unique_consecutive_out
    (CArray.start out__)
    out0
    out1
    out2
    self
    (if return_inverse then 1 else 0)
    (if return_counts then 1 else 0)
    (match dim with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match dim with
     | Some _ -> 0
     | None -> 1);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  let t2 = CArray.get out__ 2 |> with_tensor_gc in
  t0, t1, t2
;;

let unique_dim self ~dim ~sorted ~return_inverse ~return_counts =
  let out__ = CArray.make raw_tensor 3 in
  stubs_unique_dim
    (CArray.start out__)
    self
    (Int64.of_int dim)
    (if sorted then 1 else 0)
    (if return_inverse then 1 else 0)
    (if return_counts then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  let t2 = CArray.get out__ 2 |> with_tensor_gc in
  t0, t1, t2
;;

let unique_dim_consecutive self ~dim ~return_inverse ~return_counts =
  let out__ = CArray.make raw_tensor 3 in
  stubs_unique_dim_consecutive
    (CArray.start out__)
    self
    (Int64.of_int dim)
    (if return_inverse then 1 else 0)
    (if return_counts then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  let t2 = CArray.get out__ 2 |> with_tensor_gc in
  t0, t1, t2
;;

let unique_dim_consecutive_out ~out0 ~out1 ~out2 self ~dim ~return_inverse ~return_counts =
  let out__ = CArray.make raw_tensor 3 in
  stubs_unique_dim_consecutive_out
    (CArray.start out__)
    out0
    out1
    out2
    self
    (Int64.of_int dim)
    (if return_inverse then 1 else 0)
    (if return_counts then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  let t2 = CArray.get out__ 2 |> with_tensor_gc in
  t0, t1, t2
;;

let unique_dim_out ~out0 ~out1 ~out2 self ~dim ~sorted ~return_inverse ~return_counts =
  let out__ = CArray.make raw_tensor 3 in
  stubs_unique_dim_out
    (CArray.start out__)
    out0
    out1
    out2
    self
    (Int64.of_int dim)
    (if sorted then 1 else 0)
    (if return_inverse then 1 else 0)
    (if return_counts then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  let t2 = CArray.get out__ 2 |> with_tensor_gc in
  t0, t1, t2
;;

let unsafe_chunk self ~chunks ~dim =
  stubs_unsafe_chunk self (Int64.of_int chunks) (Int64.of_int dim) |> to_tensor_list
;;

let unsafe_split self ~split_size ~dim =
  stubs_unsafe_split self (Int64.of_int split_size) (Int64.of_int dim) |> to_tensor_list
;;

let unsafe_split_tensor_out ~out self ~split_size ~dim =
  let result =
    stubs_unsafe_split_tensor_out
      (CArray.of_list gc_tensor out |> CArray.start)
      (List.length out)
      self
      (Int64.of_int split_size)
      (Int64.of_int dim)
  in
  keep_values_alive out;
  result
;;

let unsafe_split_with_sizes self ~split_sizes ~dim =
  stubs_unsafe_split_with_sizes
    self
    (List.map Int64.of_int split_sizes |> CArray.of_list int64_t |> CArray.start)
    (List.length split_sizes)
    (Int64.of_int dim)
  |> to_tensor_list
;;

let unsafe_split_with_sizes_out ~out self ~split_sizes ~dim =
  let result =
    stubs_unsafe_split_with_sizes_out
      (CArray.of_list gc_tensor out |> CArray.start)
      (List.length out)
      self
      (List.map Int64.of_int split_sizes |> CArray.of_list int64_t |> CArray.start)
      (List.length split_sizes)
      (Int64.of_int dim)
  in
  keep_values_alive out;
  result
;;

let unsqueeze self ~dim = stubs_unsqueeze self (Int64.of_int dim) |> with_tensor_gc
let unsqueeze_ self ~dim = stubs_unsqueeze_ self (Int64.of_int dim) |> with_tensor_gc

let unsqueeze_copy self ~dim =
  stubs_unsqueeze_copy self (Int64.of_int dim) |> with_tensor_gc
;;

let unsqueeze_copy_out ~out self ~dim =
  stubs_unsqueeze_copy_out out self (Int64.of_int dim) |> with_tensor_gc
;;

let upsample_bicubic2d self ~output_size ~align_corners ~scales_h ~scales_w =
  stubs_upsample_bicubic2d
    self
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (if align_corners then 1 else 0)
    (Option.value scales_h ~default:0.0)
    (match scales_h with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_w ~default:0.0)
    (match scales_w with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_bicubic2d_backward
  ~grad_output
  ~output_size
  ~input_size
  ~align_corners
  ~scales_h
  ~scales_w
  =
  stubs_upsample_bicubic2d_backward
    grad_output
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (List.map Int64.of_int input_size |> CArray.of_list int64_t |> CArray.start)
    (List.length input_size)
    (if align_corners then 1 else 0)
    (Option.value scales_h ~default:0.0)
    (match scales_h with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_w ~default:0.0)
    (match scales_w with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_bicubic2d_backward_grad_input
  ~grad_input
  ~grad_output
  ~output_size
  ~input_size
  ~align_corners
  ~scales_h
  ~scales_w
  =
  stubs_upsample_bicubic2d_backward_grad_input
    grad_input
    grad_output
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (List.map Int64.of_int input_size |> CArray.of_list int64_t |> CArray.start)
    (List.length input_size)
    (if align_corners then 1 else 0)
    (Option.value scales_h ~default:0.0)
    (match scales_h with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_w ~default:0.0)
    (match scales_w with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_bicubic2d_out ~out self ~output_size ~align_corners ~scales_h ~scales_w =
  stubs_upsample_bicubic2d_out
    out
    self
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (if align_corners then 1 else 0)
    (Option.value scales_h ~default:0.0)
    (match scales_h with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_w ~default:0.0)
    (match scales_w with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_bicubic2d_vec input ~output_size ~align_corners ~scale_factors =
  stubs_upsample_bicubic2d_vec
    input
    (match output_size with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match output_size with
     | None -> -1
     | Some v -> List.length v)
    (if align_corners then 1 else 0)
    (scale_factors |> CArray.of_list double |> CArray.start)
    (List.length scale_factors)
  |> with_tensor_gc
;;

let upsample_bilinear2d self ~output_size ~align_corners ~scales_h ~scales_w =
  stubs_upsample_bilinear2d
    self
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (if align_corners then 1 else 0)
    (Option.value scales_h ~default:0.0)
    (match scales_h with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_w ~default:0.0)
    (match scales_w with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_bilinear2d_backward
  ~grad_output
  ~output_size
  ~input_size
  ~align_corners
  ~scales_h
  ~scales_w
  =
  stubs_upsample_bilinear2d_backward
    grad_output
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (List.map Int64.of_int input_size |> CArray.of_list int64_t |> CArray.start)
    (List.length input_size)
    (if align_corners then 1 else 0)
    (Option.value scales_h ~default:0.0)
    (match scales_h with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_w ~default:0.0)
    (match scales_w with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_bilinear2d_backward_grad_input
  ~grad_input
  ~grad_output
  ~output_size
  ~input_size
  ~align_corners
  ~scales_h
  ~scales_w
  =
  stubs_upsample_bilinear2d_backward_grad_input
    grad_input
    grad_output
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (List.map Int64.of_int input_size |> CArray.of_list int64_t |> CArray.start)
    (List.length input_size)
    (if align_corners then 1 else 0)
    (Option.value scales_h ~default:0.0)
    (match scales_h with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_w ~default:0.0)
    (match scales_w with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_bilinear2d_out ~out self ~output_size ~align_corners ~scales_h ~scales_w =
  stubs_upsample_bilinear2d_out
    out
    self
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (if align_corners then 1 else 0)
    (Option.value scales_h ~default:0.0)
    (match scales_h with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_w ~default:0.0)
    (match scales_w with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_bilinear2d_vec input ~output_size ~align_corners ~scale_factors =
  stubs_upsample_bilinear2d_vec
    input
    (match output_size with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match output_size with
     | None -> -1
     | Some v -> List.length v)
    (if align_corners then 1 else 0)
    (scale_factors |> CArray.of_list double |> CArray.start)
    (List.length scale_factors)
  |> with_tensor_gc
;;

let upsample_bilinear2d_vec_out ~out input ~output_size ~align_corners ~scale_factors =
  stubs_upsample_bilinear2d_vec_out
    out
    input
    (match output_size with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match output_size with
     | None -> -1
     | Some v -> List.length v)
    (if align_corners then 1 else 0)
    (scale_factors |> CArray.of_list double |> CArray.start)
    (List.length scale_factors)
  |> with_tensor_gc
;;

let upsample_linear1d self ~output_size ~align_corners ~scales =
  stubs_upsample_linear1d
    self
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (if align_corners then 1 else 0)
    (Option.value scales ~default:0.0)
    (match scales with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_linear1d_backward
  ~grad_output
  ~output_size
  ~input_size
  ~align_corners
  ~scales
  =
  stubs_upsample_linear1d_backward
    grad_output
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (List.map Int64.of_int input_size |> CArray.of_list int64_t |> CArray.start)
    (List.length input_size)
    (if align_corners then 1 else 0)
    (Option.value scales ~default:0.0)
    (match scales with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_linear1d_backward_grad_input
  ~grad_input
  ~grad_output
  ~output_size
  ~input_size
  ~align_corners
  ~scales
  =
  stubs_upsample_linear1d_backward_grad_input
    grad_input
    grad_output
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (List.map Int64.of_int input_size |> CArray.of_list int64_t |> CArray.start)
    (List.length input_size)
    (if align_corners then 1 else 0)
    (Option.value scales ~default:0.0)
    (match scales with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_linear1d_out ~out self ~output_size ~align_corners ~scales =
  stubs_upsample_linear1d_out
    out
    self
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (if align_corners then 1 else 0)
    (Option.value scales ~default:0.0)
    (match scales with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_linear1d_vec input ~output_size ~align_corners ~scale_factors =
  stubs_upsample_linear1d_vec
    input
    (match output_size with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match output_size with
     | None -> -1
     | Some v -> List.length v)
    (if align_corners then 1 else 0)
    (scale_factors |> CArray.of_list double |> CArray.start)
    (List.length scale_factors)
  |> with_tensor_gc
;;

let upsample_nearest1d self ~output_size ~scales =
  stubs_upsample_nearest1d
    self
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (Option.value scales ~default:0.0)
    (match scales with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_nearest1d_backward ~grad_output ~output_size ~input_size ~scales =
  stubs_upsample_nearest1d_backward
    grad_output
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (List.map Int64.of_int input_size |> CArray.of_list int64_t |> CArray.start)
    (List.length input_size)
    (Option.value scales ~default:0.0)
    (match scales with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_nearest1d_backward_grad_input
  ~grad_input
  ~grad_output
  ~output_size
  ~input_size
  ~scales
  =
  stubs_upsample_nearest1d_backward_grad_input
    grad_input
    grad_output
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (List.map Int64.of_int input_size |> CArray.of_list int64_t |> CArray.start)
    (List.length input_size)
    (Option.value scales ~default:0.0)
    (match scales with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_nearest1d_out ~out self ~output_size ~scales =
  stubs_upsample_nearest1d_out
    out
    self
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (Option.value scales ~default:0.0)
    (match scales with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_nearest1d_vec input ~output_size ~scale_factors =
  stubs_upsample_nearest1d_vec
    input
    (match output_size with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match output_size with
     | None -> -1
     | Some v -> List.length v)
    (scale_factors |> CArray.of_list double |> CArray.start)
    (List.length scale_factors)
  |> with_tensor_gc
;;

let upsample_nearest2d self ~output_size ~scales_h ~scales_w =
  stubs_upsample_nearest2d
    self
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (Option.value scales_h ~default:0.0)
    (match scales_h with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_w ~default:0.0)
    (match scales_w with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_nearest2d_backward ~grad_output ~output_size ~input_size ~scales_h ~scales_w =
  stubs_upsample_nearest2d_backward
    grad_output
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (List.map Int64.of_int input_size |> CArray.of_list int64_t |> CArray.start)
    (List.length input_size)
    (Option.value scales_h ~default:0.0)
    (match scales_h with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_w ~default:0.0)
    (match scales_w with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_nearest2d_backward_grad_input
  ~grad_input
  ~grad_output
  ~output_size
  ~input_size
  ~scales_h
  ~scales_w
  =
  stubs_upsample_nearest2d_backward_grad_input
    grad_input
    grad_output
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (List.map Int64.of_int input_size |> CArray.of_list int64_t |> CArray.start)
    (List.length input_size)
    (Option.value scales_h ~default:0.0)
    (match scales_h with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_w ~default:0.0)
    (match scales_w with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_nearest2d_out ~out self ~output_size ~scales_h ~scales_w =
  stubs_upsample_nearest2d_out
    out
    self
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (Option.value scales_h ~default:0.0)
    (match scales_h with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_w ~default:0.0)
    (match scales_w with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_nearest2d_vec input ~output_size ~scale_factors =
  stubs_upsample_nearest2d_vec
    input
    (match output_size with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match output_size with
     | None -> -1
     | Some v -> List.length v)
    (scale_factors |> CArray.of_list double |> CArray.start)
    (List.length scale_factors)
  |> with_tensor_gc
;;

let upsample_nearest2d_vec_out ~out input ~output_size ~scale_factors =
  stubs_upsample_nearest2d_vec_out
    out
    input
    (match output_size with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match output_size with
     | None -> -1
     | Some v -> List.length v)
    (scale_factors |> CArray.of_list double |> CArray.start)
    (List.length scale_factors)
  |> with_tensor_gc
;;

let upsample_nearest3d self ~output_size ~scales_d ~scales_h ~scales_w =
  stubs_upsample_nearest3d
    self
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (Option.value scales_d ~default:0.0)
    (match scales_d with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_h ~default:0.0)
    (match scales_h with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_w ~default:0.0)
    (match scales_w with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_nearest3d_backward
  ~grad_output
  ~output_size
  ~input_size
  ~scales_d
  ~scales_h
  ~scales_w
  =
  stubs_upsample_nearest3d_backward
    grad_output
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (List.map Int64.of_int input_size |> CArray.of_list int64_t |> CArray.start)
    (List.length input_size)
    (Option.value scales_d ~default:0.0)
    (match scales_d with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_h ~default:0.0)
    (match scales_h with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_w ~default:0.0)
    (match scales_w with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_nearest3d_backward_grad_input
  ~grad_input
  ~grad_output
  ~output_size
  ~input_size
  ~scales_d
  ~scales_h
  ~scales_w
  =
  stubs_upsample_nearest3d_backward_grad_input
    grad_input
    grad_output
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (List.map Int64.of_int input_size |> CArray.of_list int64_t |> CArray.start)
    (List.length input_size)
    (Option.value scales_d ~default:0.0)
    (match scales_d with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_h ~default:0.0)
    (match scales_h with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_w ~default:0.0)
    (match scales_w with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_nearest3d_out ~out self ~output_size ~scales_d ~scales_h ~scales_w =
  stubs_upsample_nearest3d_out
    out
    self
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (Option.value scales_d ~default:0.0)
    (match scales_d with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_h ~default:0.0)
    (match scales_h with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_w ~default:0.0)
    (match scales_w with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_nearest3d_vec input ~output_size ~scale_factors =
  stubs_upsample_nearest3d_vec
    input
    (match output_size with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match output_size with
     | None -> -1
     | Some v -> List.length v)
    (scale_factors |> CArray.of_list double |> CArray.start)
    (List.length scale_factors)
  |> with_tensor_gc
;;

let upsample_trilinear3d self ~output_size ~align_corners ~scales_d ~scales_h ~scales_w =
  stubs_upsample_trilinear3d
    self
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (if align_corners then 1 else 0)
    (Option.value scales_d ~default:0.0)
    (match scales_d with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_h ~default:0.0)
    (match scales_h with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_w ~default:0.0)
    (match scales_w with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_trilinear3d_backward
  ~grad_output
  ~output_size
  ~input_size
  ~align_corners
  ~scales_d
  ~scales_h
  ~scales_w
  =
  stubs_upsample_trilinear3d_backward
    grad_output
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (List.map Int64.of_int input_size |> CArray.of_list int64_t |> CArray.start)
    (List.length input_size)
    (if align_corners then 1 else 0)
    (Option.value scales_d ~default:0.0)
    (match scales_d with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_h ~default:0.0)
    (match scales_h with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_w ~default:0.0)
    (match scales_w with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_trilinear3d_backward_grad_input
  ~grad_input
  ~grad_output
  ~output_size
  ~input_size
  ~align_corners
  ~scales_d
  ~scales_h
  ~scales_w
  =
  stubs_upsample_trilinear3d_backward_grad_input
    grad_input
    grad_output
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (List.map Int64.of_int input_size |> CArray.of_list int64_t |> CArray.start)
    (List.length input_size)
    (if align_corners then 1 else 0)
    (Option.value scales_d ~default:0.0)
    (match scales_d with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_h ~default:0.0)
    (match scales_h with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_w ~default:0.0)
    (match scales_w with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_trilinear3d_out
  ~out
  self
  ~output_size
  ~align_corners
  ~scales_d
  ~scales_h
  ~scales_w
  =
  stubs_upsample_trilinear3d_out
    out
    self
    (List.map Int64.of_int output_size |> CArray.of_list int64_t |> CArray.start)
    (List.length output_size)
    (if align_corners then 1 else 0)
    (Option.value scales_d ~default:0.0)
    (match scales_d with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_h ~default:0.0)
    (match scales_h with
     | Some _ -> 0
     | None -> 1)
    (Option.value scales_w ~default:0.0)
    (match scales_w with
     | Some _ -> 0
     | None -> 1)
  |> with_tensor_gc
;;

let upsample_trilinear3d_vec input ~output_size ~align_corners ~scale_factors =
  stubs_upsample_trilinear3d_vec
    input
    (match output_size with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match output_size with
     | None -> -1
     | Some v -> List.length v)
    (if align_corners then 1 else 0)
    (scale_factors |> CArray.of_list double |> CArray.start)
    (List.length scale_factors)
  |> with_tensor_gc
;;

let value_selecting_reduction_backward ~grad ~dim ~indices ~sizes ~keepdim =
  stubs_value_selecting_reduction_backward
    grad
    (Int64.of_int dim)
    indices
    (List.map Int64.of_int sizes |> CArray.of_list int64_t |> CArray.start)
    (List.length sizes)
    (if keepdim then 1 else 0)
  |> with_tensor_gc
;;

let values self = stubs_values self |> with_tensor_gc
let values_copy self = stubs_values_copy self |> with_tensor_gc
let values_copy_out ~out self = stubs_values_copy_out out self |> with_tensor_gc

let vander ~x ~n ~increasing =
  stubs_vander
    x
    (match n with
     | None -> Int64.zero
     | Some v -> Int64.of_int v)
    (match n with
     | Some _ -> 0
     | None -> 1)
    (if increasing then 1 else 0)
  |> with_tensor_gc
;;

let var self ~unbiased = stubs_var self (if unbiased then 1 else 0) |> with_tensor_gc

let var_correction self ~dim ~correction ~keepdim =
  stubs_var_correction
    self
    (match dim with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match dim with
     | None -> -1
     | Some v -> List.length v)
    correction
    (if keepdim then 1 else 0)
  |> with_tensor_gc
;;

let var_correction_out ~out self ~dim ~correction ~keepdim =
  stubs_var_correction_out
    out
    self
    (match dim with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match dim with
     | None -> -1
     | Some v -> List.length v)
    correction
    (if keepdim then 1 else 0)
  |> with_tensor_gc
;;

let var_dim self ~dim ~unbiased ~keepdim =
  stubs_var_dim
    self
    (match dim with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match dim with
     | None -> -1
     | Some v -> List.length v)
    (if unbiased then 1 else 0)
    (if keepdim then 1 else 0)
  |> with_tensor_gc
;;

let var_mean self ~unbiased =
  let out__ = CArray.make raw_tensor 2 in
  stubs_var_mean (CArray.start out__) self (if unbiased then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  t0, t1
;;

let var_mean_correction self ~dim ~correction ~keepdim =
  let out__ = CArray.make raw_tensor 2 in
  stubs_var_mean_correction
    (CArray.start out__)
    self
    (match dim with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match dim with
     | None -> -1
     | Some v -> List.length v)
    correction
    (if keepdim then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  t0, t1
;;

let var_mean_correction_out ~out0 ~out1 self ~dim ~correction ~keepdim =
  let out__ = CArray.make raw_tensor 2 in
  stubs_var_mean_correction_out
    (CArray.start out__)
    out0
    out1
    self
    (match dim with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match dim with
     | None -> -1
     | Some v -> List.length v)
    correction
    (if keepdim then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  t0, t1
;;

let var_mean_dim self ~dim ~unbiased ~keepdim =
  let out__ = CArray.make raw_tensor 2 in
  stubs_var_mean_dim
    (CArray.start out__)
    self
    (match dim with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match dim with
     | None -> -1
     | Some v -> List.length v)
    (if unbiased then 1 else 0)
    (if keepdim then 1 else 0);
  let t0 = CArray.get out__ 0 |> with_tensor_gc in
  let t1 = CArray.get out__ 1 |> with_tensor_gc in
  t0, t1
;;

let var_out ~out self ~dim ~unbiased ~keepdim =
  stubs_var_out
    out
    self
    (match dim with
     | None -> from_voidp int64_t null
     | Some v -> List.map Int64.of_int v |> CArray.of_list int64_t |> CArray.start)
    (match dim with
     | None -> -1
     | Some v -> List.length v)
    (if unbiased then 1 else 0)
    (if keepdim then 1 else 0)
  |> with_tensor_gc
;;

let vdot self other = stubs_vdot self other |> with_tensor_gc
let vdot_out ~out self other = stubs_vdot_out out self other |> with_tensor_gc

let view self ~size =
  stubs_view
    self
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
  |> with_tensor_gc
;;

let view_as self other = stubs_view_as self other |> with_tensor_gc
let view_as_complex self = stubs_view_as_complex self |> with_tensor_gc
let view_as_complex_copy self = stubs_view_as_complex_copy self |> with_tensor_gc

let view_as_complex_copy_out ~out self =
  stubs_view_as_complex_copy_out out self |> with_tensor_gc
;;

let view_as_real self = stubs_view_as_real self |> with_tensor_gc
let view_as_real_copy self = stubs_view_as_real_copy self |> with_tensor_gc

let view_as_real_copy_out ~out self =
  stubs_view_as_real_copy_out out self |> with_tensor_gc
;;

let view_copy self ~size =
  stubs_view_copy
    self
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
  |> with_tensor_gc
;;

let view_copy_dtype self ~dtype =
  stubs_view_copy_dtype self (Kind.packed_to_int dtype) |> with_tensor_gc
;;

let view_copy_dtype_out ~out self ~dtype =
  stubs_view_copy_dtype_out out self (Kind.packed_to_int dtype) |> with_tensor_gc
;;

let view_copy_out ~out self ~size =
  stubs_view_copy_out
    out
    self
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
  |> with_tensor_gc
;;

let view_dtype self ~dtype =
  stubs_view_dtype self (Kind.packed_to_int dtype) |> with_tensor_gc
;;

let vsplit self ~sections = stubs_vsplit self (Int64.of_int sections) |> to_tensor_list

let vsplit_array self ~indices =
  stubs_vsplit_array
    self
    (List.map Int64.of_int indices |> CArray.of_list int64_t |> CArray.start)
    (List.length indices)
  |> to_tensor_list
;;

let vstack tensors =
  let result =
    stubs_vstack (CArray.of_list gc_tensor tensors |> CArray.start) (List.length tensors)
    |> with_tensor_gc
  in
  keep_values_alive tensors;
  result
;;

let vstack_out ~out tensors =
  let result =
    stubs_vstack_out
      out
      (CArray.of_list gc_tensor tensors |> CArray.start)
      (List.length tensors)
    |> with_tensor_gc
  in
  keep_values_alive tensors;
  result
;;

let where ~condition = stubs_where condition |> to_tensor_list

let where_scalar ~condition self other =
  stubs_where_scalar condition self other |> with_tensor_gc
;;

let where_scalarother ~condition self other =
  stubs_where_scalarother condition self other |> with_tensor_gc
;;

let where_scalarself ~condition self other =
  stubs_where_scalarself condition self other |> with_tensor_gc
;;

let where_self ~condition self other =
  stubs_where_self condition self other |> with_tensor_gc
;;

let where_self_out ~out ~condition self other =
  stubs_where_self_out out condition self other |> with_tensor_gc
;;

let xlogy self other = stubs_xlogy self other |> with_tensor_gc
let xlogy_ self other = stubs_xlogy_ self other |> with_tensor_gc

let xlogy_outscalar_other ~out self other =
  stubs_xlogy_outscalar_other out self other |> with_tensor_gc
;;

let xlogy_outscalar_self ~out self other =
  stubs_xlogy_outscalar_self out self other |> with_tensor_gc
;;

let xlogy_outtensor ~out self other =
  stubs_xlogy_outtensor out self other |> with_tensor_gc
;;

let xlogy_scalar_other self other = stubs_xlogy_scalar_other self other |> with_tensor_gc

let xlogy_scalar_other_ self other =
  stubs_xlogy_scalar_other_ self other |> with_tensor_gc
;;

let xlogy_scalar_self self other = stubs_xlogy_scalar_self self other |> with_tensor_gc
let zero self = stubs_zero self |> with_tensor_gc
let zero_ self = stubs_zero_ self |> with_tensor_gc
let zero_out ~out self = stubs_zero_out out self |> with_tensor_gc

let zeros ~size ~options =
  stubs_zeros
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
    (Kind.packed_to_int (fst options))
    (Device.to_int (snd options))
  |> with_tensor_gc
;;

let zeros_like self = stubs_zeros_like self |> with_tensor_gc
let zeros_like_out ~out self = stubs_zeros_like_out out self |> with_tensor_gc

let zeros_out ~out ~size =
  stubs_zeros_out
    out
    (List.map Int64.of_int size |> CArray.of_list int64_t |> CArray.start)
    (List.length size)
  |> with_tensor_gc
;;
